CREATE SCHEMA HL7BC_SCHEMA;
CREATE TABLE HL7BC_SCHEMA.EXPSEQUENCENO (ID VARCHAR(750), ESN INTEGER, ESNSTATE VARCHAR(2), primary key (ID));
CREATE TABLE HL7BC_SCHEMA.HL7MESSAGELOG (MESSAGEID VARCHAR(250), APPLICATIONID VARCHAR(250) , REQUESTMESSAGE BLOB, RESPONSEMESSAGE BLOB, STATUS SMALLINT, CREATEDTIME TIMESTAMP, LASTUPDATEDTIME TIMESTAMP);
CREATE TABLE HL7BC_SCHEMA.JOURNALHL7MESSAGELOG (APPLICATIONID VARCHAR(500), MESSAGECONTROLID VARCHAR(250), PROCESSMODE VARCHAR(10), REQUESTHL7MESSAGE BLOB, RESPONSEACKMESSAGE BLOB, RESPONSENAKMESSAGE BLOB, STATUS VARCHAR(200));  