<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AsynchronousClientWS" targetNamespace="http://j2ee.netbeans.org/wsdl/AsynchronousClient/AsynchronousClientWS"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/AsynchronousClient/AsynchronousClientWS" xmlns:ns="http://xml.netbeans.org/schema/Common" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/AsynchronousClient/AsynchronousClientWS">
            <xsd:import namespace="http://xml.netbeans.org/schema/Common" schemaLocation="Common.xsd"/>
        </xsd:schema>
    </types>
    <message name="requestMessage">
        <part name="inputType" element="ns:typeA"/>
    </message>
    <message name="responseMessage">
        <part name="resultType" element="ns:typeA"/>
    </message>
    <portType name="AsynchronousClientWSPortType">
        <operation name="AsynchronousClientWSOperation">
            <input name="input1" message="tns:requestMessage"/>
            <output name="output1" message="tns:responseMessage"/>
        </operation>
    </portType>
    <binding name="AsynchronousClientWSBinding" type="tns:AsynchronousClientWSPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="AsynchronousClientWSOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="AsynchronousClientWSService">
        <port name="AsynchronousClientWSPort" binding="tns:AsynchronousClientWSBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/AsynchronousClientWSService/AsynchronousClientWSPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="AsynchronousClientWS">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="AsynchronousClientWSPortTypeRole" portType="tns:AsynchronousClientWSPortType"/>
    </plnk:partnerLinkType>
</definitions>



