<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns="http://j2ee.netbeans.org/wsdl/SendInternalEPRCallbackInfo/asyncRequest" xmlns:ns0="http://xml.netbeans.org/schema/asyncRequest" xmlns:ns1="http://xml.netbeans.org/schema/Common" xmlns:ns2="http://j2ee.netbeans.org/wsdl/SendInternalEPRCallbackInfo/asyncResponse">
    <import namespace="http://j2ee.netbeans.org/wsdl/SendInternalEPRCallbackInfo/asyncRequest" location="asyncRequest.wsdl"/>
    <import namespace="http://j2ee.netbeans.org/wsdl/SendInternalEPRCallbackInfo/asyncResponse" location="asyncResponse.wsdl"/>
    <types>
        <xsd:schema targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties">
            <xsd:import namespace="http://xml.netbeans.org/schema/asyncRequest" schemaLocation="asyncRequest.xsd"/>
            <xsd:import namespace="http://xml.netbeans.org/schema/Common" schemaLocation="Common.xsd"/>
        </xsd:schema>
    </types>
    <vprop:property name="wzrd_prop_paramA_paramA" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_paramA_paramA" messageType="ns:asyncRequestOperationRequest" part="part1">
        <vprop:query>/ns0:request/ns1:typeA/ns1:paramA</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_paramA_paramA" messageType="ns2:asyncResponseOperationRequest" part="part1">
        <vprop:query>/ns1:typeA/ns1:paramA</vprop:query>
    </vprop:propertyAlias>
</definitions>

