<?xml version="1.0" encoding="UTF-8"?>
<definitions name="UndeployableSvc" targetNamespace="http://mngmntmsg.pojose.tst.sun.com/UndeployableSvc/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://mngmntmsg.pojose.tst.sun.com/UndeployableSvc/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="UndeployableSvcOperationRequest">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <message name="UndeployableSvcOperationResponse">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <portType name="UndeployableSvcInterface">
        <operation name="UndeployableSvcOperation">
            <input name="input1" message="tns:UndeployableSvcOperationRequest"/>
            <output name="output1" message="tns:UndeployableSvcOperationResponse"/>
        </operation>
    </portType>
</definitions>
