<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/EvHdlr_InvAndRep_ParentWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/EvHdlr_InvAndRep_ParentWSDL" name="EvHdlr_InvAndRep_ParentWSDL" xmlns:ns="http://xml.netbeans.org/schema/dataTypes.xsd" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns0="http://j2ee.netbeans.org/wsdl/EvHdlr_InvAndRep_subBPWSDL" xmlns:ns1="http://j2ee.netbeans.org/wsdl/Invoke_ReqRespsubBPWSDL">
    <wsdl:import location="EvHdlr_InvAndRep_subBPWSDL.wsdl" namespace="http://j2ee.netbeans.org/wsdl/EvHdlr_InvAndRep_subBPWSDL"/>
    <wsdl:import location="../../Invoke_ReqResp/Invoke_ReqRespsubBPWSDL.wsdl" namespace="http://j2ee.netbeans.org/wsdl/Invoke_ReqRespsubBPWSDL"/>
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/EvHdlr_InvAndRep_ParentWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/dataTypes.xsd" schemaLocation="../../dataTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="EvHdlr_InvAndRep_ParentWSDLOperationRequest">
        <wsdl:part name="part1" element="ns:helloObj"/>
    </wsdl:message>
    <wsdl:message name="EvHdlr_InvAndRep_ParentWSDLOperationReply">
        <wsdl:part name="part1" element="ns:helloObj"/>
    </wsdl:message>
    <wsdl:portType name="EvHdlr_InvAndRep_ParentWSDLPortType">
        <wsdl:operation name="EvHdlr_InvAndRep_ParentWSDLOperation">
            <wsdl:input name="input1" message="tns:EvHdlr_InvAndRep_ParentWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:EvHdlr_InvAndRep_ParentWSDLOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="EvHdlr_InvAndRep_ParentWSDLBinding" type="tns:EvHdlr_InvAndRep_ParentWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="EvHdlr_InvAndRep_ParentWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="EvHdlr_InvAndRep_ParentWSDLService">
        <wsdl:port name="EvHdlr_InvAndRep_ParentWSDLPort" binding="tns:EvHdlr_InvAndRep_ParentWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/EvHdlr_InvAndRep_ParentWSDLService/EvHdlr_InvAndRep_ParentWSDLPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="EvHdlr_InvAndRep_ParentWSDLPartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="EvHdlr_InvAndRep_ParentWSDLPortTypeRole" portType="tns:EvHdlr_InvAndRep_ParentWSDLPortType"/>
    </plnk:partnerLinkType>

    <vprop:property name="property1" type="xsd:string"/>    
    <vprop:propertyAlias propertyName="tns:property1"
        messageType="tns:EvHdlr_InvAndRep_ParentWSDLOperationRequest" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:string</vprop:query>
    </vprop:propertyAlias>    
    <vprop:propertyAlias propertyName="tns:property1"
        messageType="ns0:EvHdlr_InvAndRep_subBPWSDLOperationRequest1" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:string</vprop:query>
    </vprop:propertyAlias>       
    
    <vprop:property name="property2" type="xsd:int"/>
    <vprop:propertyAlias propertyName="tns:property2"
        messageType="ns0:EvHdlr_InvAndRep_subBPWSDLOperationRequest1" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:int</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property2"
        messageType="ns1:Invoke_ReqRespsubBPWSDLOperationRequest" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:int</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property2"
        messageType="ns1:Invoke_ReqRespsubBPWSDLOperationReply" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:int</vprop:query>
    </vprop:propertyAlias>     
    <vprop:propertyAlias propertyName="tns:property2"
        messageType="tns:EvHdlr_InvAndRep_ParentWSDLOperationReply" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:int</vprop:query>
    </vprop:propertyAlias>     
    
    <vprop:property name="property3" type="xsd:long"/>
    <vprop:propertyAlias propertyName="tns:property3"
        messageType="ns0:EvHdlr_InvAndRep_subBPWSDLOperationRequest1" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:long</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property3"
        messageType="ns1:Invoke_ReqRespsubBPWSDLOperationRequest" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:long</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property3"
        messageType="ns1:Invoke_ReqRespsubBPWSDLOperationReply" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:long</vprop:query>
    </vprop:propertyAlias>     
    <vprop:propertyAlias propertyName="tns:property3"
        messageType="tns:EvHdlr_InvAndRep_ParentWSDLOperationReply" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:long</vprop:query>
    </vprop:propertyAlias>  
    
    <vprop:property name="property4" type="xsd:double"/>    
    <vprop:propertyAlias propertyName="tns:property4"
        messageType="ns0:EvHdlr_InvAndRep_subBPWSDLOperationRequest1" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:double</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property4"
        messageType="ns1:Invoke_ReqRespsubBPWSDLOperationRequest" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:double</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property4"
        messageType="ns1:Invoke_ReqRespsubBPWSDLOperationReply" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:double</vprop:query>
    </vprop:propertyAlias>     
    <vprop:propertyAlias propertyName="tns:property4"
        messageType="tns:EvHdlr_InvAndRep_ParentWSDLOperationReply" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:recursive/ns:double</vprop:query>
    </vprop:propertyAlias>
    
</definitions>
