<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AlterTableFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="AlterTableFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="AlterTableFullQualRequest">
    <part name="AlterTableFullQualRequestPart" element="tns:AlterTableFullQualRequest"/>
  </message>
  <message name="AlterTableFullQualResponse">
    <part name="AlterTableFullQualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="AlterTableFullQualSql_sqlsePortType">
    <operation name="AlterTableFullQual">
      <input name="AlterTableFullQualRequest" message="tns:AlterTableFullQualRequest"/>
      <output name="AlterTableFullQualResponse" message="tns:AlterTableFullQualResponse"/>
    </operation>
  </portType>
  <binding name="AlterTableFullQualSqlBinding" type="tns:AlterTableFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="AlterTableFullQual">
      <soap:operation/>
      <input name="AlterTableFullQualRequest">
        <soap:body/>
      </input>
      <output name="AlterTableFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="AlterTableFullQualSql_sqlseService">
    <port name="AlterTableFullQualSql_sqlsePort" binding="tns:AlterTableFullQualSqlBinding">
      <soap:address location="http://localhost:18181/AlterTableFullQualSql/AlterTableFullQualSql/AlterTableFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="AlterTableFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="AlterTableFullQualSql_myrole" portType="tns:AlterTableFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
