/*
 * @(#)NameAndLocationVisualPanel.java        $Revision: 1.1.1.1 $ $Date: 2008/06/30 08:53:20 $
 * 
 * Copyright (c) 2008 Milan Fort (http://www.milanfort.com/). All rights reserved.
 * 
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the "License"). You may not use this file except
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at http://www.sun.com/cddl/cddl.html.
 * See the License for the specific language governing permissions and limitations
 * under the License.
 */

package org.openesb.components.rules4jbi.netbeans.project.wizard;

import java.io.File;
import java.util.ResourceBundle;
import javax.swing.JFileChooser;
import javax.swing.event.DocumentListener;
import org.openide.awt.Mnemonics;
import org.openide.filesystems.FileUtil;
import org.openide.util.NbBundle;

/**
 *
 * @author Milan Fort (http://www.milanfort.com/)
 * @version $Revision: 1.1.1.1 $ $Date: 2008/06/30 08:53:20 $
 * 
 * @since 0.1
 */
public class NameAndLocationVisualPanel extends javax.swing.JPanel {
    
    private static final long serialVersionUID = -2449366228226639442L;
    
    private ResourceBundle resourceBundle = NbBundle.getBundle(NameAndLocationVisualPanel.class);

    /** Creates new form NameAndLocationVisualPanel */
    public NameAndLocationVisualPanel() {
        initComponents();
        
        Mnemonics.setLocalizedText(
                projectNameLabel, resourceBundle.getString("NameAndLocationVisualPanel.projectNameLabel.text"));
        
        Mnemonics.setLocalizedText(
                projectLocationLabel, resourceBundle.getString("NameAndLocationVisualPanel.projectLocationLabel.text"));
        
        Mnemonics.setLocalizedText(
                createdFolderLabel, resourceBundle.getString("NameAndLocationVisualPanel.createdFolderLabel.text"));
        
        Mnemonics.setLocalizedText(
                createdFolderLabel, resourceBundle.getString("NameAndLocationVisualPanel.createdFolderLabel.text"));

        Mnemonics.setLocalizedText(
                browseButton, resourceBundle.getString("NameAndLocationVisualPanel.browseButton.text"));
                
        Mnemonics.setLocalizedText(
                mainProjectCheckBox, resourceBundle.getString("NameAndLocationVisualPanel.mainProjectCheckBox.text"));
    }
    
    @Override
    public String getName() {
        
        /* Using resourceBundle instance variable here causes NPE */
        return NbBundle.getMessage(NameAndLocationVisualPanel.class, "NameAndLocationPanel.name");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectNameLabel = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        projectLocationLabel = new javax.swing.JLabel();
        projectLocationTextField = new javax.swing.JTextField();
        createdFolderLabel = new javax.swing.JLabel();
        createdFolderTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        mainProjectCheckBox = new javax.swing.JCheckBox();

        projectNameLabel.setLabelFor(projectNameTextField);
        projectNameLabel.setText(org.openide.util.NbBundle.getMessage(NameAndLocationVisualPanel.class, "NameAndLocationVisualPanel.projectNameLabel.text")); // NOI18N

        projectNameTextField.setText(org.openide.util.NbBundle.getMessage(NameAndLocationVisualPanel.class, "NameAndLocationVisualPanel.projectNameTextField.text")); // NOI18N

        projectLocationLabel.setLabelFor(projectLocationTextField);
        projectLocationLabel.setText(org.openide.util.NbBundle.getMessage(NameAndLocationVisualPanel.class, "NameAndLocationVisualPanel.projectLocationLabel.text")); // NOI18N

        projectLocationTextField.setEditable(false);
        projectLocationTextField.setText(org.openide.util.NbBundle.getMessage(NameAndLocationVisualPanel.class, "NameAndLocationVisualPanel.projectLocationTextField.text")); // NOI18N

        createdFolderLabel.setLabelFor(createdFolderTextField);
        createdFolderLabel.setText(org.openide.util.NbBundle.getMessage(NameAndLocationVisualPanel.class, "NameAndLocationVisualPanel.createdFolderLabel.text")); // NOI18N

        createdFolderTextField.setEditable(false);
        createdFolderTextField.setText(org.openide.util.NbBundle.getMessage(NameAndLocationVisualPanel.class, "NameAndLocationVisualPanel.createdFolderTextField.text")); // NOI18N

        browseButton.setText(org.openide.util.NbBundle.getMessage(NameAndLocationVisualPanel.class, "NameAndLocationVisualPanel.browseButton.text")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        mainProjectCheckBox.setSelected(true);
        mainProjectCheckBox.setText(org.openide.util.NbBundle.getMessage(NameAndLocationVisualPanel.class, "NameAndLocationVisualPanel.mainProjectCheckBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectLocationLabel)
                            .addComponent(projectNameLabel)
                            .addComponent(createdFolderLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(createdFolderTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(projectLocationTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton))
                    .addComponent(mainProjectCheckBox))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameLabel)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLocationLabel)
                    .addComponent(projectLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdFolderLabel)
                    .addComponent(createdFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainProjectCheckBox)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
    JFileChooser chooser = new JFileChooser();
    FileUtil.preventFileChooserSymlinkTraversal(chooser, null);
    chooser.setDialogTitle(resourceBundle.getString("NameAndLocationVisualPanel.fileChooser.title"));
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    String projectLocationPath = projectLocationTextField.getText();
    if (projectLocationPath.length() > 0) {
        File file = new File(projectLocationPath);
        
        if (file.exists()) {
            chooser.setSelectedFile(file);
        }
    }
    
    if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
        File selectedDirectory = chooser.getSelectedFile();
        projectLocationTextField.setText(FileUtil.normalizeFile(selectedDirectory).getAbsolutePath());
    }
}//GEN-LAST:event_browseButtonActionPerformed
    
    void addDocumentListener(DocumentListener listener) {
        projectNameTextField.getDocument().addDocumentListener(listener);
        projectLocationTextField.getDocument().addDocumentListener(listener);
    }
    
    String getProjectName() {
        return projectNameTextField.getText();
    }
    
    void setProjectName(String projectName) {
        projectNameTextField.setText(projectName);
    }
    
    String getProjectLocation() {
        return projectLocationTextField.getText();
    }
    
    void setProjectLocation(String projectLocation) {
        projectLocationTextField.setText(projectLocation);
    }
    
    String getCreatedFolder() {
        return createdFolderTextField.getText();
    }
    
    void setCreatedFolder(String createdFolder) {
        createdFolderTextField.setText(createdFolder);
    }
    
    boolean isSetAsMainProject() {
        return mainProjectCheckBox.isSelected();
    }
    
    void setAsMainProject(boolean selected) {
        mainProjectCheckBox.setSelected(selected);
    }
    
    void selectWholeProjectName() {
        projectNameTextField.selectAll();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel createdFolderLabel;
    private javax.swing.JTextField createdFolderTextField;
    private javax.swing.JCheckBox mainProjectCheckBox;
    private javax.swing.JLabel projectLocationLabel;
    private javax.swing.JTextField projectLocationTextField;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
