/*
 * @(#)RuleEngineVisualPanel.java        $Revision: 1.1.1.1 $ $Date: 2008/06/30 08:53:20 $
 * 
 * Copyright (c) 2008 Milan Fort (http://www.milanfort.com/). All rights reserved.
 * 
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the "License"). You may not use this file except
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at http://www.sun.com/cddl/cddl.html.
 * See the License for the specific language governing permissions and limitations
 * under the License.
 */

package org.openesb.components.rules4jbi.netbeans.project.wizard;

import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import org.openide.awt.Mnemonics;
import org.openide.util.NbBundle;

/**
 *
 * @author Milan Fort (http://www.milanfort.com/)
 * @version $Revision: 1.1.1.1 $ $Date: 2008/06/30 08:53:20 $
 * 
 * @since 0.1
 */
public class RuleEngineVisualPanel extends javax.swing.JPanel {
    
    private static final long serialVersionUID = -2449366228226639442L;
    
    private ResourceBundle resourceBundle = NbBundle.getBundle(RuleEngineVisualPanel.class);

    /** Creates new form RuleEngineVisualPanel */
    public RuleEngineVisualPanel() {
        initComponents();
        
        Mnemonics.setLocalizedText(
                uriLabel, resourceBundle.getString("RuleEngineVisualPanel.uriLabel.text"));
        
        Mnemonics.setLocalizedText(
                classLabel, resourceBundle.getString("RuleEngineVisualPanel.classLabel.text"));
    }
    
    @Override
    public String getName() {
        
        /* Using resourceBundle instance variable here causes NPE */
        return NbBundle.getMessage(RuleEngineVisualPanel.class, "RuleEnginePanel.name");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uriLabel = new javax.swing.JLabel();
        classLabel = new javax.swing.JLabel();
        uriComboBox = new javax.swing.JComboBox();
        classComboBox = new javax.swing.JComboBox();

        uriLabel.setLabelFor(uriComboBox);
        uriLabel.setText(org.openide.util.NbBundle.getMessage(RuleEngineVisualPanel.class, "RuleEngineVisualPanel.uriLabel.text")); // NOI18N

        classLabel.setLabelFor(classComboBox);
        classLabel.setText(org.openide.util.NbBundle.getMessage(RuleEngineVisualPanel.class, "RuleEngineVisualPanel.classLabel.text")); // NOI18N

        uriComboBox.setEditable(true);

        classComboBox.setEditable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classLabel)
                    .addComponent(uriLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uriComboBox, 0, 272, Short.MAX_VALUE)
                    .addComponent(classComboBox, 0, 272, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uriLabel)
                    .addComponent(uriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLabel)
                    .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    void clearSelectedItems() {
        uriComboBox.setSelectedIndex(-1);
        classComboBox.setSelectedIndex(-1);
    }
    
    void setProviderURIs(String[] uris) {
        uriComboBox.setModel(new DefaultComboBoxModel(uris));
    }

    void setProviderClassNames(String[] classNames) {
        classComboBox.setModel(new DefaultComboBoxModel(classNames));
    }
    
    String getSelectedProvider() {
        return (String) uriComboBox.getSelectedItem();
    }

    String getSelectedProviderClass() {
        return (String) classComboBox.getSelectedItem();
    }
    
    void selectProvider(String uri) {
        uriComboBox.setSelectedItem(uri);
    }

    void selectProviderClass(String className) {
        classComboBox.setSelectedItem(className);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox classComboBox;
    private javax.swing.JLabel classLabel;
    private javax.swing.JComboBox uriComboBox;
    private javax.swing.JLabel uriLabel;
    // End of variables declaration//GEN-END:variables
}
