<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AlterNonEmptyTableSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="AlterNonEmptyTableRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="AlterNonEmptyTableResponse">
    <part name="AlterNonEmptyTableResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="AlterNonEmptyTableRequest">
    <part name="AlterNonEmptyTableRequestPart" element="tns:AlterNonEmptyTableRequest"/>
  </message>
  <portType name="AlterNonEmptyTableSql_sqlsePortType">
    <operation name="AlterNonEmptyTable">
      <input name="AlterNonEmptyTableRequest" message="tns:AlterNonEmptyTableRequest"/>
      <output name="AlterNonEmptyTableResponse" message="tns:AlterNonEmptyTableResponse"/>
    </operation>
  </portType>
  <binding name="AlterNonEmptyTableSqlBinding" type="tns:AlterNonEmptyTableSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="AlterNonEmptyTable">
      <soap:operation/>
      <input name="AlterNonEmptyTableRequest">
        <soap:body/>
      </input>
      <output name="AlterNonEmptyTableResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="AlterNonEmptyTableSql_sqlseService">
    <port name="AlterNonEmptyTableSql_sqlsePort" binding="tns:AlterNonEmptyTableSqlBinding">
      <soap:address location="http://localhost:18181/AlterNonEmptyTableSql/AlterNonEmptyTableSql/AlterNonEmptyTableSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="AlterNonEmptyTableSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="AlterNonEmptyTableSql_myrole" portType="tns:AlterNonEmptyTableSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
