//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module testproviderfault{
		
                                    struct EchoStruct {
                                        boolean            fieldBoolean;
                                        char               fieldChar;
                                        string             fieldString;
                                        long               fieldLong;
                                    };								            				
		            				
                                    exception EchoComplexException {
            				EchoStruct reason;
                                    };       		       
            				
                                    exception EchoSimpleException {
            				string reason;
                                    };       				

                                    interface EchoFault {
					string echo(in string msg) raises (EchoSimpleException, EchoComplexException);
                                    };
				};
			};
		};
	};
};