//IDL
module it{
module imolinfo{
module jbi4corba{
module test{
module testproviderenum{


	enum EchoComplexEnum {E1, E2, E3};

	interface foo {

		EchoComplexEnum echoEnum(in EchoComplexEnum e);

	};

};
};
};
};
};
