<?xml version="1.0" encoding="UTF-8"?>


<wsdl:definitions name="WhileEmpty"
             targetNamespace="http://www.mycomp.org/WhileEmpty/WhileEmpty"
             xmlns:tns="http://www.mycomp.org/WhileEmpty/WhileEmpty"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"                          
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns0="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:message name="EmptyMessage">
        <wsdl:part name="request" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="EmptyResponse">
        <wsdl:part name="response" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="CountMessage">
        <wsdl:part name="Count" type="xsd:int"/>
    </wsdl:message>
    <wsdl:portType name="EmptyPort">
        <wsdl:operation name="EmptyOperation">
            <wsdl:input name="inputmsg" message="tns:EmptyMessage"/>
            <wsdl:output name="outputmsg" message="tns:EmptyResponse"/>
        </wsdl:operation>
    </wsdl:portType>

        <binding name="EmptyBinding" type="tns:EmptyPort">
            <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
                <operation name="EmptyOperation">
                        <soap:operation style="document"/>
                        <input name="inputmsg">
                                <soap:body use="literal"/>
                        </input><output name="outputmsg">
    <soap:body use="literal"/>
</output>
                </operation>
        </binding>

   
         <wsdl:service name="WhileEmptyService">
		<wsdl:port name="WhileEmptyPort" binding="tns:EmptyBinding">                    
                     <soap:address location="http://localhost:${HttpDefaultPort}/WhileEmpty"/>
		</wsdl:port>
        </wsdl:service>

	<plnk:partnerLinkType name="WhileEmptyPartnerLinkType">
		<plnk:role name="WhileEmptyProvider" portType="tns:EmptyPort"/>
	</plnk:partnerLinkType>

</wsdl:definitions>


 

 

 

 

 
