<?xml version="1.0" encoding="windows-1252"?>
<definitions name="FunctionalTest1" targetNamespace="http://j2ee.netbeans.org/wsdl/FunctionalTest1"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/FunctionalTest1" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="message1">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="portType1">
        <operation name="FunctionalTest1Operation">
            <input name="input1" message="tns:message1"/>
            <output name="output1"	message="tns:message1"/>
        </operation>
    </portType>
    <portType name="portType2">
        <operation name="FunctionalTest1Operation">
            <input name="input1" message="tns:message1"/>
        </operation>
    </portType>
    <portType name="portType3">
        <operation name="FunctionalTest1Operation">
            <input name="input1" message="tns:message1"/>
        </operation>
    </portType>    
    <plnk:partnerLinkType name="partnerlinktype1">
        <plnk:role name="role1" portType="tns:portType1"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="invoke1PLT">
        <plnk:role name="role1" portType="tns:portType2"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="invoke2PLT">
        <plnk:role name="role2" portType="tns:portType3"/>
    </plnk:partnerLinkType>
</definitions>
