<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" 
xmlns:tns="http://beltDetail.demo.sun.com/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
targetNamespace="http://beltDetail.demo.sun.com/" 
name="BeltDetailEJBService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://beltDetail.demo.sun.com/" 
      schemaLocation="BeltDetail.xsd" 
      xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
      xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </xsd:schema>
  </types>
  <message name="getBeltDetail">
    <part name="parameters" element="tns:getBeltDetail"/>
  </message>
  <message name="getBeltDetailResponse">
    <part name="parameters" element="tns:getBeltDetailResponse"/>
  </message>
  <portType name="BeltDetailEJB">
    <operation name="getBeltDetail">
      <input message="tns:getBeltDetail"/>
      <output message="tns:getBeltDetailResponse"/>
    </operation>
  </portType>
  <binding name="BeltDetailEJBPortBinding" type="tns:BeltDetailEJB">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="getBeltDetail">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="BeltDetailEJBService">
    <port name="BeltDetailEJBPort" binding="tns:BeltDetailEJBPortBinding">
      <soap:address location="REPLACE_WITH_ACTUAL_URL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </port>
  </service>
</definitions>
