<?xml version="1.0" encoding="windows-1252"?>
<definitions name="BPTypeHierarchy" targetNamespace="http://j2ee.netbeans.org/wsdl/TypeHierarchy/BPTypeHierarchy"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/TypeHierarchy/BPTypeHierarchy" xmlns:ns="http://localhost/person" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/TypeHierarchy/BPTypeHierarchy">
            <xsd:import namespace="http://localhost/person" schemaLocation="schema/person.xsd"/>
        </xsd:schema>
    </types>
    <message name="BPTypeHierarchyOperationRequest">
        <part name="part1" element="ns:person"/>
    </message>
    <message name="BPTypeHierarchyOperationResponse">
        <part name="part1" element="ns:person"/>
    </message>
    <portType name="BPTypeHierarchyPortType">
        <operation name="BPTypeHierarchyOperation">
            <input name="input1" message="tns:BPTypeHierarchyOperationRequest"/>
            <output name="output1" message="tns:BPTypeHierarchyOperationResponse"/>
        </operation>
    </portType>
    <binding name="BPTypeHierarchyBinding" type="tns:BPTypeHierarchyPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="BPTypeHierarchyOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="BPTypeHierarchyService">
        <port name="BPTypeHierarchyPort" binding="tns:BPTypeHierarchyBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/BPTypeHierarchyService/BPTypeHierarchyPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="BPTypeHierarchy">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="BPTypeHierarchyPortTypeRole" portType="tns:BPTypeHierarchyPortType"/>
    </plnk:partnerLinkType>
</definitions>
