/*
 * @(#)FileTypeVisualPanel.java        $Revision: 1.2 $ $Date: 2008/11/12 08:26:21 $
 * 
 * Copyright (c) 2008 Milan Fort (http://www.milanfort.com/). All rights reserved.
 * 
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the "License"). You may not use this file except
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at http://www.sun.com/cddl/cddl.html.
 * See the License for the specific language governing permissions and limitations
 * under the License.
 */

package org.openesb.components.rules4jbi.netbeans.project.fileimport;

import java.awt.Dimension;
import org.openide.util.NbBundle;

/**
 *
 * @author Milan Fort (http://www.milanfort.com/)
 * @version $Revision: 1.2 $ $Date: 2008/11/12 08:26:21 $
 * 
 * @since 0.3
 */
public class FileTypeVisualPanel extends javax.swing.JPanel {
    
    private static final long serialVersionUID = -2449366228226639442L;

    /** Creates new form FileTypeVisualPanel */
    public FileTypeVisualPanel() {
        initComponents();
        
        fileTypeList.setCellRenderer(new FileTypeRenderer());
        
        setPreferredSize(new Dimension(
                Constants.PANEL_PREFERRED_SIZE_WIDTH, Constants.PANEL_PREFERRED_SIZE_HEIGHT));
    }

    @Override
    public String getName() {
        
        return NbBundle.getMessage(FileTypeVisualPanel.class, "FileTypePanel.name");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileTypeLabel = new javax.swing.JLabel();
        fileTypeScrollPane = new javax.swing.JScrollPane();
        fileTypeList = new javax.swing.JList();

        fileTypeLabel.setLabelFor(fileTypeList);
        fileTypeLabel.setText(org.openide.util.NbBundle.getMessage(FileTypeVisualPanel.class, "FileTypeVisualPanel.fileTypeLabel.text")); // NOI18N

        fileTypeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        fileTypeList.setVisibleRowCount(4);
        fileTypeScrollPane.setViewportView(fileTypeList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileTypeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(fileTypeLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileTypeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    void setFileTypes(FileType[] fileTypes) {
        fileTypeList.setListData(fileTypes);
    }
    
    void selectFirstFileType() {
        fileTypeList.setSelectedIndex(0);
        fileTypeList.ensureIndexIsVisible(0);
    }
    
    FileType getSelectedFileType() {
        return (FileType) fileTypeList.getSelectedValue();
    }

    void selectFileType(FileType fileType) {
        fileTypeList.setSelectedValue(fileType, true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileTypeLabel;
    private javax.swing.JList fileTypeList;
    private javax.swing.JScrollPane fileTypeScrollPane;
    // End of variables declaration//GEN-END:variables
}
