//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.10 at 01:36:48 PM IST 
//
package com.zaz.jbi.engine.screenscrapingse.scrconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.</p>
 *  <p>The following schema fragment specifies the expected content contained within this
 * class.<pre>&lt;complexType>  &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required">        &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="simple"/>            &lt;enumeration value="xsdType"/>
 *           &lt;/restriction>        &lt;/simpleType>      &lt;/attribute>
 *       &lt;attribute name="xsdname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>  &lt;/complexContent>&lt;/complexType></pre></p>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "parameter")
public class Parameter {

    /**
     * DOCUMENT ME!
     */
    @XmlAttribute(required = true)
    protected String name;
    /**
     * DOCUMENT ME!
     */
    @XmlAttribute(required = true)
    protected String type;
    /**
     * DOCUMENT ME!
     */
    @XmlAttribute(required = true)
    protected String xsdname;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the xsdname property.
     *
     * @return possible object is {@link String }
     */
    public String getXsdname() {
        return xsdname;
    }

    /**
     * Sets the value of the xsdname property.
     *
     * @param value allowed object is {@link String }
     */
    public void setXsdname(String value) {
        this.xsdname = value;
    }
}
