<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InsertWrongNumValSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="InsertWrongNumValRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="InsertWrongNumValResponse">
    <part name="InsertWrongNumValResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="InsertWrongNumValRequest">
    <part name="InsertWrongNumValRequestPart" element="tns:InsertWrongNumValRequest"/>
  </message>
  <portType name="InsertWrongNumValSql_sqlsePortType">
    <operation name="InsertWrongNumVal">
      <input name="InsertWrongNumValRequest" message="tns:InsertWrongNumValRequest"/>
      <output name="InsertWrongNumValResponse" message="tns:InsertWrongNumValResponse"/>
    </operation>
  </portType>
  <binding name="InsertWrongNumValSqlBinding" type="tns:InsertWrongNumValSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="InsertWrongNumVal">
      <soap:operation/>
      <input name="InsertWrongNumValRequest">
        <soap:body/>
      </input>
      <output name="InsertWrongNumValResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="InsertWrongNumValSql_sqlseService">
    <port name="InsertWrongNumValSql_sqlsePort" binding="tns:InsertWrongNumValSqlBinding">
      <soap:address location="http://localhost:18181/InsertWrongNumValSql/InsertWrongNumValSql/InsertWrongNumValSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="InsertWrongNumValSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="InsertWrongNumValSql_myrole" portType="tns:InsertWrongNumValSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
