<?xml version="1.0" encoding="UTF-8"?>
<definitions
    targetNamespace="http://j2ee.netbeans.org/wsdl/TestCustomEncoder/Correlation"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Correlation"
    xmlns:tns="http://j2ee.netbeans.org/wsdl/TestCustomEncoder/Correlation"
    xmlns:ns2="http://j2ee.netbeans.org/wsdl/TestCustomEncoder/ReadResult"
    xmlns:ns1="http://j2ee.netbeans.org/wsdl/TestCustomEncoder/ProviderResult"
    xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
    xmlns:ns4="http://xml.netbeans.org/schema/TestCustomEncoder/OutputEnvelope">
    <import location="../Reply/ReadResult.wsdl"
        namespace="http://j2ee.netbeans.org/wsdl/TestCustomEncoder/ReadResult"/>
    <import location="../Reply/ProviderResult.wsdl"
        namespace="http://j2ee.netbeans.org/wsdl/TestCustomEncoder/ProviderResult"/>
    <types/>
    <vprop:property name="JoinAction" type="xsd:string"/>
    <vprop:propertyAlias
        propertyName="tns:JoinAction"
        messageType="ns2:ReadResultOperationRequest"
        part="rroIn">
        <vprop:query>ns4:Action</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias
        propertyName="tns:JoinAction"
        messageType="ns1:ProviderResultOperationRequest"
        part="proIn"/>
</definitions>
