<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongTableNameFullSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongTableNameFullRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongTableNameFullResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongTableNameFullRequest">
    <part name="SelectWrongTableNameFullRequestPart" element="tns:SelectWrongTableNameFullRequest"/>
  </message>
  <message name="SelectWrongTableNameFullResponse">
    <part name="SelectWrongTableNameFullResponsePart" element="tns:SelectWrongTableNameFullResponse"/>
  </message>
  <portType name="SelectWrongTableNameFullSql_sqlsePortType">
    <operation name="SelectWrongTableNameFull">
      <input name="SelectWrongTableNameFullRequest" message="tns:SelectWrongTableNameFullRequest"/>
      <output name="SelectWrongTableNameFullResponse" message="tns:SelectWrongTableNameFullResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongTableNameFullSqlBinding" type="tns:SelectWrongTableNameFullSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongTableNameFull">
      <soap:operation/>
      <input name="SelectWrongTableNameFullRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongTableNameFullResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongTableNameFullSql_sqlseService">
    <port name="SelectWrongTableNameFullSql_sqlsePort" binding="tns:SelectWrongTableNameFullSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongTableNameFullSql/SelectWrongTableNameFullSql/SelectWrongTableNameFullSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongTableNameFullSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongTableNameFullSql_myrole" portType="tns:SelectWrongTableNameFullSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
