<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/driverWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="driverWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://j2ee.netbeans.org/wsdl/driverWSDL" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" xmlns:ns5="http://j2ee.netbeans.org/wsdl/Corr-FlowAsStartActivity" xmlns:ns="http://xml.netbeans.org/schema/Corr-Flow-inlineSchema">
    <wsdl:import location="Corr-FlowAsStartActivity.wsdl" namespace="http://j2ee.netbeans.org/wsdl/Corr-FlowAsStartActivity"/>
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/driverWSDL">
            <xsd:import schemaLocation="newXmlSchema.xsd" namespace="http://xml.netbeans.org/schema/Corr-Flow-inlineSchema"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="driverWSDLOperationRequest">
        <wsdl:part name="part1" element="ns:elem"/>
    </wsdl:message>
    <wsdl:message name="driverWSDLOperationReply">
        <wsdl:part name="part1" element="ns:elem"/>
    </wsdl:message>
    <wsdl:portType name="driverWSDLPortType">
        <wsdl:operation name="driverWSDLOperation">
            <wsdl:input name="input1" message="tns:driverWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:driverWSDLOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="driverWSDLBinding" type="tns:driverWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="driverWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/driverWSDL"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/driverWSDL"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="driverWSDLService">
        <wsdl:port name="driverWSDLPort" binding="tns:driverWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/driverWSDLService/driverWSDLPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="driverWSDLPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="driverWSDLPortTypeRole" portType="tns:driverWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
