<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableMixSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableMixRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableMixResponse">
    <part name="CreateTableMixResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateTableMixRequest">
    <part name="CreateTableMixRequestPart" element="tns:CreateTableMixRequest"/>
  </message>
  <portType name="CreateTableMixSql_sqlsePortType">
    <operation name="CreateTableMix">
      <input name="CreateTableMixRequest" message="tns:CreateTableMixRequest"/>
      <output name="CreateTableMixResponse" message="tns:CreateTableMixResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableMixSqlBinding" type="tns:CreateTableMixSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableMix">
      <soap:operation/>
      <input name="CreateTableMixRequest">
        <soap:body/>
      </input>
      <output name="CreateTableMixResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableMixSql_sqlseService">
    <port name="CreateTableMixSql_sqlsePort" binding="tns:CreateTableMixSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableMixSql/CreateTableMixSql/CreateTableMixSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableMixSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableMixSql_myrole" portType="tns:CreateTableMixSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
