<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DynamicContent1Way" targetNamespace="http://j2ee.netbeans.org/wsdl/DynamicContent1Way"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/DynamicContent1Way" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="DynamicContent1WayOperationRequest">
        <part name="input" type="xsd:string"/>
    </message>
    <message name="DynamicContent1WayOperationResponse">
        <part name="output" type="xsd:string"/>
    </message>
    <portType name="DynamicContent1WayPortType">
        <operation name="DynamicContent1WayOperation">
            <input name="input1" message="tns:DynamicContent1WayOperationRequest"/>
            <output name="output1" message="tns:DynamicContent1WayOperationResponse"/>
        </operation>
    </portType>
    <binding name="DynamicContent1WayBinding" type="tns:DynamicContent1WayPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="DynamicContent1WayOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/DynamicContent1Way"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/DynamicContent1Way"/>
            </output>
        </operation>
    </binding>
    <service name="DynamicContent1WayService">
        <port name="DynamicContent1WayPort" binding="tns:DynamicContent1WayBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/DynamicContent1WayService/DynamicContent1WayPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="DynamicContent1WayPlink">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="DynamicContent1WayPortTypeRole" portType="tns:DynamicContent1WayPortType"/>
    </plnk:partnerLinkType>
</definitions>
