package it.imolinfo.jbi4corba.test.webservice.generator.complexintType;


/**
* it/imolinfo/jbi4corba/test/webservice/generator/complexintType/Echo2Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test-IntType-Complex-multInterface.idl
* lunedì 19 gennaio 2009 9.37.07 CET
*/

public interface Echo2Operations 
{
  it.imolinfo.jbi4corba.test.webservice.generator.complexintType.Echo echo (it.imolinfo.jbi4corba.test.webservice.generator.complexintType.EchoStruct msg);
} // interface Echo2Operations
