<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableSpecCharsSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableSpecCharsRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableSpecCharsResponse">
    <part name="CreateTableSpecCharsResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateTableSpecCharsRequest">
    <part name="CreateTableSpecCharsRequestPart" element="tns:CreateTableSpecCharsRequest"/>
  </message>
  <portType name="CreateTableSpecCharsSql_sqlsePortType">
    <operation name="CreateTableSpecChars">
      <input name="CreateTableSpecCharsRequest" message="tns:CreateTableSpecCharsRequest"/>
      <output name="CreateTableSpecCharsResponse" message="tns:CreateTableSpecCharsResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableSpecCharsSqlBinding" type="tns:CreateTableSpecCharsSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableSpecChars">
      <soap:operation/>
      <input name="CreateTableSpecCharsRequest">
        <soap:body/>
      </input>
      <output name="CreateTableSpecCharsResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableSpecCharsSql_sqlseService">
    <port name="CreateTableSpecCharsSql_sqlsePort" binding="tns:CreateTableSpecCharsSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableSpecCharsSql/CreateTableSpecCharsSql/CreateTableSpecCharsSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableSpecCharsSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableSpecCharsSql_myrole" portType="tns:CreateTableSpecCharsSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
