<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectAllFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectAllFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectAllFullQualResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectAllFullQualResponse">
    <part name="SelectAllFullQualResponsePart" element="tns:SelectAllFullQualResponse"/>
  </message>
  <message name="SelectAllFullQualRequest">
    <part name="SelectAllFullQualRequestPart" element="tns:SelectAllFullQualRequest"/>
  </message>
  <portType name="SelectAllFullQualSql_sqlsePortType">
    <operation name="SelectAllFullQual">
      <input name="SelectAllFullQualRequest" message="tns:SelectAllFullQualRequest"/>
      <output name="SelectAllFullQualResponse" message="tns:SelectAllFullQualResponse"/>
    </operation>
  </portType>
  <binding name="SelectAllFullQualSqlBinding" type="tns:SelectAllFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectAllFullQual">
      <soap:operation/>
      <input name="SelectAllFullQualRequest">
        <soap:body/>
      </input>
      <output name="SelectAllFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectAllFullQualSql_sqlseService">
    <port name="SelectAllFullQualSql_sqlsePort" binding="tns:SelectAllFullQualSqlBinding">
      <soap:address location="http://localhost:18181/SelectAllFullQualSql/SelectAllFullQualSql/SelectAllFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectAllFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectAllFullQualSql_myrole" portType="tns:SelectAllFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
