<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/subBPWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/subBPWSDL" name="subBPWSDL" xmlns:ns="http://xml.netbeans.org/schema/dataTypes.xsd" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/">
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/subBPWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/dataTypes.xsd" schemaLocation="../dataTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="subBPWSDLOperationRequest">
        <wsdl:part name="part1" element="ns:helloObj"/>
    </wsdl:message>
    <wsdl:message name="subBPWSDLOperationReply">
        <wsdl:part name="part1" element="ns:helloObj"/>
    </wsdl:message>
    <wsdl:portType name="subBPWSDLPortType">
        <wsdl:operation name="subBPWSDLOperation">
            <wsdl:input name="input1" message="tns:subBPWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:subBPWSDLOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="subBPWSDLBinding" type="tns:subBPWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="subBPWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="subBPWSDLService">
        <wsdl:port name="subBPWSDLPort" binding="tns:subBPWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/subBPWSDLService/subBPWSDLPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="subBPWSDLPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="subBPWSDLPortTypeRole" portType="tns:subBPWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
