<?xml version="1.0" encoding="utf-8" ?>
<definitions targetNamespace="http://stc.com/FaultTest/MatchingCatches3_Messages" 
	name="FaultTest_Messages" 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"	
	xmlns:tns="http://stc.com/FaultTest/MatchingCatches3_Messages">
    <message name="FaultTest">
        <part name="part" type="xsd:string"/>
    </message>    
</definitions>
