<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectMultiParamSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectMultiParamRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectMultiParamResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectMultiParamRequest">
    <part name="SelectMultiParamRequestPart" element="tns:SelectMultiParamRequest"/>
  </message>
  <message name="SelectMultiParamResponse">
    <part name="SelectMultiParamResponsePart" element="tns:SelectMultiParamResponse"/>
  </message>
  <portType name="SelectMultiParamSql_sqlsePortType">
    <operation name="SelectMultiParam">
      <input name="SelectMultiParamRequest" message="tns:SelectMultiParamRequest"/>
      <output name="SelectMultiParamResponse" message="tns:SelectMultiParamResponse"/>
    </operation>
  </portType>
  <binding name="SelectMultiParamSqlBinding" type="tns:SelectMultiParamSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectMultiParam">
      <soap:operation/>
      <input name="SelectMultiParamRequest">
        <soap:body/>
      </input>
      <output name="SelectMultiParamResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectMultiParamSql_sqlseService">
    <port name="SelectMultiParamSql_sqlsePort" binding="tns:SelectMultiParamSqlBinding">
      <soap:address location="http://localhost:18181/SelectMultiParamSql/SelectMultiParamSql/SelectMultiParamSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectMultiParamSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectMultiParamSql_myrole" portType="tns:SelectMultiParamSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
