<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/SMTPOneWayTrigger"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/SMTPOneWayTrigger" name="SMTPOneWayTrigger" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" xmlns:smtp="http://schemas.sun.com/jbi/wsdl-extensions/smtp/">
    <wsdl:types/>
    <wsdl:message name="SMTPOneWayTriggerOperationRequest">
        <wsdl:part name="part1" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="SMTPOneWayTriggerPortType">
        <wsdl:operation name="SMTPOneWayTriggerOperation">
            <wsdl:input name="input1" message="tns:SMTPOneWayTriggerOperationRequest"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SMTPOneWayTriggerBinding" type="tns:SMTPOneWayTriggerPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SMTPOneWayTriggerOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SMTPOneWayTrigger"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SMTPOneWayTriggerService">
        <wsdl:port name="SMTPOneWayTriggerPort" binding="tns:SMTPOneWayTriggerBinding">
            <soap:address location="http://localhost:18181/SMTPOneWayTriggerService/SMTPOneWayTriggerPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="SMTPOneWayTriggerPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SMTPOneWayTriggerPortTypeRole" portType="tns:SMTPOneWayTriggerPortType"/>
    </plnk:partnerLinkType>
</definitions>
