<?xml version="1.0" encoding="UTF-8"?>
<definitions name="selectwrongtabSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="selectwrongtabnameRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="selectwrongtabnameResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="selectwrongtabnameResponse">
    <part name="selectwrongtabnameResponsePart" element="tns:selectwrongtabnameResponse"/>
  </message>
  <message name="selectwrongtabnameRequest">
    <part name="selectwrongtabnameRequestPart" element="tns:selectwrongtabnameRequest"/>
  </message>
  <portType name="selectwrongtabSQL_sqlsePortType">
    <operation name="selectwrongtabname">
      <input name="selectwrongtabnameRequest" message="tns:selectwrongtabnameRequest"/>
      <output name="selectwrongtabnameResponse" message="tns:selectwrongtabnameResponse"/>
    </operation>
  </portType>
  <binding name="selectwrongtabSQLBinding" type="tns:selectwrongtabSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="selectwrongtabname">
      <soap:operation style="document"/>
      <input name="selectwrongtabnameRequest">
        <soap:body use="literal"/>
      </input>
      <output name="selectwrongtabnameResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="selectwrongtabSQL_sqlseService">
    <port name="selectwrongtabSQL_sqlsePort" binding="tns:selectwrongtabSQLBinding">
      <soap:address location="http://localhost:18181/selectwrongtabSQL/selectwrongtabSQL/selectwrongtabSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="selectwrongtabSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="selectwrongtabSQL_myrole" portType="tns:selectwrongtabSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
