<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://flightJourney.demo.sun.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://flightJourney.demo.sun.com/" name="FlightJourneyEJBService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://flightJourney.demo.sun.com/" schemaLocation="FlightJourney.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </xsd:schema>
  </types>
  <message name="getFlightJourney">
    <part name="parameters" element="tns:getFlightJourney"/>
  </message>
  <message name="getFlightJourneyResponse">
    <part name="parameters" element="tns:getFlightJourneyResponse"/>
  </message>
  <portType name="FlightJourneyEJB">
    <operation name="getFlightJourney">
      <input message="tns:getFlightJourney"/>
      <output message="tns:getFlightJourneyResponse"/>
    </operation>
  </portType>
  <binding name="FlightJourneyEJBPortBinding" type="tns:FlightJourneyEJB">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="getFlightJourney">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="FlightJourneyEJBService">
    <port name="FlightJourneyEJBPort" binding="tns:FlightJourneyEJBPortBinding">
      <soap:address location="REPLACE_WITH_ACTUAL_URL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </port>
  </service>
</definitions>
