<?xml version="1.0" encoding="UTF-8"?>
<definitions name="deletefalsecondSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="deletefalsecondRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="deletefalsecondResponse">
    <part name="deletefalsecondResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="deletefalsecondRequest">
    <part name="deletefalsecondRequestPart" element="tns:deletefalsecondRequest"/>
  </message>
  <portType name="deletefalsecondSQL_sqlsePortType">
    <operation name="deletefalsecond">
      <input name="deletefalsecondRequest" message="tns:deletefalsecondRequest"/>
      <output name="deletefalsecondResponse" message="tns:deletefalsecondResponse"/>
    </operation>
  </portType>
  <binding name="deletefalsecondSQLBinding" type="tns:deletefalsecondSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="deletefalsecond">
      <soap:operation style="document"/>
      <input name="deletefalsecondRequest">
        <soap:body use="literal"/>
      </input>
      <output name="deletefalsecondResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="deletefalsecondSQL_sqlseService">
    <port name="deletefalsecondSQL_sqlsePort" binding="tns:deletefalsecondSQLBinding">
      <soap:address location="http://localhost:18181/deletefalsecondSQL/deletefalsecondSQL/deletefalsecondSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="deletefalsecondSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="deletefalsecondSQL_myrole" portType="tns:deletefalsecondSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
