<definitions targetNamespace="http://stc.com/current-dateTime" name="current-dateTime" xmlns:tns="http://stc.com/current-dateTime" xmlns:slnk1="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns0="http://stc.com/current-dateTime" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/">
	<types>
		<xsd:schema targetNamespace="http://stc.com/current-dateTime" elementFormDefault="qualified" xmlns:tns="http://stc.com/current-dateTime" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/">
			<xsd:element name="item">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element type="xsd:string" name="value"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</types>
	<message name="current-dateTime">
		<part name="part" element="tns:item"/>
	</message>
	<portType name="current-dateTime">
		<operation name="current-dateTime">
			<input message="tns:current-dateTime"/>
			<output message="tns:current-dateTime"/>
		</operation>
	</portType>
	<binding name="Binding" type="tns:current-dateTime">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="current-dateTime">
			<soap:operation soapAction="current-dateTime"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="current-dateTimeService">
		<port name="port" binding="tns:Binding">
			<soap:address location="http://localhost:${HttpDefaultPort}/current-dateTime"/>
		</port>
	</service>
	<plnk:partnerLinkType name="SLT" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
		<plnk:role name="server" portType="tns:current-dateTime"/>
	</plnk:partnerLinkType>
</definitions>
