<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FaultTestWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/FaultTestWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/FaultTestWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://faulttest.webservice.namespace">
    <import location="FaultTest.wsdl" namespace="http://faulttest.webservice.namespace"/>
    <plnk:partnerLinkType name="partnerLinkType2">
        <plnk:role name="Msg2Role" portType="ns:MultiOpSameMsg2ElemElemIF"/>
    </plnk:partnerLinkType>
</definitions>
