<?xml version="1.0" encoding="UTF-8"?>
<definitions name="proxy" targetNamespace="http://j2ee.netbeans.org/wsdl/proxy"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/proxy" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
    <types/>
    <message name="proxyOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="proxyOperationResponse">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="proxyPortType">
        <operation name="proxyOperation">
            <input name="input1" message="tns:proxyOperationRequest"/>
            <output name="output1" message="tns:proxyOperationResponse"/>
        </operation>
    </portType>
    <binding name="proxyBinding" type="tns:proxyPortType">
        <soap12:binding style="rpc" transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <operation name="proxyOperation">
            <soap12:operation/>
            <input name="input1">
                <soap12:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/proxy"/>
            </input>
            <output name="output1">
                <soap12:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/proxy"/>
            </output>
        </operation>
    </binding>
    <service name="proxyService">
        <port name="proxyPort" binding="tns:proxyBinding">
            <soap12:address location="http://localhost:${HttpDefaultPort}/proxyService/proxyPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="proxy">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="proxyPortTypeRole" portType="tns:proxyPortType"/>
    </plnk:partnerLinkType>
</definitions>
