<definitions name="FILE_LOCAL_READ_WRITE" targetNamespace="http://j2ee.netbeans.org/wsdl/OnDemandGet/FILE_LOCAL_READ_WRITE"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/" xmlns:tns="http://j2ee.netbeans.org/wsdl/OnDemandGet/FILE_LOCAL_READ_WRITE" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="PollInputMessage">
        <part name="part1" type="xsd:string"/>
    </message> 
    <message name="PollOutputMessage">
        <part name="part1" type="xsd:string"/>
    </message>     
    <portType name="FileInboundPortType">
        <operation name="poll">
            <input name="input1" message="tns:PollInputMessage"/>
            <output name="output1" message="tns:PollOutputMessage"/>
        </operation>
    </portType>
    <binding name="FileInboundBinding" type="tns:FileInboundPortType">
        <file:binding/>
        <operation name="poll">
            <file:operation verb="poll"/>
            <input name="input1">
                <file:message fileName="input%d.txt" pollingInterval="1000" use="literal" fileNameIsPattern="true" part="part1" archive="true" archiveDirIsRelative="false"/>
            </input>
            <output name="output1">
                <file:message fileName="reply%d.txt" use="literal" fileNameIsPattern="true" part="part1" />
            </output>
        </operation>
    </binding>
    <service name="FileInboundService">
        <port name="FILE_LOCAL_READ_WRITE_InboundPort" binding="tns:FileInboundBinding">
            <file:address fileDirectory="${ojc-root}/driver-tests/ftpbc/FTPBCTests/OnDemandGetCompApp/test/OnDemandGetTest/in_out"/>
        </port>
    </service>
    <plnk:partnerLinkType name="FILE_LOCAL_READ_WRITE">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="FileInboundPortTypeRole" portType="tns:FileInboundPortType"/>
    </plnk:partnerLinkType>
</definitions>
