<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="EchoLazyLookupCorbaloc" targetNamespace="urn:jbi4corba/test-provider-lazy-lookup" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:imolacorba="uri://schemas.imola.it/jbi/wsdl-extensions/corba/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:jbi4corba/test-provider-lazy-lookup" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
   <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:jbi4corba/test-provider-lazy-lookup" xmlns="urn:jbi4corba/test-provider-lazy-lookup" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="echo">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="msg" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="echoResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="return" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
   </wsdl:types>
  <wsdl:message name="echo">
    <wsdl:part name="parameters" element="tns:echo">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="echoResponse">
    <wsdl:part name="parameters" element="tns:echoResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="EchoLazyLookupCorbaloc">
    <wsdl:operation name="echo">
      <wsdl:input name="echo" message="tns:echo">
    </wsdl:input>
      <wsdl:output name="echoResponse" message="tns:echoResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EchoLazyLookupCorbalocCorbaBinding" type="tns:EchoLazyLookupCorbaloc">
<imolacorba:binding>
<imolacorba:idl>
//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module testproviderlazylookup{
					
//						interface InterfaceEchoLazyLookupNs {
//							string echo(in string msg);
//						};
//
						interface InterfaceEchoLazyLookupCorbaloc {
							string echo(in string msg);
						};
//
//						interface InterfaceEchoLazyLookupCorbaname {
//							string echo(in string msg);
//						};
//
//						interface InterfaceEchoLazyLookupIOR {
//							string echo(in string msg);
//						};
					
				};
			};
		};
	};
};
</imolacorba:idl>
</imolacorba:binding>
    <wsdl:operation name="echo">
      <wsdl:input name="echo">
      </wsdl:input>
      <wsdl:output name="echoResponse">
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EchoLazyLookupCorbaloc">
    <wsdl:port name="EchoLazyLookupCorbalocCorbaPort" binding="tns:EchoLazyLookupCorbalocCorbaBinding">
<imolacorba:address name="corbaloc:iiop:1.2@127.0.0.1:1061/EchoLazyLookupCorbaloc" localizationType="corbaloc">
<imolacorba:orb>
<imolacorba:property name="org.omg.CORBA.ORBInitialPort" value="1050"/>
<imolacorba:property name="org.omg.CORBA.ORBClass" value="com.sun.corba.ee.impl.orb.ORBImpl"/>
<imolacorba:property name="org.omg.CORBA.ORBInitialHost" value="localhost"/>
</imolacorba:orb>
</imolacorba:address>
    </wsdl:port>
  </wsdl:service>
<plnk:partnerLinkType name="EchoLazyLookupCorbaloc">
<plnk:role name="EchoLazyLookupCorbalocPortTypeRole" portType="tns:EchoLazyLookupCorbaloc"/>
</plnk:partnerLinkType>
</wsdl:definitions>
