CREATE TABLESPACE "HL7BC_SCHEMA_DB" DATAFILE 'HL7BC_SCHEMA_DB1.dat' SIZE 512M, 'HL7BC_SCHEMA_DB2.dat' SIZE 512M;
CREATE USER HL7BC_SCHEMA IDENTIFIED BY HL7BC_SCHEMA DEFAULT TABLESPACE HL7BC_SCHEMA_DB QUOTA UNLIMITED ON HL7BC_SCHEMA_DB TEMPORARY TABLESPACE temp QUOTA 0M ON system;
GRANT CREATE session to HL7BC_SCHEMA;
GRANT CREATE table to HL7BC_SCHEMA;
GRANT CREATE procedure to HL7BC_SCHEMA;
CREATE TABLE HL7BC_SCHEMA.EXPSEQUENCENO (ID VARCHAR(1000), ESN INTEGER, ESNSTATE VARCHAR(2), primary key (ID));
CREATE TABLE HL7BC_SCHEMA.HL7MESSAGELOG (MESSAGEID VARCHAR(250), APPLICATIONID VARCHAR(250) , REQUESTMESSAGE CLOB, RESPONSEMESSAGE CLOB, STATUS SMALLINT, CREATEDTIME TIMESTAMP, LASTUPDATEDTIME TIMESTAMP);
CREATE TABLE HL7BC_SCHEMA.JOURNALHL7MESSAGELOG (APPLICATIONID VARCHAR(500), MESSAGECONTROLID VARCHAR(250), PROCESSMODE VARCHAR(10), REQUESTHL7MESSAGE CLOB, RESPONSEACKMESSAGE CLOB, RESPONSENAKMESSAGE CLOB, STATUS VARCHAR(200));  