DROP TABLE HL7BC_SCHEMA.EXPSEQUENCENO;
DROP TABLE HL7BC_SCHEMA.HL7MESSAGELOG;
DROP TABLE HL7BC_SCHEMA.JOURNALHL7MESSAGELOG;
DROP SCHEMA HL7BC_SCHEMA RESTRICT;
DROP USER HL7BC_SCHEMA CASCADE;
DROP TABLESPACE HL7BC_SCHEMA_DB INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;