//idl
module it{
module imolinfo{
module jbi4corba{
		
		// struct
  		struct ComplexStruct {
    		boolean            fieldBoolean;
    		char               fieldChar;
    		wchar              fieldWChar;
                wstring            fieldWString;
    		short              fieldShort;
    		unsigned short     fieldUnsignedShort;
    		long               fieldLong;
    		unsigned long      fieldUnsignedLong;
    		long long          fieldLongLong;
    		unsigned long long fieldUnsignedLongLong;
    		float              fieldFloat;
    		double             fieldDouble;

    		
  		};	

	      };
	};
};