//IDL
module it{
module imolinfo{
module jbi4corba{
module test{
module webservice{
module generator{
	
	#include "include1.idl"
	#include "include2.idl"
	#include "imola/include1.idl"

	enum EchoComplexEnum {E1, E2, E3};

	interface foo {

		EchoComplexEnum echoEnum(in EchoComplexEnum e);

	};
};
};
};
};
};
};