<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/SOAPFindOraTrigger"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SOAPFindOraTrigger" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://j2ee.netbeans.org/wsdl/SOAPFindOraTrigger" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/SOAPFindOraTrigger">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="TestTable.xsd"/>
        </xsd:schema>
    </types>
    <message name="SOAPFindOraTriggerOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="SOAPFindOraTriggerOperationReply">
        <part name="part1" element="ns:TestTable"/>
    </message>
    <portType name="SOAPFindOraTriggerPortType">
        <wsdl:operation name="SOAPFindOraTriggerOperation">
            <wsdl:input name="input1" message="tns:SOAPFindOraTriggerOperationRequest"/>
            <wsdl:output name="output1" message="tns:SOAPFindOraTriggerOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="SOAPFindOraTriggerBinding" type="tns:SOAPFindOraTriggerPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SOAPFindOraTriggerOperation">
            <soap:operation style="document"/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SOAPFindOraTrigger" parts="part1"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SOAPFindOraTrigger" parts="part1"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="SOAPFindOraTriggerService">
        <wsdl:port name="SOAPFindOraTriggerPort" binding="tns:SOAPFindOraTriggerBinding">
            <soap:address location="http://localhost:18181/SOAPFindOraTriggerService/SOAPFindOraTriggerPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="SOAPFindOraTriggerPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SOAPFindOraTriggerPortTypeRole" portType="tns:SOAPFindOraTriggerPortType"/>
    </plnk:partnerLinkType>
</definitions>
