package it.imolinfo.jbi4corba.test.testprovidercrb106.doubleparam;


/**
* it/imolinfo/jbi4corba/test/testprovidercrb106/doubleparam/InterfaceDoubleParamOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/EchoCrb106Single.idl
* giovedì 22 novembre 2007 16.36.59 CET
*/


//==================================================
public interface InterfaceDoubleParamOperations 
{
  it.imolinfo.jbi4corba.test.testprovidercrb106.StructAB methodA (it.imolinfo.jbi4corba.test.testprovidercrb106.ValueTypeA a, it.imolinfo.jbi4corba.test.testprovidercrb106.ValueTypeB b);
  it.imolinfo.jbi4corba.test.testprovidercrb106.StructAB methodB (it.imolinfo.jbi4corba.test.testprovidercrb106.ValueTypeA a, it.imolinfo.jbi4corba.test.testprovidercrb106.ValueTypeB b);
} // interface InterfaceDoubleParamOperations
