<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InsertWrongValSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="InsertWrongValRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="InsertWrongValResponse">
    <part name="InsertWrongValResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="InsertWrongValRequest">
    <part name="InsertWrongValRequestPart" element="tns:InsertWrongValRequest"/>
  </message>
  <portType name="InsertWrongValSql_sqlsePortType">
    <operation name="InsertWrongVal">
      <input name="InsertWrongValRequest" message="tns:InsertWrongValRequest"/>
      <output name="InsertWrongValResponse" message="tns:InsertWrongValResponse"/>
    </operation>
  </portType>
  <binding name="InsertWrongValSqlBinding" type="tns:InsertWrongValSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="InsertWrongVal">
      <soap:operation/>
      <input name="InsertWrongValRequest">
        <soap:body/>
      </input>
      <output name="InsertWrongValResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="InsertWrongValSql_sqlseService">
    <port name="InsertWrongValSql_sqlsePort" binding="tns:InsertWrongValSqlBinding">
      <soap:address location="http://localhost:18181/InsertWrongValSql/InsertWrongValSql/InsertWrongValSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="InsertWrongValSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="InsertWrongValSql_myrole" portType="tns:InsertWrongValSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
