<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Z_IDOCINBOUNDASYNC.EUCWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/Z_IDOCINBOUNDASYNC.EUCWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/Z_IDOCINBOUNDASYNC.EUCWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="urn:sap-com:document:sap:soap:functions:mc-style">
    <import location="../Z_IDOCINBOUNDASYNC.EUC.wsdl" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
    <plnk:partnerLinkType name="Z_IDOCINBOUNDASYNCLinkType">
        <plnk:role name="Z_IDOCINBOUNDASYNCRole" portType="ns:Z_IDOCINBOUNDASYNC"/>
    </plnk:partnerLinkType>
</definitions>
