<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWithXParNameViewFullSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWithXParNameViewFullRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWithXParNameViewFullResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWithXParNameViewFullResponse">
    <part name="SelectWithXParNameViewFullResponsePart" element="tns:SelectWithXParNameViewFullResponse"/>
  </message>
  <message name="SelectWithXParNameViewFullRequest">
    <part name="SelectWithXParNameViewFullRequestPart" element="tns:SelectWithXParNameViewFullRequest"/>
  </message>
  <portType name="SelectWithXParNameViewFullSql_sqlsePortType">
    <operation name="SelectWithXParNameViewFull">
      <input name="SelectWithXParNameViewFullRequest" message="tns:SelectWithXParNameViewFullRequest"/>
      <output name="SelectWithXParNameViewFullResponse" message="tns:SelectWithXParNameViewFullResponse"/>
    </operation>
  </portType>
  <binding name="SelectWithXParNameViewFullSqlBinding" type="tns:SelectWithXParNameViewFullSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWithXParNameViewFull">
      <soap:operation/>
      <input name="SelectWithXParNameViewFullRequest">
        <soap:body/>
      </input>
      <output name="SelectWithXParNameViewFullResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWithXParNameViewFullSql_sqlseService">
    <port name="SelectWithXParNameViewFullSql_sqlsePort" binding="tns:SelectWithXParNameViewFullSqlBinding">
      <soap:address location="http://localhost:18181/SelectWithXParNameViewFullSql/SelectWithXParNameViewFullSql/SelectWithXParNameViewFullSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWithXParNameViewFullSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWithXParNameViewFullSql_myrole" portType="tns:SelectWithXParNameViewFullSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
