<?xml version="1.0" encoding="UTF-8"?>
<definitions name="XslPartAsType" targetNamespace="http://j2ee.netbeans.org/wsdl/XslPartAsType"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/XslPartAsType" xmlns:ns="http://sun.com/EmplInput" xmlns:ns0="http://sun.com/EmplOutput" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/XslPartAsType">
            <xsd:import namespace="http://sun.com/EmplInput" schemaLocation="EmployeeInput.xsd"/>
            <xsd:import namespace="http://sun.com/EmplOutput" schemaLocation="EmployeeOutput.xsd"/>
        </xsd:schema>
    </types>
    <message name="XslPartAsTypeOperationRequest">
        <part name="part1" type="ns:emplInput"/>
    </message>
    <message name="XslPartAsTypeOperationReply">
        <part name="part1" type="ns0:emplOutput"/>
    </message>
    <portType name="XslPartAsTypePortType">
        <wsdl:operation name="XslPartAsTypeOperation">
            <wsdl:input name="input1" message="tns:XslPartAsTypeOperationRequest"/>
            <wsdl:output name="output1" message="tns:XslPartAsTypeOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="XslPartAsTypeBinding" type="tns:XslPartAsTypePortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="XslPartAsTypeOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/XslPartAsType"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/XslPartAsType"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="XslPartAsTypeService">
        <wsdl:port name="XslPartAsTypePort" binding="tns:XslPartAsTypeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/XslPartAsTypeService/XslPartAsTypePort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="XslPartAsType1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="XslPartAsTypePortTypeRole" portType="tns:XslPartAsTypePortType"/>
    </plnk:partnerLinkType>
</definitions>
