<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableNumColSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableNumColRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableNumColResponse">
    <part name="CreateTableNumColResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateTableNumColRequest">
    <part name="CreateTableNumColRequestPart" element="tns:CreateTableNumColRequest"/>
  </message>
  <portType name="CreateTableNumColSql_sqlsePortType">
    <operation name="CreateTableNumCol">
      <input name="CreateTableNumColRequest" message="tns:CreateTableNumColRequest"/>
      <output name="CreateTableNumColResponse" message="tns:CreateTableNumColResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableNumColSqlBinding" type="tns:CreateTableNumColSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableNumCol">
      <soap:operation/>
      <input name="CreateTableNumColRequest">
        <soap:body/>
      </input>
      <output name="CreateTableNumColResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableNumColSql_sqlseService">
    <port name="CreateTableNumColSql_sqlsePort" binding="tns:CreateTableNumColSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableNumColSql/CreateTableNumColSql/CreateTableNumColSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableNumColSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableNumColSql_myrole" portType="tns:CreateTableNumColSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
