<?xml version="1.0" encoding="UTF-8"?>
<definitions name="joinswrongquerySQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="joinswrongqueryRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="joinswrongqueryResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="joinswrongqueryRequest">
    <part name="joinswrongqueryRequestPart" element="tns:joinswrongqueryRequest"/>
  </message>
  <message name="joinswrongqueryResponse">
    <part name="joinswrongqueryResponsePart" element="tns:joinswrongqueryResponse"/>
  </message>
  <portType name="joinswrongquerySQL_sqlsePortType">
    <operation name="joinswrongquery">
      <input name="joinswrongqueryRequest" message="tns:joinswrongqueryRequest"/>
      <output name="joinswrongqueryResponse" message="tns:joinswrongqueryResponse"/>
    </operation>
  </portType>
  <binding name="joinswrongquerySQLBinding" type="tns:joinswrongquerySQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="joinswrongquery">
      <soap:operation style="document"/>
      <input name="joinswrongqueryRequest">
        <soap:body use="literal"/>
      </input>
      <output name="joinswrongqueryResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="joinswrongquerySQL_sqlseService">
    <port name="joinswrongquerySQL_sqlsePort" binding="tns:joinswrongquerySQLBinding">
      <soap:address location="http://localhost:18181/joinswrongquerySQL/joinswrongquerySQL/joinswrongquerySQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="joinswrongquerySQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="joinswrongquerySQL_myrole" portType="tns:joinswrongquerySQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
