<definitions targetNamespace="urn:CorrInvRecW1C6ChildTargetNamespace"
             name="CorrInvRecW1C6ChildDefinition"
             xmlns:bpws="http://schemas.xmlsoap.org/ws/2004/03/business-process/"
             xmlns:tns="urn:CorrInvRecW1C6ChildTargetNamespace"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:slnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/">
    <plnk:partnerLinkType name="CorrInvRecW1C6ChildServiceLinkType"
                          xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/">
        <plnk:role name="CorrInvRecW1C6ChildServerRole"
                   portType="tns:CorrInvRecW1C6ChildPortType"></plnk:role>
    </plnk:partnerLinkType>
    <bpws:property type="xsd:string"
                   name="CorrInvRecW1C6ChildProp"></bpws:property>
    <bpws:propertyAlias part="CorrInvRecW1C6ChildPart"
                        propertyName="tns:CorrInvRecW1C6ChildProp"
                        messageType="tns:CorrInvRecW1C6ChildMessage">
        <bpws:query>string</bpws:query>
    </bpws:propertyAlias>
    <types>
        <xsd:schema targetNamespace="urn:CorrInvRecW1C6ChildTargetNamespace"
                    attributeFormDefault="unqualified"
                    elementFormDefault="qualified"
                    xmlns:tns="urn:CorrInvRecW1C6ChildTargetNamespace"
                    xmlns:ns1="urn:CorrInvRecW1C6ChildTargetNamespace"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    xmlns="http://schemas.xmlsoap.org/wsdl/"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
            
                    <xsd:complexType name="CorrInvRecW1C6ChildType">
                <xsd:sequence>
                    <xsd:element type="xsd:string"
                                 name="string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="CorrInvRecW1C6ChildMessage">
        <part name="CorrInvRecW1C6ChildPart"
              type="tns:CorrInvRecW1C6ChildType"></part>
    </message>
    <portType name="CorrInvRecW1C6ChildPortType">
        <operation name="CorrInvRecW1C6ChildOperation">
            <input message="tns:CorrInvRecW1C6ChildMessage"></input>
            <output message="tns:CorrInvRecW1C6ChildMessage"></output>
        </operation>
    </portType>
    <binding name="CorrInvRecW1C6ChildBinding"
             type="tns:CorrInvRecW1C6ChildPortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CorrInvRecW1C6ChildOperation">
            <soap:operation soapAction="CorrInvRecW1C6ChildOperation"/>
            <input>
                <soap:body parts="CorrInvRecW1C6ChildPart"
                           use="literal"/>
            </input>
            <output>
                <soap:body parts="CorrInvRecW1C6ChildPart"
                           use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="CorrInvRecW1C6ChildService">
        <port name="CorrInvRecW1C6ChildPort"
              binding="tns:CorrInvRecW1C6ChildBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/service/CorrInvRecW1C6Child"/>
        </port>
    </service>
</definitions>