<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns="urn:singlePartnerLinkTargetNamespace">
    <import namespace="urn:singlePartnerLinkTargetNamespace" location="singlePartnerLink.wsdl"/>
    <vprop:property name="wzrd_prop_id_id" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_id_id" messageType="ns:singlePartnerLinkMessage" part="singlePartnerLinkPart"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_id_id" messageType="ns:singlePartnerLinkMessage1" part="singlePartnerLinkPart1"/>
</definitions>
