//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.10 at 01:36:48 PM IST 
//
package com.sun.jbi.engine.scriptse.scrconfig;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.</p>
 *  <p>The following schema fragment specifies the expected content contained within this
 * class.<pre>&lt;complexType>  &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">      &lt;sequence>
 *         &lt;element ref="{}parameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}returntype" minOccurs="0"/>      &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wsdlop" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>  &lt;/complexContent>&lt;/complexType></pre></p>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =  {
    "parameter", "returntype"}
)
@XmlRootElement(name = "operation")
public class Operation {
    /**
     * DOCUMENT ME!
     */
    protected List<Parameter> parameter;

    /**
     * DOCUMENT ME!
     */
    protected Returntype returntype;

    /**
     * DOCUMENT ME!
     */
    @XmlAttribute(required = true)
    protected String name;

    /**
     * DOCUMENT ME!
     */
    @XmlAttribute(required = true)
    protected String wsdlop;

    /**
     * Gets the value of the parameter property.<p>This accessor method returns a reference
     * to the live list, not a snapshot. Therefore any modification you make to the returned list
     * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the parameter property.</p>
     *  <p>For example, to add a new item, do as follows:<pre>   getParameter().add(newItem);</pre></p>
     *  <p>Objects of the following type(s) are allowed in the list {@link Parameter }</p>
     *
     * @return DOCUMENT ME!
     */
    public List<Parameter> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<Parameter>();
        }

        return this.parameter;
    }

    /**
     * Gets the value of the returntype property.
     *
     * @return possible object is {@link Returntype }
     */
    public Returntype getReturntype() {
        return returntype;
    }

    /**
     * Sets the value of the returntype property.
     *
     * @param value allowed object is {@link Returntype }
     */
    public void setReturntype(Returntype value) {
        this.returntype = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the wsdlop property.
     *
     * @return possible object is {@link String }
     */
    public String getWsdlop() {
        return wsdlop;
    }

    /**
     * Sets the value of the wsdlop property.
     *
     * @param value allowed object is {@link String }
     */
    public void setWsdlop(String value) {
        this.wsdlop = value;
    }
}
