//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.10 at 01:36:48 PM IST 
//
package com.sun.jbi.engine.scriptse.scrconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.</p>
 *  <p>The following schema fragment specifies the expected content contained within this
 * class.<pre>&lt;complexType>  &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">      &lt;sequence>
 *         &lt;element name="ScrEngineDetails">          &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>                  &lt;element ref="{}enginename"/>
 *                   &lt;element ref="{}extension" minOccurs="0"/>
 *                   &lt;element ref="{}version" minOccurs="0"/>
 *                   &lt;element ref="{}mimetype" minOccurs="0"/>                &lt;/sequence>
 *               &lt;/restriction>            &lt;/complexContent>          &lt;/complexType>
 *         &lt;/element>        &lt;element ref="{}operations"/>        &lt;choice>
 *           &lt;element ref="{}requestReplyService" minOccurs="0"/>
 *           &lt;element ref="{}filterOneWay" minOccurs="0"/>        &lt;/choice>
 *       &lt;/sequence>    &lt;/restriction>  &lt;/complexContent>&lt;/complexType></pre></p>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "", propOrder =  {
        "scrEngineDetails", "operations", "requestReplyService", "filterOneWay"}

)
@XmlRootElement(name = "scriptconfig")
public class Scriptconfig {
    /**
     * DOCUMENT ME!
     */
    @XmlElement(name = "ScrEngineDetails", required = true)
    protected Scriptconfig.ScrEngineDetails scrEngineDetails;

    /**
     * DOCUMENT ME!
     */
    @XmlElement(required = true)
    protected Operations operations;

    /**
     * DOCUMENT ME!
     */
    protected RequestReplyService requestReplyService;

    /**
     * DOCUMENT ME!
     */
    protected FilterOneWay filterOneWay;

    /**
     * Gets the value of the scrEngineDetails property.
     *
     * @return possible object is {@link Scriptconfig.ScrEngineDetails }
     */
    public Scriptconfig.ScrEngineDetails getScrEngineDetails() {
        return scrEngineDetails;
    }

    /**
     * Sets the value of the scrEngineDetails property.
     *
     * @param value allowed object is {@link Scriptconfig.ScrEngineDetails }
     */
    public void setScrEngineDetails(Scriptconfig.ScrEngineDetails value) {
        this.scrEngineDetails = value;
    }

    /**
     * Gets the value of the operations property.
     *
     * @return possible object is {@link Operations }
     */
    public Operations getOperations() {
        return operations;
    }

    /**
     * Sets the value of the operations property.
     *
     * @param value allowed object is {@link Operations }
     */
    public void setOperations(Operations value) {
        this.operations = value;
    }

    /**
     * Gets the value of the requestReplyService property.
     *
     * @return possible object is {@link RequestReplyService }
     */
    public RequestReplyService getRequestReplyService() {
        return requestReplyService;
    }

    /**
     * Sets the value of the requestReplyService property.
     *
     * @param value allowed object is {@link RequestReplyService }
     */
    public void setRequestReplyService(RequestReplyService value) {
        this.requestReplyService = value;
    }

    /**
     * Gets the value of the filterOneWay property.
     *
     * @return possible object is {@link FilterOneWay }
     */
    public FilterOneWay getFilterOneWay() {
        return filterOneWay;
    }

    /**
     * Sets the value of the filterOneWay property.
     *
     * @param value allowed object is {@link FilterOneWay }
     */
    public void setFilterOneWay(FilterOneWay value) {
        this.filterOneWay = value;
    }

    /**
     * <p>Java class for anonymous complex type.</p>
     *  <p>The following schema fragment specifies the expected content contained within
     * this class.<pre>&lt;complexType>  &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">      &lt;sequence>
     *         &lt;element ref="{}enginename"/>
     *         &lt;element ref="{}extension" minOccurs="0"/>
     *         &lt;element ref="{}version" minOccurs="0"/>
     *         &lt;element ref="{}mimetype" minOccurs="0"/>      &lt;/sequence>
     *     &lt;/restriction>  &lt;/complexContent>&lt;/complexType></pre></p>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder =  {
        "enginename", "extension", "version", "mimetype"}
    )
    public static class ScrEngineDetails {
        /**
         * DOCUMENT ME!
         */
        @XmlElement(required = true)
        protected String enginename;

        /**
         * DOCUMENT ME!
         */
        protected String extension;

        /**
         * DOCUMENT ME!
         */
        protected String version;

        /**
         * DOCUMENT ME!
         */
        protected String mimetype;

        /**
         * Gets the value of the enginename property.
         *
         * @return possible object is {@link String }
         */
        public String getEnginename() {
            return enginename;
        }

        /**
         * Sets the value of the enginename property.
         *
         * @param value allowed object is {@link String }
         */
        public void setEnginename(String value) {
            this.enginename = value;
        }

        /**
         * Gets the value of the extension property.
         *
         * @return possible object is {@link String }
         */
        public String getExtension() {
            return extension;
        }

        /**
         * Sets the value of the extension property.
         *
         * @param value allowed object is {@link String }
         */
        public void setExtension(String value) {
            this.extension = value;
        }

        /**
         * Gets the value of the version property.
         *
         * @return possible object is {@link String }
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         *
         * @param value allowed object is {@link String }
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the mimetype property.
         *
         * @return possible object is {@link String }
         */
        public String getMimetype() {
            return mimetype;
        }

        /**
         * Sets the value of the mimetype property.
         *
         * @param value allowed object is {@link String }
         */
        public void setMimetype(String value) {
            this.mimetype = value;
        }
    }
}
