<definitions targetNamespace="urn:request-response-initiatejoinChildTargetNamespace"
             name="request-response-initiatejoinChildDefinition"
             xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:tns="urn:request-response-initiatejoinChildTargetNamespace"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:slnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:parentWSDL="request-response-initiatejoinParent">
    <plnk:partnerLinkType name="request-response-initiatejoinChildServiceLinkType"
                          xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plnk:role name="request-response-initiatejoinChildServerRole"
                   portType="tns:request-response-initiatejoinChildPortType"></plnk:role>
    </plnk:partnerLinkType>
    <vprop:propertyAlias part="request-response-initiatejoinChildPart"
                        propertyName="parentWSDL:property"
                        messageType="tns:request-response-initiatejoinChildMessage">
        <vprop:query>string</vprop:query>
    </vprop:propertyAlias>
    <import location="request-response-initiatejoin_parent.wsdl" namespace="request-response-initiatejoinParent"/>
    
    <types>
        <xsd:schema targetNamespace="urn:request-response-initiatejoinChildTargetNamespace"
                    attributeFormDefault="unqualified"
                    elementFormDefault="qualified"
                    xmlns:tns="urn:request-response-initiatejoinChildTargetNamespace"
                    xmlns:ns1="urn:request-response-initiatejoinChildTargetNamespace"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    xmlns="http://schemas.xmlsoap.org/wsdl/"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
            
                    <xsd:complexType name="request-response-initiatejoinChildType">
                <xsd:sequence>
                    <xsd:element type="xsd:string"
                                 name="string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="request-response-initiatejoinChildMessage">
        <part name="request-response-initiatejoinChildPart"
              type="tns:request-response-initiatejoinChildType"></part>
    </message>
    <portType name="request-response-initiatejoinChildPortType">
        <operation name="request-response-initiatejoinChildOperation">
            <input message="tns:request-response-initiatejoinChildMessage"></input>
            <output message="tns:request-response-initiatejoinChildMessage"></output>
        </operation>
    </portType>
    <binding name="request-response-initiatejoinChildBinding"
             type="tns:request-response-initiatejoinChildPortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="request-response-initiatejoinChildOperation">
            <soap:operation soapAction="request-response-initiatejoinChildOperation"/>
            <input>
                <soap:body parts="request-response-initiatejoinChildPart"
                           use="literal"/>
            </input>
            <output>
                <soap:body parts="request-response-initiatejoinChildPart"
                           use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="request-response-initiatejoinChildService">
        <port name="request-response-initiatejoinChildPort"
              binding="tns:request-response-initiatejoinChildBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/service/request-response-initiatejoinChild"/>
        </port>
    </service>
</definitions>
