<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Trigger" targetNamespace="http://j2ee.netbeans.org/wsdl/HttpOutBoundHeaderTest_bpel/Trigger"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/HttpOutBoundHeaderTest_bpel/Trigger" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="TriggerOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="TriggerOperationResponse">
        <part name="part2" type="xsd:string"/>
    </message>
    <portType name="TriggerPortType">
        <operation name="TriggerOperation">
            <input name="input1" message="tns:TriggerOperationRequest"/>
            <output name="output1" message="tns:TriggerOperationResponse"/>
        </operation>
    </portType>
    <binding name="TriggerBinding" type="tns:TriggerPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="TriggerOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/HttpOutBoundHeaderTest_bpel/Trigger"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/HttpOutBoundHeaderTest_bpel/Trigger"/>
            </output>
        </operation>
    </binding>
    <service name="TriggerService">
        <port name="TriggerPort" binding="tns:TriggerBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/TriggerService/TriggerPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="Trigger">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="TriggerPortTypeRole" portType="tns:TriggerPortType"/>
    </plnk:partnerLinkType>
</definitions>
