<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/cache"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/cache" name="cache" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" xmlns:ns1="http://j2ee.netbeans.org/wsdl/helloPartner">
    <import location="helloPartner.wsdl" namespace="http://j2ee.netbeans.org/wsdl/helloPartner"/>
    <types/>
    <portType name="cachePortType">
        <wsdl:operation name="cacheOperation">
            <wsdl:input name="input1" message="ns1:helloPartnerOperationRequest"/>
            <wsdl:output name="output1" message="ns1:helloPartnerOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="cacheBinding" type="tns:cachePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <wsdl:operation name="cacheOperation">
            <soap:operation soapAction="cacheOperation" style="document"/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="cacheService">
        <wsdl:port name="cachePort" binding="tns:cacheBinding">
            <soap:address location="http://localhost:18181/cacheService/cachePort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="cachePartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="cachePortTypeRole" portType="tns:cachePortType"/>
    </plnk:partnerLinkType>
</definitions>
