<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableColNumSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableColNumRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableColNumResponse">
    <part name="CreateTableColNumResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateTableColNumRequest">
    <part name="CreateTableColNumRequestPart" element="tns:CreateTableColNumRequest"/>
  </message>
  <portType name="CreateTableColNumSql_sqlsePortType">
    <operation name="CreateTableColNum">
      <input name="CreateTableColNumRequest" message="tns:CreateTableColNumRequest"/>
      <output name="CreateTableColNumResponse" message="tns:CreateTableColNumResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableColNumSqlBinding" type="tns:CreateTableColNumSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableColNum">
      <soap:operation/>
      <input name="CreateTableColNumRequest">
        <soap:body/>
      </input>
      <output name="CreateTableColNumResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableColNumSql_sqlseService">
    <port name="CreateTableColNumSql_sqlsePort" binding="tns:CreateTableColNumSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableColNumSql/CreateTableColNumSql/CreateTableColNumSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableColNumSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableColNumSql_myrole" portType="tns:CreateTableColNumSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
