<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/throttling"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="throttling" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://j2ee.netbeans.org/wsdl/throttling" xmlns:ns="http://xml.netbeans.org/schema/hello" xmlns:ns0="http://j2ee.netbeans.org/wsdl/helloPartner">
    <import location="helloPartner.wsdl" namespace="http://j2ee.netbeans.org/wsdl/helloPartner"/>
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/throttling">
            <xsd:import namespace="http://xml.netbeans.org/schema/hello" schemaLocation="hello.xsd"/>
        </xsd:schema>
    </types>
    <portType name="throttlingPortType">
        <wsdl:operation name="throttlingOperation">
            <wsdl:input name="input1" message="ns0:helloPartnerOperationRequest"/>
            <wsdl:output name="output1" message="ns0:helloPartnerOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="throttlingBinding" type="tns:throttlingPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="throttlingOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="throttlingService">
        <wsdl:port name="throttlingPort" binding="tns:throttlingBinding">
            <soap:address location="http://localhost:18181/throttlingService/throttlingPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="throttling1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="throttlingPortTypeRole" portType="tns:throttlingPortType"/>
    </plnk:partnerLinkType>
</definitions>
