/*
 * @(#)FileChooserPanel.java        $Revision: 1.3 $ $Date: 2008/11/04 18:48:12 $
 * 
 * Copyright (c) 2008 Milan Fort (http://www.milanfort.com/). All rights reserved.
 * 
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the "License"). You may not use this file except
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at http://www.sun.com/cddl/cddl.html.
 * See the License for the specific language governing permissions and limitations
 * under the License.
 */

package org.openesb.components.rules4jbi.netbeans.util.chooser;

import java.beans.PropertyChangeListener;
import java.beans.PropertyVetoException;

import javax.swing.tree.TreeSelectionModel;

import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.Node;

/**
 *
 * @author Milan Fort (http://www.milanfort.com/)
 * @version $Revision: 1.3 $ $Date: 2008/11/04 18:48:12 $
 * 
 * @since 0.1
 */
public final class FileChooserPanel extends javax.swing.JPanel implements ExplorerManager.Provider {
    
    private static final long serialVersionUID = -2449366228226639442L;
    
    private final ExplorerManager explorerManager;
    
    /** Creates new form FileChooserPanel */
    public FileChooserPanel(Node rootNode, String title) {
        initComponents();
        
        titleLabel.setText(title);
        
        explorerManager = new ExplorerManager();
        
        explorerManager.setRootContext(rootNode);
        
        BeanTreeView beanTreeView = (BeanTreeView) selectionScrollPane;
        
        beanTreeView.setPopupAllowed(false);
        beanTreeView.setDefaultActionAllowed(false);
        beanTreeView.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
    }

    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }
    
    void addExplorerManagerPropertyChangeListener(PropertyChangeListener listener) {
        explorerManager.addPropertyChangeListener(listener);
    }

    void clearSelection() {
        try {
            explorerManager.setSelectedNodes(new Node[] {});
            
        } catch (PropertyVetoException e) {
            //ignore; should actually never happen
        }
    }
    
    void hideRootNode() {
        BeanTreeView beanTreeView = (BeanTreeView) selectionScrollPane;
        
        beanTreeView.setRootVisible(false);
    }
    
    void expandAllNodes() {
        BeanTreeView beanTreeView = (BeanTreeView) selectionScrollPane;
        
        beanTreeView.expandAll();
    }
    
    Node getSelectedNode() {
        Node[] nodes = explorerManager.getSelectedNodes();

        /* should always be one, because we use single selection mode, unless no node is selected */
        if (nodes.length == 1) {
            return nodes[0];
            
        } else {
            return null;
        }
    }
    
    void setSelectedNode(Node node) {
        try {
            explorerManager.setSelectedNodes(new Node[] {node});
            
        } catch (PropertyVetoException e) {
            //ignore
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        selectionScrollPane = new BeanTreeView();

        titleLabel.setText(org.openide.util.NbBundle.getMessage(FileChooserPanel.class, "FileChooserPanel.titleLabel.text")); // NOI18N

        selectionScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlShadow));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(titleLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane selectionScrollPane;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
