//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module webservice{
					module generator{

    					// primitive
    					valuetype MyLong {
        					public long data;
    				    };

    					// complex
    					valuetype MySequence {
        					public sequence<long> data;
    				    };

    					interface foo {
        					// primitive
        					string bar_in(in MyLong n);
        					string bar_inout(inout MyLong n);

        					// complex
        					string complexBar_in(in MySequence si);
        					string complexBar_inout(inout MySequence sio);
        			    };
					};
				};
			};
		};
	};
};
