#include "EchoWithIncludesStruct.idl"
module test2{
	
	struct SomeStruct {
			test1::EchoStruct someStruct;
            boolean fieldBoolean;                                
            string fieldString;
	};            
};
