//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module webservice{
					module generator{

        				    // struct
           					struct EchoStruct {
              					long field1;
               				};

               				// array of struct
        					typedef long ArrayOfEchoStruct[10];


    					interface foo {
        					string barIn(in ArrayOfEchoStruct e);
        					string barOut(out ArrayOfEchoStruct e);
        					string barInOut(inout ArrayOfEchoStruct e);
        			    };
					};
				};
			};
		};
	};
};
