//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module testprovidersimple{
					
						interface EchoInOut {
							string echo(in string msg, inout string msgout);
						};
					
				};
			};
		};
	};
};
