//IDL
module it{
module imolinfo{
module jbi4corba{
module test{
module webservice{
module generator{

// simple types supported
// boolean 		
// char
// wchar
// string
// wstring
// short
// unsigned short 
// long
// unsigned long
// long long
// unsigned long long
// float
// double 
// octect


  typedef string mystring;  
  typedef long myint;  
  typedef boolean myboolean;
  typedef char mychar;
  typedef wchar mywchar;
  typedef wstring mywstring;
  typedef short myshort;
  typedef unsigned short myunsignedshort;
  typedef long mylong;
  typedef unsigned long myunsignedlong;
  typedef long long mylonglong ;
  typedef unsigned long long myunsignedlonglong;
  typedef float myfloat;
  typedef double mydouble;

  typedef any myany;

  interface Echo {
    string echo(in any msg);
  };
};
};
};
};
};
};
