//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module webservice{
					module generator{
  					// struct
					  struct EchoStruct {
					    boolean            fieldBoolean;
					    string             fieldString;
					  };

    					typedef sequence<long> SeqLong;
    					typedef sequence<string> SeqString;  					
					typedef sequence<EchoStruct> SeqEchoStruct;
					typedef string MatrixString[3][3];


    					interface foo {
	            				string barSeqStr(in SeqString str);
        	    				string barSeqLong(in SeqLong e);
        	    				string barSeqStruct(in SeqEchoStruct seq);
        	    				string barSeqStructSeqLong(in SeqEchoStruct seq, in SeqLong integ, inout string str2);
        	    				string barSeqStrInOut(inout SeqString str);
        	    				string barSeqLongInOut(inout SeqLong e);
              //        string barSeqEchoStruct(in unsigned long howmany,inout SeqEchoStruct e);
 						string echoMatrix(in MatrixString e);
        			    };
					};
				};
			};
		};
	};
};
