//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module webservice{
					module generator{

    				    // ===== struct
       					struct EchoStruct {
          					long field1;
           				};

           				// ===== exception
    					exception EchoComplexException {
        					long reasonCode;
        				};

        				// ===== insterface
    					interface foo {
        					string bar_in(in EchoStruct e)
        					    raises (EchoComplexException);

        					string bar_inout(inout EchoStruct e)
        					    raises (EchoComplexException);
    				    };

					};
				};
			};
		};
	};
};
