//IDL
module it{
module imolinfo{
module jbi4corba{
module test{
module webservice{
module generator{

// simple types supported
// boolean 		
// char
// wchar
// string
// wstring
// short
// unsigned short 
// long
// unsigned long
// long long
// unsigned long long
// float
// double 
// octect

  // Arrays
  typedef string mystringArr[2];  
  typedef long myintArr[2];  
  typedef boolean mybooleanArr[2];
  typedef char mycharArr[2];
  typedef wchar mywcharArr[2];
  typedef wstring mywstringArr[2];
  typedef short myshortArr[2];
  typedef unsigned short myunsignedshortArr[2];
  typedef long mylongArr[2];
  typedef unsigned long myunsignedlongArr[2];
  typedef long long mylonglongArr[2];
  typedef unsigned long long myunsignedlonglongArr[2];
  typedef float myfloatArr[2];
  typedef double mydoubleArr[2];
  typedef string MatrixString[3][3];
  typedef long MatrixLong[3][3];

  // Sequences
  typedef sequence <string> mystringSeq;
  typedef sequence <long> myintSeq;  
  typedef sequence <boolean> mybooleanSeq;
  typedef sequence <char> mycharSeq;
  typedef sequence <wchar> mywcharSeq;
  typedef sequence <wstring> mywstringSeq;
  typedef sequence <short> myshortSeq;
  typedef sequence <unsigned short> myunsignedshortSeq;
  typedef sequence <unsigned long> myunsignedlongSeq;
  typedef sequence <long long> mylonglongSeq;
  typedef sequence <unsigned long long> myunsignedlonglongSeq;
  typedef sequence <float> myfloatSeq;
  typedef sequence <double> mydoubleSeq;

  interface Echo {
    string echo(in any msg);
  };

};
};
};
};
};
};
