
		   interface Echo {
    		
			string echo(in string msg);

                 };
	
	
	
		   
		   interface Echo7{
		   	Echo echo(in string mesg);
		   };

		   interface Echo8{
		     Echo echo(in Echo intf); 
               };

		   interface Echo9{
		    Echo echo(in string luca,in Echo pippo,out Echo echoinout); 	
		   };

