//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module webservice{
					module generator{
    					valuetype EchoVT {
    						public string s;
    				    };

    					interface foo {
        					string barIn(in EchoVT e);
        					//string barInOut(inout EchoVT e);
        			    };
					};
				};
			};
		};
	};
};
