 module it{
    module imolinfo{

        interface Echo {
               string echo_method(in string msg);
        };

        interface EchoIn : Echo {
            long echoin_method(in long msg);
        };

};
};
