//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module webservice{
					module generator{

    					struct EchoStruct {
        					long field1;
        				};

    					interface foo {

                            string bar(in EchoStruct es);
                            string barInOut(inout EchoStruct es);
        			    };
					};
				};
			};
		};
	};
};
