//IDL
module it{
module imolinfo{
module jbi4corba{
module test{
module webservice{
module generator{
  interface Echo {
    string echo(in string msg);
  };
  interface Echo1 {
    string echo2(in string msg);
  };	
};
};
};
};
};
};
