module it {
	module imolinfo {
               module test{
		
                	interface IDLWithObject {
                            Object echo(in string msg);
                    };

                };
      };
};
