//IDL
module it{

module generator{
				
		   interface Echo {
    		
			string echo(in string msg);

                 };
	
	
	module test{	
		   
		   interface Echo1{
		   	it::generator::Echo echo(in string mesg);
		   };

		   interface Echo2{
		      it::generator::Echo echo(in it::generator::Echo intf); 
               };

		   interface Echo3{
		     it::generator::Echo echo(in string luca,in it::generator::Echo pippo,out it::generator::Echo echoinout); 	
		   };
	};

};
};