#ifndef foo_idl
#define foo_idl

#pragma prefix "my.namespace"
module foo {
    struct NameAndValue_T {
      string name;
      string value;
    };
    typedef sequence<NameAndValue_T> NameAndValueList_T;
    typedef NameAndValueList_T Bar_T;
    typedef sequence<NameAndValueList_T> BarList_T;
    interface Foo_I {
      boolean bar(in unsigned long how_many, inout BarList_T nameList);
    };
};
