//IDL
module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module webservice{
					module generator2{
						interface Echo {
							string echo(in string msg);
						};
						interface Math {
							long sum(in long num1,in long num2);
							long square(in long num1);
						};						
					};
				};
			};
		};
	};
};
