module it{
module imolinfo{
module jbi4corba{
module test{
	
	union TempUnion switch (short){
		case 1: long numeric;
		case 2: string alfanumeric;
		default: any two_format;
	};
	
	union FirstUnion switch (short){
		case 1: long numeric;
		case 2: string alfanumeric;
		case 3: TempUnion uni1;
		case 4: sequence <TempUnion> uni2;
		default: any two_format;
	};

	union SecondUnion switch (short){
		case 1: long numeric;
		case 2: string alfanumeric;
		default: any two_format;
	};

	union ThirdUnion switch (short) { 
		case 1: long primo; 
		case 2: short secondo; 
		case 3: sequence <FirstUnion> third;
		default: boolean altro; 
	}; 
	
	
	typedef short IntArr[2][3];
	typedef boolean BoolArr[2];
	
	interface Echo {
		string echo1(in ThirdUnion msg0, in IntArr msg1, in SecondUnion msg2);
		ThirdUnion echo2(in BoolArr msg0, in SecondUnion msg1,in BoolArr msg2, in IntArr msg3);
		FirstUnion echo3(in BoolArr msg0, in boolean msg1, in char msg2, in ThirdUnion msg3,  in boolean msg4, in char msg5);

		};
		
};};};}; 