module it{
module imolinfo{
module jbi4corba{
module test{
     union CharDUnion switch (char) {
          case 'a':      string aValue;
          case 'b':      long bValue;
          case 'c':      boolean cValue;
          default:       string defValue;
     };
     
     union BooleanDUnion switch (boolean) {
          case  TRUE:      string aValue;
          case FALSE:      long bValue;
          
     };
     
     union IntDUnion switch (long) {
          case 1:      string aValue;
          case 2:      long bValue;
          case 3:      boolean cValue;
          default:       string defValue;
     };
     
     enum MyEnum {first, second, third, fourth, fifth}; 
	
	union EnumDUnion switch (MyEnum) { 
		case first: string aValue; 
		case second: long bValue; 
		case third: boolean cValue; 
		default: boolean defValue; 
	}; 

     interface EchoDiscriminators {
	     string echoDiscriminator(in CharDUnion msg1, in BooleanDUnion msg2, in IntDUnion msg3, in EnumDUnion msg4);
     };
};};};}; 