<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://stc.com/echoSubstringAfter" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="echoSubstringAfter" targetNamespace="http://stc.com/echoSubstringAfter">
    <types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://stc.com/echoSubstringAfter">
            <xsd:element name="item">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="value" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </types>
    <message name="echoSubstringAfter">
        <part element="tns:item" name="part"/>
    </message>
    <portType name="echoSubstringAfter">
        <operation name="echoSubstringAfter">
            <input message="tns:echoSubstringAfter"/>
            <output message="tns:echoSubstringAfter"/>
        </operation>
    </portType>
    <binding name="Binding" type="tns:echoSubstringAfter">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="echoSubstringAfter">
            <soap:operation soapAction="echoSubstringAfter"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="echoSubstringAfterService">
        <port binding="tns:Binding" name="port">
            <soap:address location="http://localhost:${HttpDefaultPort}/echoSubstringAfter"/>
        </port>
    </service>
    <plnk:partnerLinkType xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="SLT">
        <plnk:role name="server" portType="tns:echoSubstringAfter"/>
    </plnk:partnerLinkType>
</definitions>
