<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AlterColumnWrongParamSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="AlterColumnWrongParamRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="AlterColumnWrongParamResponse">
    <part name="AlterColumnWrongParamResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="AlterColumnWrongParamRequest">
    <part name="AlterColumnWrongParamRequestPart" element="tns:AlterColumnWrongParamRequest"/>
  </message>
  <portType name="AlterColumnWrongParamSql_sqlsePortType">
    <operation name="AlterColumnWrongParam">
      <input name="AlterColumnWrongParamRequest" message="tns:AlterColumnWrongParamRequest"/>
      <output name="AlterColumnWrongParamResponse" message="tns:AlterColumnWrongParamResponse"/>
    </operation>
  </portType>
  <binding name="AlterColumnWrongParamSqlBinding" type="tns:AlterColumnWrongParamSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="AlterColumnWrongParam">
      <soap:operation/>
      <input name="AlterColumnWrongParamRequest">
        <soap:body/>
      </input>
      <output name="AlterColumnWrongParamResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="AlterColumnWrongParamSql_sqlseService">
    <port name="AlterColumnWrongParamSql_sqlsePort" binding="tns:AlterColumnWrongParamSqlBinding">
      <soap:address location="http://localhost:18181/AlterColumnWrongParamSql/AlterColumnWrongParamSql/AlterColumnWrongParamSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="AlterColumnWrongParamSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="AlterColumnWrongParamSql_myrole" portType="tns:AlterColumnWrongParamSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
