module it{
module imolinfo{
module jbi4corba{
module test{
module testconsumerfromidlanytypes {
	
	union TempUnion switch (short){
		case 1: long numeric;
		case 2: string alfanumeric;
		default: any two_format;
	};
	
	struct ComplexStruct1 {
		boolean          fieldBoolean;
		char               fieldChar;
	        sequence<any>    fieldAny;
	};
	
	typedef any ArrayOfAny[2][3];
	// exception
	exception EchoAnyException {
	any reason;
	};  
	
	interface EchoAnyTypes {
		string echo1(inout any msg);
		any echo2(in any msg) raises(EchoAnyException);
		ComplexStruct1 echo3(in TempUnion msg);
		ArrayOfAny echo4(inout ComplexStruct1 msg);
		};
};};};};};