package org.netbeans.j2ee.wsdl.inoutservice.calcpototalvalue;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2
 * Wed Mar 25 00:28:47 PDT 2009
 * Generated source version: 2.2
 * 
 */
 
@WebService(targetNamespace = "http://j2ee.netbeans.org/wsdl/InOutService/calcPOTotalValue", name = "callbackCalcTotalValuePO")
@XmlSeeAlso({org.netbeans.xml.schema.poschema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CallbackCalcTotalValuePO {

    @Oneway
    @WebMethod
    public void getPO(
        @WebParam(partName = "part1", name = "order", targetNamespace = "http://xml.netbeans.org/schema/POSchema")
        org.netbeans.xml.schema.poschema.PoType part1
    );
}
