<?xml version="1.0" encoding="UTF-8"?>


<wsdl:definitions name="ScopeWithinWhileTest"
             targetNamespace="http://www.mycomp.org/ScopeWithinWhile/ScopeWithinWhileTest"
             xmlns:tns="http://www.mycomp.org/ScopeWithinWhile/ScopeWithinWhileTest"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"                          
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <wsdl:message name="RequestMsg">
        <wsdl:part name="Req" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="ResponseMsg">
        <wsdl:part name="Res" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="CountMsg">
        <wsdl:part name="Count" type="xsd:int"/>
    </wsdl:message>
    <wsdl:portType name="ScopePort">
        <wsdl:operation name="ScopeOperation">
            <wsdl:input name="input" message="tns:RequestMsg"/>
            <wsdl:output name="output" message="tns:ResponseMsg"/>
        </wsdl:operation>
    </wsdl:portType>

        <binding name="ScopeBinding" type="tns:ScopePort">
            <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
                <operation name="ScopeOperation">
                        <soap:operation style="document"/>
                        <input name="input">
                     <soap:body use="literal"/>
                </input><output name="output">
    <soap:body use="literal"/>
</output>
                </operation>
        </binding>

   
         <wsdl:service name="ScopeWithinWhileTestService">
		<wsdl:port name="ScopeWithinWhileTestPortName" binding="tns:ScopeBinding">                    
                     <soap:address location="http://localhost:${HttpDefaultPort}/ScopeWithinWhileTest"/>
		</wsdl:port>
        </wsdl:service>

	<plnk:partnerLinkType name="ScopeWithinWhileTestPartnerLinkType">
		<plnk:role name="ScopeWithinWhileTestProvider" portType="tns:ScopePort"/>
	</plnk:partnerLinkType>

</wsdl:definitions>


 

 

 

 

 
