<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/SoapTrigger4FileReqReplyOut"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/SoapTrigger4FileReqReplyOut" name="SoapTrigger4FileReqReplyOut" xmlns:ns="http://xml.netbeans.org/schema/SimpleSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/SoapTrigger4FileReqReplyOut">
            <xsd:import namespace="http://xml.netbeans.org/schema/SimpleSchema" schemaLocation="SimpleSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="SoapTrigger4FileReqReplyOutOperationRequest">
        <part name="part1" type="ns:requestType"/>
    </message>
    <message name="SoapTrigger4FileReqReplyOutOperationReply">
        <part name="part1" type="ns:responseType"/>
    </message>
    <portType name="SoapTrigger4FileReqReplyOutPortType">
        <wsdl:operation name="SoapTrigger4FileReqReplyOutOperation">
            <wsdl:input name="input1" message="tns:SoapTrigger4FileReqReplyOutOperationRequest"/>
            <wsdl:output name="output1" message="tns:SoapTrigger4FileReqReplyOutOperationReply"/>
        </wsdl:operation>
    </portType>
    <plnk:partnerLinkType name="SoapTrigger4FileReqReplyOutPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SoapTrigger4FileReqReplyOutPortTypeRole" portType="tns:SoapTrigger4FileReqReplyOutPortType"/>
    </plnk:partnerLinkType>
</definitions>
