<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DeneigementServiceServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/DeneigementServiceServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/DeneigementServiceServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://deneigement.utbm.fr/">
    <import location="DeneigementServiceService.wsdl" namespace="http://deneigement.utbm.fr/"/>
    <plnk:partnerLinkType name="DeneigementServiceLinkType">
        <plnk:role name="DeneigementServiceRole" portType="ns:DeneigementService"/>
    </plnk:partnerLinkType>
</definitions>
