<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SequenceNested"
             targetNamespace="http://www.mycomp.org/DefaultServiceName"
             xmlns:tns="http://www.mycomp.org/DefaultServiceName"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"                          
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns0="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:message name="message1">
        <wsdl:part name="parameter1" type="xsd:string"/>
        <wsdl:part name="parameter2" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="SequenceNestedPortType">
        <wsdl:operation name="SequenceNestedOperation">
            <wsdl:input name="input1" message="tns:message1"/>
            <wsdl:output name="output1" message="tns:message1"/>
        </wsdl:operation>
    </wsdl:portType>

        <binding name="SequenceNestedSoapBinding" type="tns:SequenceNestedPortType">
            <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
                <operation name="SequenceNestedOperation">
                        <soap:operation style="document"/>
                        <input name="input1">
                     <soap:body/>
                </input><output name="output1">
    <soap:body/>
</output>
                </operation>
        </binding>

   
         <wsdl:service name="SequenceNestedService">
		<wsdl:port name="SequenceNestedPortName" binding="tns:SequenceNestedSoapBinding">                    
                     <soap:address location="http://localhost:${HttpDefaultPort}/SequenceNested"/>
		</wsdl:port>
        </wsdl:service>

	<plnk:partnerLinkType name="SequenceNestedPartnerLinkType">
		<plnk:role name="SequenceNestedProvider" portType="tns:SequenceNestedPortType"/>
	</plnk:partnerLinkType>

</wsdl:definitions>


 

 

 

 

 
