<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InsertOneFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="InsertOneFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="InsertOneFullQualResponse">
    <part name="InsertOneFullQualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="InsertOneFullQualRequest">
    <part name="InsertOneFullQualRequestPart" element="tns:InsertOneFullQualRequest"/>
  </message>
  <portType name="InsertOneFullQualSql_sqlsePortType">
    <operation name="InsertOneFullQual">
      <input name="InsertOneFullQualRequest" message="tns:InsertOneFullQualRequest"/>
      <output name="InsertOneFullQualResponse" message="tns:InsertOneFullQualResponse"/>
    </operation>
  </portType>
  <binding name="InsertOneFullQualSqlBinding" type="tns:InsertOneFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="InsertOneFullQual">
      <soap:operation/>
      <input name="InsertOneFullQualRequest">
        <soap:body/>
      </input>
      <output name="InsertOneFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="InsertOneFullQualSql_sqlseService">
    <port name="InsertOneFullQualSql_sqlsePort" binding="tns:InsertOneFullQualSqlBinding">
      <soap:address location="http://localhost:18181/InsertOneFullQualSql/InsertOneFullQualSql/InsertOneFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="InsertOneFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="InsertOneFullQualSql_myrole" portType="tns:InsertOneFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
