<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongViewSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongViewRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongViewResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongViewResponse">
    <part name="SelectWrongViewResponsePart" element="tns:SelectWrongViewResponse"/>
  </message>
  <message name="SelectWrongViewRequest">
    <part name="SelectWrongViewRequestPart" element="tns:SelectWrongViewRequest"/>
  </message>
  <portType name="SelectWrongViewSql_sqlsePortType">
    <operation name="SelectWrongView">
      <input name="SelectWrongViewRequest" message="tns:SelectWrongViewRequest"/>
      <output name="SelectWrongViewResponse" message="tns:SelectWrongViewResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongViewSqlBinding" type="tns:SelectWrongViewSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongView">
      <soap:operation/>
      <input name="SelectWrongViewRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongViewResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongViewSql_sqlseService">
    <port name="SelectWrongViewSql_sqlsePort" binding="tns:SelectWrongViewSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongViewSql/SelectWrongViewSql/SelectWrongViewSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongViewSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongViewSql_myrole" portType="tns:SelectWrongViewSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
