<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableSmallSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableSmallRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableSmallRequest">
    <part name="CreateTableSmallRequestPart" element="tns:CreateTableSmallRequest"/>
  </message>
  <message name="CreateTableSmallResponse">
    <part name="CreateTableSmallResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="CreateTableSmallSql_sqlsePortType">
    <operation name="CreateTableSmall">
      <input name="CreateTableSmallRequest" message="tns:CreateTableSmallRequest"/>
      <output name="CreateTableSmallResponse" message="tns:CreateTableSmallResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableSmallSqlBinding" type="tns:CreateTableSmallSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableSmall">
      <soap:operation/>
      <input name="CreateTableSmallRequest">
        <soap:body/>
      </input>
      <output name="CreateTableSmallResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableSmallSql_sqlseService">
    <port name="CreateTableSmallSql_sqlsePort" binding="tns:CreateTableSmallSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableSmallSql/CreateTableSmallSql/CreateTableSmallSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableSmallSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableSmallSql_myrole" portType="tns:CreateTableSmallSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
