<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectOneParamFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectOneParamFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectOneParamFullQualResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectOneParamFullQualResponse">
    <part name="SelectOneParamFullQualResponsePart" element="tns:SelectOneParamFullQualResponse"/>
  </message>
  <message name="SelectOneParamFullQualRequest">
    <part name="SelectOneParamFullQualRequestPart" element="tns:SelectOneParamFullQualRequest"/>
  </message>
  <portType name="SelectOneParamFullQualSql_sqlsePortType">
    <operation name="SelectOneParamFullQual">
      <input name="SelectOneParamFullQualRequest" message="tns:SelectOneParamFullQualRequest"/>
      <output name="SelectOneParamFullQualResponse" message="tns:SelectOneParamFullQualResponse"/>
    </operation>
  </portType>
  <binding name="SelectOneParamFullQualSqlBinding" type="tns:SelectOneParamFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectOneParamFullQual">
      <soap:operation/>
      <input name="SelectOneParamFullQualRequest">
        <soap:body/>
      </input>
      <output name="SelectOneParamFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectOneParamFullQualSql_sqlseService">
    <port name="SelectOneParamFullQualSql_sqlsePort" binding="tns:SelectOneParamFullQualSqlBinding">
      <soap:address location="http://localhost:18181/SelectOneParamFullQualSql/SelectOneParamFullQualSql/SelectOneParamFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectOneParamFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectOneParamFullQualSql_myrole" portType="tns:SelectOneParamFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
