<?xml version="1.0" encoding="UTF-8"?>
<definitions name="FTP" targetNamespace="http://j2ee.netbeans.org/wsdl/FTP_CLIENT"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/FTP_CLIENT" xmlns:ns="http://xml.netbeans.org/schema/SimpleSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ftp="http://schemas.sun.com/jbi/wsdl-extensions/ftp/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/FTP_CLIENT">
            <xsd:import namespace="http://xml.netbeans.org/schema/SimpleSchema" schemaLocation="SimpleSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="FTPOperationRequest">
        <part name="part1" type="ns:requestType"/>
    </message>
    <portType name="FTPPortType">
        <operation name="FTPOperation">
            <input name="input1" message="tns:FTPOperationRequest"/>
        </operation>
    </portType>
    <binding name="binding1" type="tns:FTPPortType">
        <ftp:binding/>
        <operation name="FTPOperation">
            <ftp:operation/>
            <input name="input1">
                <ftp:message messageRepository="GREETER_GREETEE_REPO_EE" archive="true" protect="true" use="literal" messageCorrelate="true" messageName="%u" messageNamePrefixIB="req." messageNamePrefixOB="resp." pollIntervalMillis="5000" stage="true"/>
            </input>
        </operation>
    </binding>
    <service name="service1">
        <port name="port1" binding="tns:binding1">
            <ftp:address url="ftp://${test_ftp_user}:${test_ftp_password}@${test_ftp_server_name}:${test_ftp_server_port}" useUserDefinedHeuristics="false" mode="BINARY" cmdChannelTimeout="56000" dataChannelTimeout="56000"/>
            <!--
            <ftp:address url="ftp://anonymous:abc\@yahoo.com@goose.stc.com:1021" useUserDefinedHeuristics="false" mode="BINARY" dirListStyle="NT 4.0" cmdChannelTimeout="56000" dataChannelTimeout="56000"/>
            -->
        </port>
    </service>
    <plink:partnerLinkType name="FTPPartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plink:role name="FTPPortTypeRole" portType="tns:FTPPortType"/>
    </plink:partnerLinkType>
</definitions>
