package it.imolinfo.jbi4corba.test.testprovideranytypes;


/**
* it/imolinfo/jbi4corba/test/testprovideranytypes/ArrayOfAnyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/imolaCSV/nokia/open-jbi-components/contrib-imola/corba-bc/integration-test/test-provider-anytypes/provider-anytypes-jbi4corba-provider/src/main/resources/AnyTypes.idl
* lunedì 2 febbraio 2009 12.26.09 EET
*/

abstract public class ArrayOfAnyHelper
{
  private static String  _id = "IDL:it/imolinfo/jbi4corba/test/testprovideranytypes/ArrayOfAny:1.0";

  public static void insert (org.omg.CORBA.Any a, org.omg.CORBA.Any[][] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.omg.CORBA.Any[][] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_any);
      __typeCode = org.omg.CORBA.ORB.init ().create_array_tc (2, __typeCode );
      __typeCode = org.omg.CORBA.ORB.init ().create_array_tc (3, __typeCode );
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (it.imolinfo.jbi4corba.test.testprovideranytypes.ArrayOfAnyHelper.id (), "ArrayOfAny", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.omg.CORBA.Any[][] read (org.omg.CORBA.portable.InputStream istream)
  {
    org.omg.CORBA.Any value[][] = null;
    value = new org.omg.CORBA.Any[2][];
    for (int _o0 = 0;_o0 < (2); ++_o0)
    {
      value[_o0] = new org.omg.CORBA.Any[3];
      for (int _o1 = 0;_o1 < (3); ++_o1)
      {
        value[_o0][_o1] = istream.read_any ();
      }
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.omg.CORBA.Any[][] value)
  {
    if (value.length != (2))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (2); ++_i0)
    {
      if (value[_i0].length != (3))
        throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
      for (int _i1 = 0;_i1 < (3); ++_i1)
      {
        ostream.write_any (value[_i0][_i1]);
      }
    }
  }

}
