package it.imolinfo.jbi4corba.test.testprovideranytypes;

/**
* it/imolinfo/jbi4corba/test/testprovideranytypes/EchoAnyTypesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/imolaCSV/nokia/open-jbi-components/contrib-imola/corba-bc/integration-test/test-provider-anytypes/provider-anytypes-jbi4corba-provider/src/main/resources/AnyTypes.idl
* lunedì 2 febbraio 2009 12.26.09 EET
*/

public final class EchoAnyTypesHolder implements org.omg.CORBA.portable.Streamable
{
  public it.imolinfo.jbi4corba.test.testprovideranytypes.EchoAnyTypes value = null;

  public EchoAnyTypesHolder ()
  {
  }

  public EchoAnyTypesHolder (it.imolinfo.jbi4corba.test.testprovideranytypes.EchoAnyTypes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = it.imolinfo.jbi4corba.test.testprovideranytypes.EchoAnyTypesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    it.imolinfo.jbi4corba.test.testprovideranytypes.EchoAnyTypesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return it.imolinfo.jbi4corba.test.testprovideranytypes.EchoAnyTypesHelper.type ();
  }

}
