<?xml version="1.0" encoding="UTF-8"?>
<definitions name="BPThrowsMsgWithNoPartsNoAssign" targetNamespace="http://j2ee.netbeans.org/wsdl/BPThrowsMsgWithNoPartsNoAssign"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/BPThrowsMsgWithNoPartsNoAssign" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="BPThrowsMsgWithNoPartsNoAssignOperationRequest"/>
    <message name="BPThrowsMsgWithNoPartsNoAssignOperationReply"/>
    <message name="FaultMessage"></message>    
    <portType name="BPThrowsMsgWithNoPartsNoAssignPortType">
        <wsdl:operation name="BPThrowsMsgWithNoPartsNoAssignOperation">
            <wsdl:input name="input1" message="tns:BPThrowsMsgWithNoPartsNoAssignOperationRequest"/>
            <wsdl:output name="output1" message="tns:BPThrowsMsgWithNoPartsNoAssignOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="BPThrowsMsgWithNoPartsNoAssignBinding" type="tns:BPThrowsMsgWithNoPartsNoAssignPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="BPThrowsMsgWithNoPartsNoAssignOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/BPThrowsMsgWithNoPartsNoAssign"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/BPThrowsMsgWithNoPartsNoAssign"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="BPThrowsMsgWithNoPartsNoAssignService">
        <wsdl:port name="BPThrowsMsgWithNoPartsNoAssignPort" binding="tns:BPThrowsMsgWithNoPartsNoAssignBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/BPThrowsMsgWithNoPartsNoAssignService/BPThrowsMsgWithNoPartsNoAssignPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="BPThrowsMsgWithNoPartsNoAssign1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="BPThrowsMsgWithNoPartsNoAssignPortTypeRole" portType="tns:BPThrowsMsgWithNoPartsNoAssignPortType"/>
    </plnk:partnerLinkType>
</definitions>
