<?xml version="1.0" encoding="UTF-8"?>
<definitions name="MessageWithNoPartsNoAssignSUbBP" targetNamespace="http://j2ee.netbeans.org/wsdl/MessageWithNoPartsNoAssignSUbBP"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/MessageWithNoPartsNoAssignSUbBP" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="MessageWithNoPartsNoAssignSUbBPOperationRequest"/>
    <message name="MessageWithNoPartsNoAssignSUbBPOperationReply"/>
    <portType name="MessageWithNoPartsNoAssignSUbBPPortType">
        <wsdl:operation name="MessageWithNoPartsNoAssignSUbBPOperation">
            <wsdl:input name="input1" message="tns:MessageWithNoPartsNoAssignSUbBPOperationRequest"/>
            <wsdl:output name="output1" message="tns:MessageWithNoPartsNoAssignSUbBPOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="MessageWithNoPartsNoAssignSUbBPBinding" type="tns:MessageWithNoPartsNoAssignSUbBPPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="MessageWithNoPartsNoAssignSUbBPOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/MessageWithNoPartsNoAssignSUbBP"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/MessageWithNoPartsNoAssignSUbBP"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="MessageWithNoPartsNoAssignSUbBPService">
        <wsdl:port name="MessageWithNoPartsNoAssignSUbBPPort" binding="tns:MessageWithNoPartsNoAssignSUbBPBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/MessageWithNoPartsNoAssignSUbBPService/MessageWithNoPartsNoAssignSUbBPPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="MessageWithNoPartsNoAssignSUbBP1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="MessageWithNoPartsNoAssignSUbBPPortTypeRole" portType="tns:MessageWithNoPartsNoAssignSUbBPPortType"/>
    </plnk:partnerLinkType>
</definitions>
