<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Parent2WSDLRIT39666" targetNamespace="http://j2ee.netbeans.org/wsdl/Parent2WSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Parent2WSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="Parent2WSDLOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="Parent2WSDLOperationReply">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="Parent2WSDLPortType">
        <wsdl:operation name="Parent2WSDLOperation">
            <wsdl:input name="input1" message="tns:Parent2WSDLOperationRequest"/>
        </wsdl:operation>
    </portType>
    <binding name="Parent2WSDLBinding" type="tns:Parent2WSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Parent2WSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/Parent2WSDL"/>
            </wsdl:input>
        </wsdl:operation>
    </binding>
    <service name="Parent2WSDLService">
        <wsdl:port name="Parent2WSDLPort" binding="tns:Parent2WSDLBinding">
            <soap:address location="http://localhost:18181/Parent2WSDLService/Parent2WSDLPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="Parent2WSDLRIT396661">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="Parent2WSDLPortTypeRole" portType="tns:Parent2WSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
