<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableDupSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableDupRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableDupResponse">
    <part name="CreateTableDupResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateTableDupRequest">
    <part name="CreateTableDupRequestPart" element="tns:CreateTableDupRequest"/>
  </message>
  <portType name="CreateTableDupSql_sqlsePortType">
    <operation name="CreateTableDup">
      <input name="CreateTableDupRequest" message="tns:CreateTableDupRequest"/>
      <output name="CreateTableDupResponse" message="tns:CreateTableDupResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableDupSqlBinding" type="tns:CreateTableDupSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableDup">
      <soap:operation/>
      <input name="CreateTableDupRequest">
        <soap:body/>
      </input>
      <output name="CreateTableDupResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableDupSql_sqlseService">
    <port name="CreateTableDupSql_sqlsePort" binding="tns:CreateTableDupSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableDupSql/CreateTableDupSql/CreateTableDupSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableDupSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableDupSql_myrole" portType="tns:CreateTableDupSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
