<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/newWSDL1"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/newWSDL1" name="newWSDL1" xmlns:ns="http://xml.netbeans.org/schema/dataTypes.xsd" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/newWSDL1">
            <xsd:import namespace="http://xml.netbeans.org/schema/dataTypes.xsd" schemaLocation="dataTypes.xsd"/>
        </xsd:schema>
    </types>
    <message name="newWSDL1OperationRequest">
        <part name="part1" element="ns:helloObj"/>
    </message>
    <message name="newWSDL1OperationReply">
        <part name="part1" element="ns:helloObj"/>
    </message>
    <portType name="newWSDL1PortType">
        <wsdl:operation name="newWSDL1Operation">
            <wsdl:input name="input1" message="tns:newWSDL1OperationRequest"/>
            <wsdl:output name="output1" message="tns:newWSDL1OperationRequest"/>
        </wsdl:operation>
    </portType>
    <binding name="newWSDL1Binding" type="tns:newWSDL1PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="newWSDL1Operation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="newWSDL1Service">
        <wsdl:port name="newWSDL1Port" binding="tns:newWSDL1Binding">
            <soap:address location="http://localhost:${HttpDefaultPort}/newWSDL1Service/newWSDL1Port"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="newWSDL11">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="newWSDL1PortTypeRole" portType="tns:newWSDL1PortType"/>
    </plnk:partnerLinkType>
</definitions>
