<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/EJBTestDriver"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/EJBTestDriver" name="EJBTestDriver" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">

  <!-- Type definitions -->
    <message name="EJBTestDriverOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="EJBTestDriverOperationReply">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="EJBTestDriverPortType">
        <wsdl:operation name="EJBTestDriverOperation">
            <wsdl:input name="input1" message="tns:EJBTestDriverOperationRequest"/>
            <wsdl:output name="output1" message="tns:EJBTestDriverOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="EJBTestDriverBinding" type="tns:EJBTestDriverPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="EJBTestDriverOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/EJBTestDriver"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/EJBTestDriver"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="EJBTestDriverService">
        <wsdl:port name="EJBTestDriverPort" binding="tns:EJBTestDriverBinding">
            <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
        </wsdl:port>
    </service>
</definitions>
