<?xml version="1.0" encoding="UTF-8"?>
<definitions name="LTS_SubBPWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/LTS_SubBPWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/LTS_SubBPWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns0="http://j2ee.netbeans.org/wsdl/SupplyChainMessageWSDL">
    <import location="SupplyChainMessageWSDL.wsdl" namespace="http://j2ee.netbeans.org/wsdl/SupplyChainMessageWSDL"/>
    <types/>
    <portType name="LTS_SubBPWSDLPortType">
        <operation name="LTS_SubBPWSDLOperation">
            <input name="input1" message="ns0:Load_Attribute_SubBPInput"/>
        </operation>
    </portType>
    <portType name="LTS_SubBPWSDLCallBackPortType">
        <operation name="LTS_SubBPWSDLCallBackOperation">
            <input name="input2" message="ns0:Load_Attribute_SubBPReply"/>
        </operation>
    </portType>
    <binding name="LTS_SubBPWSDLBinding" type="tns:LTS_SubBPWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="LTS_SubBPWSDLOperation">
            <soap:operation style="document"/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/LTS_SubBPWSDL"/>
            </input>
        </operation>
    </binding>
    <binding name="LTS_SubBPWSDLCallBackPortTypeBinding_Europe" type="tns:LTS_SubBPWSDLCallBackPortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="LTS_SubBPWSDLCallBackOperation">
            <soap:operation style="document"/>
            <input name="input2">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/LTS_SubBPWSDL"/>
            </input>
        </operation>
    </binding>
    <service name="LTS_SubBPWSDLService">
        <port name="LTS_SubBPWSDLPort" binding="tns:LTS_SubBPWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/LTS_SubBPWSDLService/LTS_SubBPWSDLPort"/>
        </port>
        <port name="LTS_SubBPWSDLCallBackPortTypeBindingPort" binding="tns:LTS_SubBPWSDLCallBackPortTypeBinding_Europe">
            <soap:address location="http://localhost:${HttpDefaultPort}/LTS_SubBPWSDLService/LTS_SubBPWSDLCallBackPortTypeBindingPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="LTS_SubBPReceivePT">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="LTS_SubBPWSDLPortTypeRole" portType="tns:LTS_SubBPWSDLPortType"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="LTS_SubBPWSDLCallBackPT">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="LTS_SubBPWSDLCallBackPortTypeRole" portType="tns:LTS_SubBPWSDLCallBackPortType"/>
    </plnk:partnerLinkType>
</definitions>
