<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns0="http://xml.netbeans.org/schema/pfizer/OTDLoadAttributes" xmlns:ns="http://j2ee.netbeans.org/wsdl/SupplyChainMessageWSDL" xmlns:ns1="http://j2ee.netbeans.org/wsdl/SupplyChainMessageWSDL" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties">
    <import namespace="http://j2ee.netbeans.org/wsdl/bpLSC_EuropeELCJMSWSDL" location="SupplyChain_MainBPJMSWSDL.wsdl"/>
    <import namespace="http://j2ee.netbeans.org/wsdl/LTS_SubBPWSDL" location="LTS_SubBPWSDL.wsdl"/>
    <import location="SupplyChainMessageWSDL.wsdl" namespace="http://j2ee.netbeans.org/wsdl/SupplyChainMessageWSDL"/>
    <import namespace="http://j2ee.netbeans.org/wsdl/LSP_SubBPWSDL" location="LSP_SubBPWSDL.wsdl"/>
    <types>
        <xsd:schema targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties">
            <xsd:import namespace="http://xml.netbeans.org/schema/pfizer/OTDLoadAttributes" schemaLocation="Partners/jcdLoadBuiltInManu/LOAD_ATTRIBUTES.xsd"/>
        </xsd:schema>
    </types>
    <vprop:property name="wzrd_prop_LOAD_ID_LOAD_ID" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_LOAD_ID_LOAD_ID" messageType="ns:Load_Attribute_SubBPInput" part="part1">
        <vprop:query>/ns0:LOAD_ATTRIBUTES/ns0:LOAD_ID</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_LOAD_ID_LOAD_ID" messageType="ns:Load_Attribute_SubBPReply" part="part1">
        <vprop:query>/ns0:LOAD_ATTRIBUTE_REPLY/ns0:LOAD_ATTRIBUTES/ns0:LOAD_ID</vprop:query>
    </vprop:propertyAlias>
    <vprop:property name="wzrd_prop_QUANTITY_LTS_QUANTITY_LTS" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_QUANTITY_LTS_QUANTITY_LTS" messageType="ns:Load_Attribute_SubBPInput" part="part1">
        <vprop:query>/ns0:LOAD_ATTRIBUTES/ns0:QUANTITY_LTS</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_QUANTITY_LTS_QUANTITY_LTS" messageType="ns:Load_Attribute_SubBPReply" part="part1">
        <vprop:query>/ns0:LOAD_ATTRIBUTE_REPLY/ns0:LOAD_ATTRIBUTES/ns0:QUANTITY_LTS</vprop:query>
    </vprop:propertyAlias>
</definitions>
