<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectOneParamSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectOneParamRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectOneParamResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectOneParamRequest">
    <part name="SelectOneParamRequestPart" element="tns:SelectOneParamRequest"/>
  </message>
  <message name="SelectOneParamResponse">
    <part name="SelectOneParamResponsePart" element="tns:SelectOneParamResponse"/>
  </message>
  <portType name="SelectOneParamSql_sqlsePortType">
    <operation name="SelectOneParam">
      <input name="SelectOneParamRequest" message="tns:SelectOneParamRequest"/>
      <output name="SelectOneParamResponse" message="tns:SelectOneParamResponse"/>
    </operation>
  </portType>
  <binding name="SelectOneParamSqlBinding" type="tns:SelectOneParamSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectOneParam">
      <soap:operation/>
      <input name="SelectOneParamRequest">
        <soap:body/>
      </input>
      <output name="SelectOneParamResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectOneParamSql_sqlseService">
    <port name="SelectOneParamSql_sqlsePort" binding="tns:SelectOneParamSqlBinding">
      <soap:address location="http://localhost:18181/SelectOneParamSql/SelectOneParamSql/SelectOneParamSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectOneParamSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectOneParamSql_myrole" portType="tns:SelectOneParamSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
