/*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at http://www.netbeans.org/cddl.html
 * or http://www.netbeans.org/cddl.txt.
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://www.netbeans.org/cddl.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
 * Microsystems, Inc. All Rights Reserved.
 */


package org.netbeans.modules.jbi.apisupport.project.wizard;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.StringTokenizer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import org.netbeans.modules.j2ee.deployment.devmodules.api.ServerManager;
import org.netbeans.modules.jbi.apisupport.JbiAdminSettings;
import org.netbeans.modules.jbi.apisupport.common.wizard.AbstractWizardModel;
import org.netbeans.modules.jbi.apisupport.common.wizard.AbstractWizardVisualPanel;
import org.netbeans.modules.jbi.apisupport.common.wizard.ProjectLocationVisualPanel;
import org.openide.WizardDescriptor;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;

/** A single panel for a wizard - the GUI portion.
 *
 * @author chikkala
 */
public class BCDPCompDescriptionVisualPanel
        extends AbstractWizardVisualPanel
        implements PropertyChangeListener {
    
    /** Create the wizard panel and set up some basic properties. */
    public BCDPCompDescriptionVisualPanel(DeployPluginProjectPanel panel) {
        super(panel);
        initComponents();
        // Provide a name in the title bar.
        setName(NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class,
                "TITLE_ComponentDescriptionPanel"));
        this.mEngineTypeValue =
                org.openide.util.NbBundle.getMessage(
                BCDPCompDescriptionVisualPanel.class, "LBL_ServiceEngine");
        this.mBindingTypeValue =
                org.openide.util.NbBundle.getMessage(
                BCDPCompDescriptionVisualPanel.class, "LBL_BindingComponent");
        
        this.mNameTF.getDocument().addDocumentListener( new DocumentListener() {
            
            public void insertUpdate(DocumentEvent e) {
                componentNameChanged();
            }
            
            public void removeUpdate(DocumentEvent e) {
                componentNameChanged();
            }
            
            public void changedUpdate(DocumentEvent e) {
                componentNameChanged();
            }
            
        });
        
        
        this.mPackageTF.getDocument().addDocumentListener( new DocumentListener() {
            
            public void insertUpdate(DocumentEvent e) {
                packageNameChanged();
            }
            
            public void removeUpdate(DocumentEvent e) {
                packageNameChanged();
            }
            
            public void changedUpdate(DocumentEvent e) {
                packageNameChanged();
            }
            
        });
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mPackageLBL = new javax.swing.JLabel();
        mPackageTF = new javax.swing.JTextField();
        mComponentTypeLBL = new javax.swing.JLabel();
        mComponentTypeValueLBL = new javax.swing.JLabel();
        mNameLBL = new javax.swing.JLabel();
        mNameTF = new javax.swing.JTextField();
        mDescriptionLBL = new javax.swing.JLabel();
        mDescriptionScrollPane = new javax.swing.JScrollPane();
        mDescriptionTA = new javax.swing.JTextArea();
        mWsdlExtPanel = new javax.swing.JPanel();
        mNamespaceLBL = new javax.swing.JLabel();
        mNamespaceTF = new javax.swing.JTextField();
        mNSPrefixLBL = new javax.swing.JLabel();
        mNSPrefixTF = new javax.swing.JTextField();
        mDummyLBL = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        mPackageLBL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mPackageLBL.setLabelFor(mPackageTF);
        mPackageLBL.setText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "BasicCompDescPanel.ComponentSourcePackage.LBL"));
        mPackageLBL.setToolTipText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "TIP_Package"));
        mPackageLBL.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        add(mPackageLBL, gridBagConstraints);

        mPackageTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mPackageTFKeyTyped(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        add(mPackageTF, gridBagConstraints);

        mComponentTypeLBL.setLabelFor(mComponentTypeValueLBL);
        mComponentTypeLBL.setText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "BasicCompDescPanel.ComponentType.LBL"));
        mComponentTypeLBL.setToolTipText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "TIP_LBL_ComponentType"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(mComponentTypeLBL, gridBagConstraints);

        mComponentTypeValueLBL.setText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "LBL_ServiceEngine"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(mComponentTypeValueLBL, gridBagConstraints);

        mNameLBL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mNameLBL.setLabelFor(mNameTF);
        mNameLBL.setText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "BasicCompDescPanel.ComponentName.LBL"));
        mNameLBL.setToolTipText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "TIP_LBL_ComponentName"));
        mNameLBL.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(mNameLBL, gridBagConstraints);

        mNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNameTFActionPerformed(evt);
            }
        });
        mNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mNameTFKeyTyped(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(mNameTF, gridBagConstraints);

        mDescriptionLBL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mDescriptionLBL.setLabelFor(mDescriptionTA);
        mDescriptionLBL.setText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "BasicCompDescPanel.ComponentDesc.LBL"));
        mDescriptionLBL.setToolTipText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "TIP_LBL_ComponentDescription"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(mDescriptionLBL, gridBagConstraints);

        mDescriptionScrollPane.setPreferredSize(new java.awt.Dimension(4, 40));
        mDescriptionTA.setFont(new java.awt.Font("SansSerif", 0, 12));
        mDescriptionTA.setMargin(new java.awt.Insets(1, 1, 1, 1));
        mDescriptionTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mDescriptionTAKeyTyped(evt);
            }
        });

        mDescriptionScrollPane.setViewportView(mDescriptionTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(mDescriptionScrollPane, gridBagConstraints);

        mWsdlExtPanel.setLayout(new java.awt.GridBagLayout());

        mWsdlExtPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "TITLE_WSDLExt")));
        mNamespaceLBL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mNamespaceLBL.setLabelFor(mNamespaceTF);
        mNamespaceLBL.setText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "LBL_Namespace"));
        mNamespaceLBL.setToolTipText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "TIP_LBL_Namespace"));
        mNamespaceLBL.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mWsdlExtPanel.add(mNamespaceLBL, gridBagConstraints);

        mNamespaceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNamespaceTFActionPerformed(evt);
            }
        });
        mNamespaceTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mNamespaceTFKeyTyped(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mWsdlExtPanel.add(mNamespaceTF, gridBagConstraints);

        mNSPrefixLBL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mNSPrefixLBL.setLabelFor(mNSPrefixTF);
        mNSPrefixLBL.setText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "LBL_NSPrefix"));
        mNSPrefixLBL.setToolTipText(org.openide.util.NbBundle.getMessage(BCDPCompDescriptionVisualPanel.class, "TIP_LBL_NSPrefix"));
        mNSPrefixLBL.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mWsdlExtPanel.add(mNSPrefixLBL, gridBagConstraints);

        mNSPrefixTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNSPrefixTFActionPerformed(evt);
            }
        });
        mNSPrefixTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mNSPrefixTFKeyTyped(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mWsdlExtPanel.add(mNSPrefixTF, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(mWsdlExtPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        add(mDummyLBL, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    private void mNSPrefixTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mNSPrefixTFKeyTyped
        this.mNSPrefixEdited = true;
    }//GEN-LAST:event_mNSPrefixTFKeyTyped
    
    private void mNSPrefixTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNSPrefixTFActionPerformed
        this.mNSPrefixEdited = true;
    }//GEN-LAST:event_mNSPrefixTFActionPerformed
    
    private void mNamespaceTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mNamespaceTFKeyTyped
        this.mNamespaceEdited = true;
    }//GEN-LAST:event_mNamespaceTFKeyTyped
    
    private void mNamespaceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNamespaceTFActionPerformed
        this.mNamespaceEdited = true;
    }//GEN-LAST:event_mNamespaceTFActionPerformed
    
    private void mPackageTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mPackageTFKeyTyped
        // TODO add your handling code here:
        this.mPackageNameEdited = true;
    }//GEN-LAST:event_mPackageTFKeyTyped
    
    private void mDescriptionTAKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_mDescriptionTAKeyTyped
    {//GEN-HEADEREND:event_mDescriptionTAKeyTyped
        // TODO add your handling code here:
        this.mCompDescEdited = true;
    }//GEN-LAST:event_mDescriptionTAKeyTyped
    
    private void mNameTFKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_mNameTFKeyTyped
    {//GEN-HEADEREND:event_mNameTFKeyTyped
        // TODO add your handling code here:
        this.mCompNameEdited = true;
    }//GEN-LAST:event_mNameTFKeyTyped
    
    private void mNameTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mNameTFActionPerformed
    {//GEN-HEADEREND:event_mNameTFActionPerformed
        // TODO add your handling code here:
        this.mCompNameEdited = true;
    }//GEN-LAST:event_mNameTFActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mComponentTypeLBL;
    private javax.swing.JLabel mComponentTypeValueLBL;
    private javax.swing.JLabel mDescriptionLBL;
    private javax.swing.JScrollPane mDescriptionScrollPane;
    private javax.swing.JTextArea mDescriptionTA;
    private javax.swing.JLabel mDummyLBL;
    private javax.swing.JLabel mNSPrefixLBL;
    private javax.swing.JTextField mNSPrefixTF;
    private javax.swing.JLabel mNameLBL;
    private javax.swing.JTextField mNameTF;
    private javax.swing.JLabel mNamespaceLBL;
    private javax.swing.JTextField mNamespaceTF;
    private javax.swing.JLabel mPackageLBL;
    private javax.swing.JTextField mPackageTF;
    private javax.swing.JPanel mWsdlExtPanel;
    // End of variables declaration//GEN-END:variables
    
    private String mEngineTypeValue =  "Service Engine";
    private String mBindingTypeValue =  "Binding Component";
    
    private boolean mValidPackageName = true;
    private boolean mValidComponentName = true;
    
    private boolean mPackageNameEdited = false;
    private boolean mCompNameEdited = false;
    private boolean mCompDescEdited = false;
    
    private boolean mNamespaceEdited = false;
    private boolean mNSPrefixEdited = false;
    
    private String mCompType = DeployPluginWizardModel.SERVICE_ENGINE_COMP_TYPE;
    
    private boolean canUpdateModelFromProjectName() {
        return !(this.mPackageNameEdited && this.mCompNameEdited && this.mCompDescEdited &&
                this.mNamespaceEdited && this.mNSPrefixEdited);
    }
    
    // update the asainfo until user edit the info.
    private void updateModelFromProjectName(DeployPluginWizardModel wizModel) {
        if ( !canUpdateModelFromProjectName()) {
            return;
        }
        String prjName = wizModel.getProjectName();
        String compType = wizModel.getComponentType();
        
        if ( prjName != null && prjName.trim().length() > 0 ) {
            if ( !this.mCompNameEdited ) {
                wizModel.setComponentName(
                        DeployPluginWizardModel.getComponentName(
                        DeployPluginWizardModel.SAMPLE_BC_NAME, compType));
            }
            
            if ( !this.mCompDescEdited ) {
                String compName = wizModel.getComponentName();
                wizModel.setComponentDescription(DeployPluginWizardModel.getComponentDescription(compName, compType));
            }
            
            if ( !this.mPackageNameEdited ) {
                wizModel.setPackageName(DeployPluginWizardModel.getPackageName(prjName, compType));
            }
            
//            BCDeployPluginWizardModel bcWizModel = (BCDeployPluginWizardModel)wizModel;
//            if ( !this.mNamespaceEdited ) {
//            }
//
//            if ( !this.mNSPrefixEdited ) {
//            }
            
        }
    }
    
    private String toComponentTypeValue(String compType) {
        if ( DeployPluginWizardModel.BINDING_COMPONENT_COMP_TYPE.equalsIgnoreCase(compType)) {
            return this.mBindingTypeValue;
        } else {
            return this.mEngineTypeValue;
        }
    }
    
    public void loadFromWizardModel(AbstractWizardModel wizModel) {
        BCDeployPluginWizardModel pluginWizModel = (BCDeployPluginWizardModel)wizModel;
        
        this.mCompType = pluginWizModel.getComponentType();
        
        updateModelFromProjectName(pluginWizModel);
        
        this.mComponentTypeValueLBL.setText(toComponentTypeValue(pluginWizModel.getComponentType()));
        
        String compName = pluginWizModel.getComponentName();
        if ( compName != null ) {
            compName = compName.trim();
        }
        this.mNameTF.setText(compName);
        
        this.mDescriptionTA.setText(pluginWizModel.getComponentDescription());
        String pkgName = pluginWizModel.getPackageName();
        if ( pkgName != null ) {
            pkgName = pkgName.trim();
        }
        this.mPackageTF.setText(pkgName);
        
        this.mNamespaceTF.setText(pluginWizModel.getWSDLExtInfo().getNamespace());
        this.mNSPrefixTF.setText(pluginWizModel.getWSDLExtInfo().getNamespacePrefix());
    }
    
    public void saveToWizardModel(AbstractWizardModel wizModel) {
        BCDeployPluginWizardModel pluginWizModel = (BCDeployPluginWizardModel)wizModel;
        
        String name = this.mNameTF.getText().trim();
        String desc = this.mDescriptionTA.getText();
        String packageName = this.mPackageTF.getText().trim();
        
        String namespace = this.mNamespaceTF.getText().trim();
        String nsPrefix = this.mNSPrefixTF.getText().trim();
        
        pluginWizModel.setComponentName(name);
        pluginWizModel.setComponentDescription(desc);
        pluginWizModel.setPackageName(packageName);
        
        pluginWizModel.getWSDLExtInfo().setNamespace(namespace);
        pluginWizModel.getWSDLExtInfo().setNamespacePrefix(nsPrefix);
    }
    
    public void validateVisualPanel(AbstractWizardModel wizModel) throws org.openide.WizardValidationException {
        // do nothing.
        // check for the valid package name.
    }
    
    public boolean isValidVisualPanel(AbstractWizardModel wizModel) {
        WizardDescriptor wizardDescriptor = wizModel.getWizardDescriptor();
        wizardDescriptor.putProperty( "WizardPanel_errorMessage", "" );
        
        if (!this.mValidPackageName ) {
            wizardDescriptor.putProperty( "WizardPanel_errorMessage", // NOI18N
                    NbBundle.getMessage(BasicJbiComponentDescriptionVisualPanel.class,"ERROR_InvalidPackageName"));
            return false;
        }
        
        if (!this.mValidComponentName) {
            wizardDescriptor.putProperty( "WizardPanel_errorMessage", // NOI18N
                    NbBundle.getMessage(BasicJbiComponentDescriptionVisualPanel.class,"ERROR_InvalidComponentName"));
            return false;
        }
        
        return true;
    }
    
    private boolean isValidPackageName(String pkgName) {
        String trimedPkgName = pkgName.trim();
        if ( trimedPkgName.length() == 0 ) {
            return false; // don't allow root package eventhough it is valid
        }
        
        StringTokenizer tk = new StringTokenizer(trimedPkgName, "."); //NOI18N
        boolean valid = true;
        while (tk.hasMoreTokens()) {
            String token = tk.nextToken();
            if (token.length() == 0 || !Utilities.isJavaIdentifier(token)) {
                valid = false;
                break;
            }
        }
        
        return valid;
    }
    
    private void packageNameChanged() {
        String pkgName = this.mPackageTF.getText();
        this.mValidPackageName = isValidPackageName(pkgName);
        this.getWizardPanel().fireChangeEvent();
    }
    
    private boolean isValidComponentName(String name) {
        // for now, the package name validity is same as the component name validity
        return isValidPackageName(name); // TODO add a common method for the validation of the name, pkg name
    }
    
    private void componentNameChanged() {
        String compName = this.mNameTF.getText();
        this.mValidComponentName = isValidComponentName(compName);
        if ( !this.mCompDescEdited ) {
            this.mDescriptionTA.setText(DeployPluginWizardModel.getComponentDescription(compName, this.mCompType));
        }
        
        if ( !this.mNamespaceEdited ) {
            this.mNamespaceTF.setText(WSDLExtInfo.getNamespace(compName));
        }
        
        if ( !this.mNSPrefixEdited ) {
          this.mNSPrefixTF.setText(WSDLExtInfo.getNamespacePrefix(compName));  
        }
        
        this.getWizardPanel().fireChangeEvent();
    }
    
    private void updateGUIFromProjectNameChange(String prjName) {
        
        if ( !canUpdateModelFromProjectName()) {
            return;
        }
        
        if ( prjName != null && prjName.trim().length() > 0 ) {
//            if ( !this.mCompNameEdited ) {
//                this.mNameTF.setText(DeployPluginWizardModel.getComponentName(prjName, this.mCompType));
//            }
            
            if ( !this.mPackageNameEdited ) {
                this.mPackageTF.setText(DeployPluginWizardModel.getPackageName(prjName, this.mCompType));
            }
        }
        
    }
    
    public void propertyChange(PropertyChangeEvent event) {
        if (ProjectLocationVisualPanel.PROP_PROJECT_NAME.equals(event.getPropertyName())) {
            String newProjectName = (String)event.getNewValue();
            newProjectName = ( newProjectName != null ) ? newProjectName.trim() : "" ;
            updateGUIFromProjectNameChange(newProjectName);
        }
    }
}
