#include "dir/second.idl"
#include <./dir2/./third.idl>

module it{
    module imolinfo{
        module jbi4corba{
            module test{
		module webservice{
                    module generator{
                        module testclasses{
                            module anotherpackage{
                                interface aEchoInOut {
                                    string echo(inout second::second_string msg, in third::third_int msgstr);
                                };
                            };
			};
                    };
                };
            };
        };
    };
};