<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/triggerWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/triggerWSDL" name="triggerWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <wsdl:types/>
    <wsdl:message name="triggerWSDLOperationRequest">
        <wsdl:part name="part1" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="triggerWSDLOperationReply">
        <wsdl:part name="part1" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="triggerWSDLPortType">
        <wsdl:operation name="triggerWSDLOperation">
            <wsdl:input name="input1" message="tns:triggerWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:triggerWSDLOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="triggerWSDLBinding" type="tns:triggerWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="triggerWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/triggerWSDL"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/triggerWSDL"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="triggerWSDLService">
        <wsdl:port name="triggerWSDLPort" binding="tns:triggerWSDLBinding">
            <soap:address location="http://localhost:18181/triggerWSDLService/triggerWSDLPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="triggerWSDLPartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="triggerWSDLPortTypeRole" portType="tns:triggerWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
