<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/SOAPDeleteOraTrigger"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/SOAPDeleteOraTrigger" name="SOAPDeleteOraTrigger" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="SOAPDeleteOraTriggerOperationRequest">
        <part name="part1" type="xsd:int"/>
    </message>
    <message name="SOAPDeleteOraTriggerOperationReply">
        <part name="part1" type="xsd:int"/>
    </message>
    <portType name="SOAPDeleteOraTriggerPortType">
        <wsdl:operation name="SOAPDeleteOraTriggerOperation">
            <wsdl:input name="input1" message="tns:SOAPDeleteOraTriggerOperationRequest"/>
            <wsdl:output name="output1" message="tns:SOAPDeleteOraTriggerOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="SOAPDeleteOraTriggerBinding" type="tns:SOAPDeleteOraTriggerPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SOAPDeleteOraTriggerOperation">
            <soap:operation style="document"/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SOAPDeleteOraTrigger" parts="part1"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SOAPDeleteOraTrigger" parts="part1"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="SOAPDeleteOraTriggerService">
        <wsdl:port name="SOAPDeleteOraTriggerPort" binding="tns:SOAPDeleteOraTriggerBinding">
            <soap:address location="http://localhost:18181/SOAPDeleteOraTriggerService/SOAPDeleteOraTriggerPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="SOAPDeleteOraTriggerPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SOAPDeleteOraTriggerPortTypeRole" portType="tns:SOAPDeleteOraTriggerPortType"/>
    </plnk:partnerLinkType>
</definitions>
