module it{
	module imolinfo{
		module jbi4corba{
			module test{
				module testsharedprovidercomplex{

                                struct  SharedStruct {
                                string            fieldName;
                                string            fieldSName;
                                };

                                 interface EchoShared {

    							SharedStruct echo(in string name,in string sname);
                                   
                                                        };
                         };
                    };
               };
        };
};