<?xml version="1.0" encoding="UTF-8"?>


<wsdl:definitions name="WaitFlowTest"
             targetNamespace="http://www.mycomp.org/WaitFlowTest"
             xmlns:tns="http://www.mycomp.org/WaitFlowTest"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"                          
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns0="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:message name="requestMessage
">
        <wsdl:part name="request" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="responseMessage">
        <wsdl:part name="response" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="MyPortType">
        <wsdl:operation name="WaitFlowOperation">
            <wsdl:input name="inputText" message="tns:requestMessage
"/>
            <wsdl:output name="outputText" message="tns:responseMessage"/>
        </wsdl:operation>
    </wsdl:portType>

        <binding name="SoapBinding" type="tns:MyPortType">
            <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
                <operation name="WaitFlowOperation">
                        <soap:operation style="document"/>
                        <input name="inputText">
                                <soap:body use="literal"/>
                        </input><output name="outputText">
    <soap:body use="literal"/>
</output>
                </operation>
        </binding>

   
         <wsdl:service name="WaitFlowTestService">
		<wsdl:port name="WaitFlowTestPortName" binding="tns:SoapBinding">                    
                     <soap:address location="http://localhost:${HttpDefaultPort}/WaitFlowTest"/>
		</wsdl:port>
        </wsdl:service>

	<plnk:partnerLinkType name="WaitFlowTestPartnerLinkType">
		<plnk:role name="WaitFlowTestProvider" portType="tns:MyPortType"/>
	</plnk:partnerLinkType>

</wsdl:definitions>


 

 

 

 

 
