package it.imolinfo.jbi4corba.test.testprovideruniontypes;


/**
* it/imolinfo/jbi4corba/test/testprovideruniontypes/EchoUnionTypesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/imolaCSV/nokia/open-jbi-components/contrib-imola/corba-bc/integration-test/test-provider-uniontypes/provider-uniontypes-jbi4corba-provider/src/main/resources/UnionTypes.idl
* lunedì 19 gennaio 2009 9.19.47 EET
*/

abstract public class EchoUnionTypesHelper
{
  private static String  _id = "IDL:it/imolinfo/jbi4corba/test/testprovideruniontypes/EchoUnionTypes:1.0";

  public static void insert (org.omg.CORBA.Any a, it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypesHelper.id (), "EchoUnionTypes");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EchoUnionTypesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes)
      return (it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      it.imolinfo.jbi4corba.test.testprovideruniontypes._EchoUnionTypesStub stub = new it.imolinfo.jbi4corba.test.testprovideruniontypes._EchoUnionTypesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes)
      return (it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionTypes)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      it.imolinfo.jbi4corba.test.testprovideruniontypes._EchoUnionTypesStub stub = new it.imolinfo.jbi4corba.test.testprovideruniontypes._EchoUnionTypesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
