package it.imolinfo.jbi4corba.test.testprovideruniontypes;


/**
* it/imolinfo/jbi4corba/test/testprovideruniontypes/EchoUnionExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/imolaCSV/nokia/open-jbi-components/contrib-imola/corba-bc/integration-test/test-provider-uniontypes/provider-uniontypes-jbi4corba-provider/src/main/resources/UnionTypes.idl
* lunedì 19 gennaio 2009 9.19.47 EET
*/

abstract public class EchoUnionExceptionHelper
{
  private static String  _id = "IDL:it/imolinfo/jbi4corba/test/testprovideruniontypes/EchoUnionException:1.0";

  public static void insert (org.omg.CORBA.Any a, it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = it.imolinfo.jbi4corba.test.testprovideruniontypes.ThirdUnionHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "reason",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionExceptionHelper.id (), "EchoUnionException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionException read (org.omg.CORBA.portable.InputStream istream)
  {
    it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionException value = new it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionException ();
    // read and discard the repository ID
    istream.read_string ();
    value.reason = it.imolinfo.jbi4corba.test.testprovideruniontypes.ThirdUnionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, it.imolinfo.jbi4corba.test.testprovideruniontypes.EchoUnionException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    it.imolinfo.jbi4corba.test.testprovideruniontypes.ThirdUnionHelper.write (ostream, value.reason);
  }

}
