<?xml version="1.0" encoding="UTF-8"?>
<definitions name="validatorWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/validatorWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/validatorWSDL" xmlns:ns="http://xml.netbeans.org/schema/validatorSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/validatorWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/validatorSchema" schemaLocation="validatorSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="validateRequest">
        <part name="anyInput" element="ns:PartElement"/>
    </message>
    <message name="validateResponse">
        <part name="validatorOutput" element="ns:validatorOutput"/>
    </message>
    <portType name="validatorWSDLPortType">
        <operation name="validate">
            <input name="input1" message="tns:validateRequest"/>
            <output name="output1" message="tns:validateResponse"/>
        </operation>
    </portType>
    <binding name="validatorWSDLBinding" type="tns:validatorWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="validate">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="validatorWSDLService">
        <port name="validatorWSDLPort" binding="tns:validatorWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/validatorWSDLService/validatorWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="validatorWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="validatorWSDLPortTypeRole" portType="tns:validatorWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
