<?xml version="1.0" encoding="UTF-8"?>
<definitions 
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Wrapper" 
    targetNamespace="http://localhost/BpelCorrelation/Wrapper/"
    xmlns:ns="http://www.ardatis.com/ventouris/TaakService"
    xmlns:ns0="http://www.ardatis.com/ventouris/SeeBeyondService" 
    xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
    xmlns:tns="http://localhost/BpelCorrelation/Wrapper/"
    xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop">
    <import namespace="http://www.ardatis.com/ventouris/SeeBeyondService" location="MultiOp_UserTestCase2.wsdl"/>
    <import namespace="http://www.ardatis.com/ventouris/TaakService" location="TaakService.wsdl"/> 
    <vprop:property name="DossierId" type="xsd:string" /> 
    <vprop:propertyAlias 
      propertyName="tns:DossierId"
      messageType="ns0:SetStartProcessRequest"
      part="SetStartProcessRequest">
      <vprop:query>/SetStartProcessRequest/dossierId</vprop:query>    
    </vprop:propertyAlias>
    <vprop:propertyAlias 
      propertyName="tns:DossierId"
      messageType="ns0:RecoverRequest"
      part="RecoverRequest">
      <vprop:query>/RecoverRequest/insz</vprop:query>    
    </vprop:propertyAlias>
    <vprop:propertyAlias 
      propertyName="tns:DossierId"
      messageType="ns:TaakServiceSEI_createTaakRequest"
      part="parameters">
      <vprop:query>/createTaakRequest/dossierId</vprop:query>    
    </vprop:propertyAlias>
    <plink:partnerLinkType name="setStartProcessPartnerLinkType">
        <plink:role name="setStartProcessRole" portType="ns0:SbynSEI"/>
    </plink:partnerLinkType>
    <plink:partnerLinkType name="recoverPartnerLinkType">
        <plink:role name="recoverRole" portType="ns0:SbynSEI"/>
    </plink:partnerLinkType>
</definitions>
