package it.imolinfo.jbi4corba.test.testprovideroneway;

/**
* it/imolinfo/jbi4corba/test/testprovideroneway/EchoStructHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/EchoOneway.idl
* giovedì 29 novembre 2007 9.14.26 CET
*/

public final class EchoStructHolder implements org.omg.CORBA.portable.Streamable
{
  public it.imolinfo.jbi4corba.test.testprovideroneway.EchoStruct value = null;

  public EchoStructHolder ()
  {
  }

  public EchoStructHolder (it.imolinfo.jbi4corba.test.testprovideroneway.EchoStruct initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = it.imolinfo.jbi4corba.test.testprovideroneway.EchoStructHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    it.imolinfo.jbi4corba.test.testprovideroneway.EchoStructHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return it.imolinfo.jbi4corba.test.testprovideroneway.EchoStructHelper.type ();
  }

}
