<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TroubleTicketWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/TroubleTicketWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/TroubleTicketWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://java.sun.com/products/oss/xml/TroubleTicket/wsdl">
    <import location="TroubleTicket.wsdl" namespace="http://java.sun.com/products/oss/xml/TroubleTicket/wsdl"/>
    <plnk:partnerLinkType name="TroubleTicketWSPortLinkType">
        <plnk:role name="roleTroubleTicket" portType="ns:TroubleTicketWSPort"/>
    </plnk:partnerLinkType>
</definitions>
