<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    name="EchoInOnlyWrapper" 
    targetNamespace="http://enterprise.netbeans.org/bpel/EchoInOnlyWrapper" 
    xmlns:tns="http://enterprise.netbeans.org/bpel/EchoInOnlyWrapper" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:ns1="urn:jbi4corba/test-consumer-inonly">
    
    <import location="EchoInOnly.wsdl" namespace="urn:jbi4corba/test-consumer-inonly"/>
    
    <plnk:partnerLinkType name="echoInOnlyProcess">
        <plnk:role name="echoInOnlyProcess" portType="ns1:EchoInOnlyPortType"/>
    </plnk:partnerLinkType>
</definitions>
