package it.imolinfo.jbi4corba.test.testprovidersimplemult;


/**
* it/imolinfo/jbi4corba/test/testprovidersimplemult/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* mercoledì 19 novembre 2008 17.33.37 CET
*/

public interface EchoOperations 
{
  String echo (String msg);
} // interface EchoOperations
