<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongParamValViewSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongParamValViewRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongParamValViewResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongParamValViewRequest">
    <part name="SelectWrongParamValViewRequestPart" element="tns:SelectWrongParamValViewRequest"/>
  </message>
  <message name="SelectWrongParamValViewResponse">
    <part name="SelectWrongParamValViewResponsePart" element="tns:SelectWrongParamValViewResponse"/>
  </message>
  <portType name="SelectWrongParamValViewSql_sqlsePortType">
    <operation name="SelectWrongParamValView">
      <input name="SelectWrongParamValViewRequest" message="tns:SelectWrongParamValViewRequest"/>
      <output name="SelectWrongParamValViewResponse" message="tns:SelectWrongParamValViewResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongParamValViewSqlBinding" type="tns:SelectWrongParamValViewSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongParamValView">
      <soap:operation/>
      <input name="SelectWrongParamValViewRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongParamValViewResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongParamValViewSql_sqlseService">
    <port name="SelectWrongParamValViewSql_sqlsePort" binding="tns:SelectWrongParamValViewSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongParamValViewSql/SelectWrongParamValViewSql/SelectWrongParamValViewSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongParamValViewSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongParamValViewSql_myrole" portType="tns:SelectWrongParamValViewSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
