<?xml version="1.0" encoding="UTF-8"?>
<definitions name="testPickNoSibling" targetNamespace="http://j2ee.netbeans.org/testPickNoSibling"
    xmlns:tns="http://j2ee.netbeans.org/testPickNoSibling"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/testPickNoSibling"/>
    </types>
    <message name="testPickNoSiblingOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="testPickNoSiblingOperationReply">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="testPickNoSiblingPortType">
        <operation name="testPickNoSiblingOperation">
            <input name="input1" message="tns:testPickNoSiblingOperationRequest"/>
            <output name="output1" message="tns:testPickNoSiblingOperationReply"/>
        </operation>
    </portType>
    <binding name="testPickNoSiblingBinding" type="tns:testPickNoSiblingPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="testPickNoSiblingOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="testPickNoSiblingService">
        <port name="testPickNoSiblingPort" binding="tns:testPickNoSiblingBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/service"/>
        </port>
    </service>
    <plink:partnerLinkType name="testPickNoSiblingPartner">
        <plink:role name="testPickNoSiblingPortTypeRole" portType="tns:testPickNoSiblingPortType"/>
    </plink:partnerLinkType>
</definitions>
