/*
 * @(#)ConfigurationVisualPanel.java        $Revision: 1.2 $ $Date: 2008/11/24 12:47:18 $
 * 
 * Copyright (c) 2008 Milan Fort (http://www.milanfort.com/). All rights reserved.
 * 
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the "License"). You may not use this file except
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at http://www.sun.com/cddl/cddl.html.
 * See the License for the specific language governing permissions and limitations
 * under the License.
 */

package org.openesb.components.rules4jbi.netbeans.wsdl.wizard;

import java.awt.Dimension;
import javax.swing.event.DocumentListener;
import org.openide.util.NbBundle;

/**
 *
 * @author Milan Fort (http://www.milanfort.com/)
 * @version $Revision: 1.2 $ $Date: 2008/11/24 12:47:18 $
 * 
 * @since 0.1
 */
public class ConfigurationVisualPanel extends javax.swing.JPanel {
    
    private static final long serialVersionUID = -2449366228226639442L;
    
    /** Creates new form ConfigurationVisualPanel */
    public ConfigurationVisualPanel() {
        initComponents();
        
        setPreferredSize(new Dimension(
                Constants.PANEL_PREFERRED_SIZE_WIDTH, Constants.PANEL_PREFERRED_SIZE_HEIGHT));
    }
    
    @Override
    public String getName() {
        return NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationPanel.name");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        definitionsLabel = new javax.swing.JLabel();
        definitionsTextField = new javax.swing.JTextField();
        targetNamespaceLabel = new javax.swing.JLabel();
        targetNamespaceTextField = new javax.swing.JTextField();
        portTypeLabel = new javax.swing.JLabel();
        portTypeTextField = new javax.swing.JTextField();
        serviceLabel = new javax.swing.JLabel();
        serviceTextField = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        partnerLinkTypeLabel = new javax.swing.JLabel();
        partnerLinkTypeTextField = new javax.swing.JTextField();
        partnerLinkRoleLabel = new javax.swing.JLabel();
        partnerLinkRoleTextField = new javax.swing.JTextField();

        definitionsLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("org/openesb/components/rules4jbi/netbeans/wsdl/wizard/Bundle").getString("ConfigurationVisualPanel.definitionsLabel.text").charAt(0));
        definitionsLabel.setLabelFor(definitionsTextField);
        definitionsLabel.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.definitionsLabel.text")); // NOI18N

        definitionsTextField.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.definitionsTextField.text")); // NOI18N

        targetNamespaceLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("org/openesb/components/rules4jbi/netbeans/wsdl/wizard/Bundle").getString("ConfigurationVisualPanel.targetNamespaceLabel.text").charAt(0));
        targetNamespaceLabel.setLabelFor(targetNamespaceTextField);
        targetNamespaceLabel.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.targetNamespaceLabel.text")); // NOI18N

        targetNamespaceTextField.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.targetNamespaceTextField.text")); // NOI18N

        portTypeLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("org/openesb/components/rules4jbi/netbeans/wsdl/wizard/Bundle").getString("ConfigurationVisualPanel.portTypeLabel.text").charAt(0));
        portTypeLabel.setLabelFor(portTypeTextField);
        portTypeLabel.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.portTypeLabel.text")); // NOI18N

        portTypeTextField.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.portTypeTextField.text")); // NOI18N

        serviceLabel.setDisplayedMnemonic('S');
        serviceLabel.setLabelFor(serviceTextField);
        serviceLabel.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.serviceLabel.text")); // NOI18N

        serviceTextField.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.serviceTextField.text")); // NOI18N

        portLabel.setDisplayedMnemonic('N');
        portLabel.setLabelFor(portTextField);
        portLabel.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.portLabel.text")); // NOI18N

        portTextField.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.portTextField.text")); // NOI18N

        partnerLinkTypeLabel.setDisplayedMnemonic('L');
        partnerLinkTypeLabel.setLabelFor(partnerLinkTypeTextField);
        partnerLinkTypeLabel.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.partnerLinkTypeLabel.text")); // NOI18N

        partnerLinkTypeTextField.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.partnerLinkTypeTextField.text")); // NOI18N

        partnerLinkRoleLabel.setDisplayedMnemonic('R');
        partnerLinkRoleLabel.setLabelFor(partnerLinkRoleTextField);
        partnerLinkRoleLabel.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.partnerLinkRoleLabel.text")); // NOI18N

        partnerLinkRoleTextField.setText(org.openide.util.NbBundle.getMessage(ConfigurationVisualPanel.class, "ConfigurationVisualPanel.partnerLinkRoleTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partnerLinkTypeLabel)
                    .addComponent(targetNamespaceLabel)
                    .addComponent(definitionsLabel)
                    .addComponent(portTypeLabel)
                    .addComponent(serviceLabel)
                    .addComponent(portLabel)
                    .addComponent(partnerLinkRoleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partnerLinkRoleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(targetNamespaceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(definitionsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(portTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(serviceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(portTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(partnerLinkTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(definitionsLabel)
                    .addComponent(definitionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetNamespaceLabel)
                    .addComponent(targetNamespaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portTypeLabel)
                    .addComponent(portTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceLabel)
                    .addComponent(serviceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partnerLinkTypeLabel)
                    .addComponent(partnerLinkTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partnerLinkRoleLabel)
                    .addComponent(partnerLinkRoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    void addDocumentListener(DocumentListener listener) {
        definitionsTextField.getDocument().addDocumentListener(listener);
        portTextField.getDocument().addDocumentListener(listener);
        portTypeTextField.getDocument().addDocumentListener(listener);
        serviceTextField.getDocument().addDocumentListener(listener);
        targetNamespaceTextField.getDocument().addDocumentListener(listener);
        partnerLinkTypeTextField.getDocument().addDocumentListener(listener);
        partnerLinkRoleTextField.getDocument().addDocumentListener(listener);
    }
    
    String getDefinitionsName() {
        return definitionsTextField.getText();
    }
    
    void setDefinitionsName(String definitionsName) {
        definitionsTextField.setText(definitionsName);
    }
    
    String getTargetNamespace() {
        return targetNamespaceTextField.getText();
    }
    
    void setTargetNamespace(String targetNamespace) {
        targetNamespaceTextField.setText(targetNamespace);
    }
    
    String getPortTypeName() {
        return portTypeTextField.getText();
    }
    
    void setPortTypeName(String portTypeName) {
        portTypeTextField.setText(portTypeName);
    }
    
    String getServiceName() {
        return serviceTextField.getText();
    }
    
    void setServiceName(String serviceName) {
        serviceTextField.setText(serviceName);
    }
    
    String getPortName() {
        return portTextField.getText();
    }
    
    void setPortName(String portName) {
        portTextField.setText(portName);
    }
    
    String getPartnerLinkTypeName() {
        return partnerLinkTypeTextField.getText();
    }
    
    void setPartnerLinkTypeName(String partnerLinkTypeName) {
        partnerLinkTypeTextField.setText(partnerLinkTypeName);
    }

    String getPartnerLinkRoleName() {
        return partnerLinkRoleTextField.getText();
    }
    
    void setPartnerLinkRoleName(String partnerLinkRoleName) {
        partnerLinkRoleTextField.setText(partnerLinkRoleName);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel definitionsLabel;
    private javax.swing.JTextField definitionsTextField;
    private javax.swing.JLabel partnerLinkRoleLabel;
    private javax.swing.JTextField partnerLinkRoleTextField;
    private javax.swing.JLabel partnerLinkTypeLabel;
    private javax.swing.JTextField partnerLinkTypeTextField;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JLabel portTypeLabel;
    private javax.swing.JTextField portTypeTextField;
    private javax.swing.JLabel serviceLabel;
    private javax.swing.JTextField serviceTextField;
    private javax.swing.JLabel targetNamespaceLabel;
    private javax.swing.JTextField targetNamespaceTextField;
    // End of variables declaration//GEN-END:variables
}
