<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ApprovePurchaseWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ApprovePurchaseWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ApprovePurchaseWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="ApprovePurchase_BPEL">
    <import location="ApprovePurchase.wsdl" namespace="ApprovePurchase_BPEL"/>
    <plnk:partnerLinkType name="purchaseOrderFileOutLT">
        <plnk:role name="fileOut" portType="ns:purcharseOrderFileOutPT"/>
    </plnk:partnerLinkType>
</definitions>
