<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectOneParamViewFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectOneParamViewFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectOneParamViewFullQualResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectOneParamViewFullQualRequest">
    <part name="SelectOneParamViewFullQualRequestPart" element="tns:SelectOneParamViewFullQualRequest"/>
  </message>
  <message name="SelectOneParamViewFullQualResponse">
    <part name="SelectOneParamViewFullQualResponsePart" element="tns:SelectOneParamViewFullQualResponse"/>
  </message>
  <portType name="SelectOneParamViewFullQualSql_sqlsePortType">
    <operation name="SelectOneParamViewFullQual">
      <input name="SelectOneParamViewFullQualRequest" message="tns:SelectOneParamViewFullQualRequest"/>
      <output name="SelectOneParamViewFullQualResponse" message="tns:SelectOneParamViewFullQualResponse"/>
    </operation>
  </portType>
  <binding name="SelectOneParamViewFullQualSqlBinding" type="tns:SelectOneParamViewFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectOneParamViewFullQual">
      <soap:operation/>
      <input name="SelectOneParamViewFullQualRequest">
        <soap:body/>
      </input>
      <output name="SelectOneParamViewFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectOneParamViewFullQualSql_sqlseService">
    <port name="SelectOneParamViewFullQualSql_sqlsePort" binding="tns:SelectOneParamViewFullQualSqlBinding">
      <soap:address location="http://localhost:18181/SelectOneParamViewFullQualSql/SelectOneParamViewFullQualSql/SelectOneParamViewFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectOneParamViewFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectOneParamViewFullQualSql_myrole" portType="tns:SelectOneParamViewFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
