<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DeleteWrongColFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="DeleteWrongColFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="DeleteWrongColFullQualResponse">
    <part name="DeleteWrongColFullQualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="DeleteWrongColFullQualRequest">
    <part name="DeleteWrongColFullQualRequestPart" element="tns:DeleteWrongColFullQualRequest"/>
  </message>
  <portType name="DeleteWrongColFullQualSql_sqlsePortType">
    <operation name="DeleteWrongColFullQual">
      <input name="DeleteWrongColFullQualRequest" message="tns:DeleteWrongColFullQualRequest"/>
      <output name="DeleteWrongColFullQualResponse" message="tns:DeleteWrongColFullQualResponse"/>
    </operation>
  </portType>
  <binding name="DeleteWrongColFullQualSqlBinding" type="tns:DeleteWrongColFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="DeleteWrongColFullQual">
      <soap:operation/>
      <input name="DeleteWrongColFullQualRequest">
        <soap:body/>
      </input>
      <output name="DeleteWrongColFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="DeleteWrongColFullQualSql_sqlseService">
    <port name="DeleteWrongColFullQualSql_sqlsePort" binding="tns:DeleteWrongColFullQualSqlBinding">
      <soap:address location="http://localhost:18181/DeleteWrongColFullQualSql/DeleteWrongColFullQualSql/DeleteWrongColFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="DeleteWrongColFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="DeleteWrongColFullQualSql_myrole" portType="tns:DeleteWrongColFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
