<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TstSvc" targetNamespace="http://svc.tst.sun.com/TstSvc/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://svc.tst.sun.com/TstSvc/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="TstSvcOperationRequest">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <message name="TstSvcOperationResponse">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <portType name="TstSvcInterface">
        <operation name="TstSvcOperation">
            <input name="input1" message="tns:TstSvcOperationRequest"/>
            
        </operation>
    </portType>
</definitions>
