<?xml version="1.0" encoding="UTF-8"?>
<definitions name="createtablecapfullqualSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="createtablecapfullqualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="createtablecapfullqualResponse">
    <part name="createtablecapfullqualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="createtablecapfullqualRequest">
    <part name="createtablecapfullqualRequestPart" element="tns:createtablecapfullqualRequest"/>
  </message>
  <portType name="createtablecapfullqualSQL_sqlsePortType">
    <operation name="createtablecapfullqual">
      <input name="createtablecapfullqualRequest" message="tns:createtablecapfullqualRequest"/>
      <output name="createtablecapfullqualResponse" message="tns:createtablecapfullqualResponse"/>
    </operation>
  </portType>
  <binding name="createtablecapfullqualSQLBinding" type="tns:createtablecapfullqualSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="createtablecapfullqual">
      <soap:operation style="document"/>
      <input name="createtablecapfullqualRequest">
        <soap:body use="literal"/>
      </input>
      <output name="createtablecapfullqualResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="createtablecapfullqualSQL_sqlseService">
    <port name="createtablecapfullqualSQL_sqlsePort" binding="tns:createtablecapfullqualSQLBinding">
      <soap:address location="http://localhost:18181/createtablecapfullqualSQL/createtablecapfullqualSQL/createtablecapfullqualSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="createtablecapfullqualSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="createtablecapfullqualSQL_myrole" portType="tns:createtablecapfullqualSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
