<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongViewFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongViewFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongViewFullQualResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongViewFullQualResponse">
    <part name="SelectWrongViewFullQualResponsePart" element="tns:SelectWrongViewFullQualResponse"/>
  </message>
  <message name="SelectWrongViewFullQualRequest">
    <part name="SelectWrongViewFullQualRequestPart" element="tns:SelectWrongViewFullQualRequest"/>
  </message>
  <portType name="SelectWrongViewFullQualSql_sqlsePortType">
    <operation name="SelectWrongViewFullQual">
      <input name="SelectWrongViewFullQualRequest" message="tns:SelectWrongViewFullQualRequest"/>
      <output name="SelectWrongViewFullQualResponse" message="tns:SelectWrongViewFullQualResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongViewFullQualSqlBinding" type="tns:SelectWrongViewFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongViewFullQual">
      <soap:operation/>
      <input name="SelectWrongViewFullQualRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongViewFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongViewFullQualSql_sqlseService">
    <port name="SelectWrongViewFullQualSql_sqlsePort" binding="tns:SelectWrongViewFullQualSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongViewFullQualSql/SelectWrongViewFullQualSql/SelectWrongViewFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongViewFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongViewFullQualSql_myrole" portType="tns:SelectWrongViewFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
