<?xml version="1.0" encoding="UTF-8"?>
<definitions name="UpdateFalseCondSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="UpdateFalseCondRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="UpdateFalseCondResponse">
    <part name="UpdateFalseCondResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="UpdateFalseCondRequest">
    <part name="UpdateFalseCondRequestPart" element="tns:UpdateFalseCondRequest"/>
  </message>
  <portType name="UpdateFalseCondSql_sqlsePortType">
    <operation name="UpdateFalseCond">
      <input name="UpdateFalseCondRequest" message="tns:UpdateFalseCondRequest"/>
      <output name="UpdateFalseCondResponse" message="tns:UpdateFalseCondResponse"/>
    </operation>
  </portType>
  <binding name="UpdateFalseCondSqlBinding" type="tns:UpdateFalseCondSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="UpdateFalseCond">
      <soap:operation/>
      <input name="UpdateFalseCondRequest">
        <soap:body/>
      </input>
      <output name="UpdateFalseCondResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="UpdateFalseCondSql_sqlseService">
    <port name="UpdateFalseCondSql_sqlsePort" binding="tns:UpdateFalseCondSqlBinding">
      <soap:address location="http://localhost:18181/UpdateFalseCondSql/UpdateFalseCondSql/UpdateFalseCondSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="UpdateFalseCondSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="UpdateFalseCondSql_myrole" portType="tns:UpdateFalseCondSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
