<?xml version="1.0" encoding="UTF-8"?>
<definitions name="createtablescnspSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="createtablescnspRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="createtablescnspRequest">
    <part name="createtablescnspRequestPart" element="tns:createtablescnspRequest"/>
  </message>
  <message name="createtablescnspResponse">
    <part name="createtablescnspResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="createtablescnspSQL_sqlsePortType">
    <operation name="createtablescnsp">
      <input name="createtablescnspRequest" message="tns:createtablescnspRequest"/>
      <output name="createtablescnspResponse" message="tns:createtablescnspResponse"/>
    </operation>
  </portType>
  <binding name="createtablescnspSQLBinding" type="tns:createtablescnspSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="createtablescnsp">
      <soap:operation style="document"/>
      <input name="createtablescnspRequest">
        <soap:body use="literal"/>
      </input>
      <output name="createtablescnspResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="createtablescnspSQL_sqlseService">
    <port name="createtablescnspSQL_sqlsePort" binding="tns:createtablescnspSQLBinding">
      <soap:address location="http://localhost:18181/createtablescnspSQL/createtablescnspSQL/createtablescnspSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="createtablescnspSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="createtablescnspSQL_myrole" portType="tns:createtablescnspSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
