<?xml version="1.0" encoding="UTF-8"?>
<definitions name="dropnonexisttabfullqualSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="dropnonexisttabfullqualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="dropnonexisttabfullqualResponse">
    <part name="dropnonexisttabfullqualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="dropnonexisttabfullqualRequest">
    <part name="dropnonexisttabfullqualRequestPart" element="tns:dropnonexisttabfullqualRequest"/>
  </message>
  <portType name="dropnonexisttabfullqualSQL_sqlsePortType">
    <operation name="dropnonexisttabfullqual">
      <input name="dropnonexisttabfullqualRequest" message="tns:dropnonexisttabfullqualRequest"/>
      <output name="dropnonexisttabfullqualResponse" message="tns:dropnonexisttabfullqualResponse"/>
    </operation>
  </portType>
  <binding name="dropnonexisttabfullqualSQLBinding" type="tns:dropnonexisttabfullqualSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="dropnonexisttabfullqual">
      <soap:operation style="document"/>
      <input name="dropnonexisttabfullqualRequest">
        <soap:body use="literal"/>
      </input>
      <output name="dropnonexisttabfullqualResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="dropnonexisttabfullqualSQL_sqlseService">
    <port name="dropnonexisttabfullqualSQL_sqlsePort" binding="tns:dropnonexisttabfullqualSQLBinding">
      <soap:address location="http://localhost:18181/dropnonexisttabfullqualSQL/dropnonexisttabfullqualSQL/dropnonexisttabfullqualSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="dropnonexisttabfullqualSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="dropnonexisttabfullqualSQL_myrole" portType="tns:dropnonexisttabfullqualSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
