package it.imolinfo.jbi4corba.test.testproviderarray;


/**
* it/imolinfo/jbi4corba/test/testproviderarray/ArrayInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoArray.idl
* venerdì 20 febbraio 2009 12.20.53 CET
*/

public interface ArrayInterfaceOperations 
{
  boolean[] echoArrayBoolean (boolean[] e);
  char[] echoArrayChar (char[] e);
  char[] echoArrayWChar (char[] e);
  byte[] echoArrayOctet (byte[] e);
  String[] echoArrayString (String[] e);
  String[] echoArrayWString (String[] e);
  short[] echoArrayShort (short[] e);
  short[] echoArrayUnsignedShort (short[] e);
  int[] echoArrayLong (int[] e);
  int[] echoArrayUnsignedLong (int[] e);
  long[] echoArrayLongLong (long[] e);
  long[] echoArrayUnsignedLongLong (long[] e);
  float[] echoArrayFloat (float[] e);
  double[] echoArrayDouble (double[] e);
  it.imolinfo.jbi4corba.test.testproviderarray.ComplexStruct[] echoArrayComplexStruct (it.imolinfo.jbi4corba.test.testproviderarray.ComplexStruct[] e);
  String[][] echoMatrixString (String[][] e);
} // interface ArrayInterfaceOperations
