<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    name="EchoPrimitivesWrapper" 
    targetNamespace="http://enterprise.netbeans.org/bpel/EchoPrimitivesWrapper" 
    xmlns:tns="http://enterprise.netbeans.org/bpel/EchoPrimitivesWrapper" 
    xmlns:ns="urn:jbi4corba/test-consumer-primitives"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <import location="EchoPrimitives.wsdl" namespace="urn:jbi4corba/test-consumer-primitives"/>
    
    <plnk:partnerLinkType name="echoPrimitivesProcess">
        <plnk:role name="echoPrimitivesProcess" portType="ns:EchoPrimitivesPortType"/>
    </plnk:partnerLinkType>
</definitions>
