<?xml version="1.0" encoding="UTF-8"?>
<definitions name="createtableSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="createtableRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="createtableResponse">
    <part name="createtableResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="createtableRequest">
    <part name="createtableRequestPart" element="tns:createtableRequest"/>
  </message>
  <portType name="createtableSQL_sqlsePortType">
    <operation name="createtable">
      <input name="createtableRequest" message="tns:createtableRequest"/>
      <output name="createtableResponse" message="tns:createtableResponse"/>
    </operation>
  </portType>
  <binding name="createtableSQLBinding" type="tns:createtableSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="createtable">
      <soap:operation style="document"/>
      <input name="createtableRequest">
        <soap:body use="literal"/>
      </input>
      <output name="createtableResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="createtableSQL_sqlseService">
    <port name="createtableSQL_sqlsePort" binding="tns:createtableSQLBinding">
      <soap:address location="http://localhost:18181/createtableSQL/createtableSQL/createtableSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="createtableSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="createtableSQL_myrole" portType="tns:createtableSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
