<?xml version="1.0" encoding="UTF-8"?>
<definitions name="UddiSearchWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/UddiSearchWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/UddiSearchWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:uddi="http://schemas.sun.com/jbi/wsdl-extensions/uddi/">
    <types/>
    <message name="UddiSearchWSDLOperationRequest">
        <part name="businesspart" type="xsd:string"/>
        <part name="servicepart" type="xsd:string"/>
    </message>
    <message name="UddiSearchWSDLOperationReply">
        <part name="part1" type="xsd:anyURI"/>
    </message>
    <portType name="UddiSearchWSDLPortType">
        <wsdl:operation name="UddiSearchWSDLOperation">
            <wsdl:input name="input1" message="tns:UddiSearchWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:UddiSearchWSDLOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="UddiSearchWSDLBinding" type="tns:UddiSearchWSDLPortType">
        <uddi:binding/>
        <wsdl:operation name="UddiSearchWSDLOperation">
            <uddi:operation name="search"/>
            <wsdl:input name="input1">
                <uddi:input businessName="businesspart" serviceName="servicepart"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <uddi:output/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="UddiSearchWSDLService">
        <wsdl:port name="UddiSearchWSDLPort" binding="tns:UddiSearchWSDLBinding">
            <uddi:address publishUri="http://localhost/publish" inquiryUri="http://juddi.com:8080/juddi/inquiry"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="UddiSearchWSDL1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="UddiSearchWSDLPortTypeRole" portType="tns:UddiSearchWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
