<?xml version="1.0" encoding="UTF-8"?>


<wsdl:definitions name="WhileOneActivity"
             targetNamespace="http://www.mycomp.org/DefaultServiceName"
             xmlns:tns="http://www.mycomp.org/DefaultServiceName"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"                          
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns0="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:message name="message1">
        <wsdl:part name="string" type="xsd:string"/>
        <wsdl:part name="counter" type="xsd:int"/>
    </wsdl:message>
    <wsdl:portType name="WhileOneActivityPortType">
        <wsdl:operation name="WhileOneActivityOperation1">
            <wsdl:input name="input1" message="tns:message1"/>
            <wsdl:output name="output1" message="tns:message1"/>
        </wsdl:operation>
    </wsdl:portType>

        <binding name="WhileOneActivitySoapBinding" type="tns:WhileOneActivityPortType">
            <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
                <operation name="WhileOneActivityOperation1">
                <input name="input1">
                     <soap:body/>
                </input><output name="output1">
    <soap:body/>
</output>
                </operation>
        </binding>

   
         <wsdl:service name="WhileOneActivityService">
		<wsdl:port name="WhileOneActivityPortName" binding="tns:WhileOneActivitySoapBinding">                    
                     <soap:address location="http://localhost:${HttpDefaultPort}/WhileOneActivity"/>
		</wsdl:port>
        </wsdl:service>

	<plnk:partnerLinkType name="WhileOneActivityPartnerLinkType">
		<plnk:role name="WhileOneActivityProvider" portType="tns:WhileOneActivityPortType"/>
	</plnk:partnerLinkType>

</wsdl:definitions>


 

 

 

 

 
