<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:MultiDepBpel2-test6TargetNamespace" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MultiDepBpel2-test6Definition" targetNamespace="urn:MultiDepBpel2-test6TargetNamespace">
    <types>
        <xsd:schema xmlns:ns1="urn:MultiDepBpel2-test6TargetNamespace" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:MultiDepBpel2-test6TargetNamespace">
            <xsd:complexType name="MultiDepBpel2-test6Type">
                <xsd:sequence>
                    <xsd:element name="string" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="MultiDepBpel2-test6Message">
        <part name="MultiDepBpel2-test6Part" type="tns:MultiDepBpel2-test6Type"/>
    </message>
    <portType name="MultiDepBpel2-test6PortType">
        <operation name="MultiDepBpel2-test6Operation">
            <input message="tns:MultiDepBpel2-test6Message"/>
            <output message="tns:MultiDepBpel2-test6Message"/>
        </operation>
    </portType>
    <binding name="MultiDepBpel2-test6Binding" type="tns:MultiDepBpel2-test6PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="MultiDepBpel2-test6Operation">
            <soap:operation soapAction="MultiDepBpel2-test6Operation"/>
            <input>
                <soap:body parts="MultiDepBpel2-test6Part" use="literal"/>
            </input>
            <output>
                <soap:body parts="MultiDepBpel2-test6Part" use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="MultiDepBpel2-test6Service">
        <port binding="tns:MultiDepBpel2-test6Binding" name="MultiDepBpel2-test6Port">
            <soap:address location="http://localhost:${HttpDefaultPort}/service/MultiDepBpel2-test6"/>
        </port>
    </service>
    <plnk:partnerLinkType xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="MultiDepBpel2-test6ServiceLinkType">
	<plnk:role name="MultiDepBpel2-test6ServerRole" portType="tns:MultiDepBpel2-test6PortType"/>
   </plnk:partnerLinkType>
</definitions>
