<?xml version="1.0" encoding="utf-8" ?>
<definitions targetNamespace="http://localhost/BpelClient/EjbWebServiceBpelWrapper"
             name="EjbWebServiceBpelWrapper"
             xmlns:tns="http://localhost/BpelClient/EjbWebServiceBpelWrapper"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:ns="urn:EchoEjb/wsdl"
             xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <plink:partnerLinkType name="EjbPartner">
        <plink:role portType="ns:EchoEjbSEI"
                    name="ejbPartnerRole"></plink:role>
    </plink:partnerLinkType>
    <import namespace="urn:EchoEjb/wsdl"
            location="EjbWebService.wsdl"></import>
</definitions>
