<?xml version="1.0" encoding="UTF-8"?>
<definitions name="IOWSDL10" targetNamespace="http://j2ee.netbeans.org/wsdl/IOWSDL10"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://j2ee.netbeans.org/wsdl/IOWSDL10">
    <types/>
    <message name="IOWSDL10OperationRequest">
        <part name="InputPart" type="xsd:string"/>
    </message>
    <message name="IOWSDL10OperationReply">
        <part name="OutputPart" type="xsd:string"/>
    </message>
    <portType name="IOWSDL10PortType">
        <wsdl:operation name="IOWSDL10Operation">
            <wsdl:input name="input1" message="tns:IOWSDL10OperationRequest"/>
            <wsdl:output name="output1" message="tns:IOWSDL10OperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="IOWSDL10Binding" type="tns:IOWSDL10PortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="IOWSDL10Operation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/IOWSDL10"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/IOWSDL10"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="IOWSDL10Service">
        <wsdl:port name="IOWSDL10Port" binding="tns:IOWSDL10Binding">
            <soap:address location="http://localhost:${HttpDefaultPort}/TerminationHandlerBpel/TH_OnAlarmScope/IOWSDL10Service/IOWSDL10Port"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="IOWSDL10Plink">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="IOWSDL10PortTypeRole" portType="tns:IOWSDL10PortType"/>
    </plnk:partnerLinkType>
</definitions>
