<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://enterprise.netbeans.org/bpel/saml/nmPropertiesDefinitions"
    xmlns:tns="http://enterprise.netbeans.org/bpel/saml/nmPropertiesDefinitions"
    xmlns:sxnmp="http://www.sun.com/wsbpel/2.0/process/executable/SUNExtension/NMProperty"
    xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
    xmlns:ns="http://localhost/Synchronous/Synchronous">
    <import location="Synchronous.wsdl" namespace="http://localhost/Synchronous/Synchronous"/>
    <types/>
    <vprop:property name="subject" type="xsd:any"/>
    <vprop:propertyAlias messageType="ns:requestMessage"
        part="inputType"
        propertyName="tns:subject"
        sxnmp:nmProperty="javax.jbi.security.subject"/>
</definitions>
