<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InsertOneRowTableSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="InsertOneRowTableRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="InsertOneRowTableResponse">
    <part name="InsertOneRowTableResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="InsertOneRowTableRequest">
    <part name="InsertOneRowTableRequestPart" element="tns:InsertOneRowTableRequest"/>
  </message>
  <portType name="InsertOneRowTableSql_sqlsePortType">
    <operation name="InsertOneRowTable">
      <input name="InsertOneRowTableRequest" message="tns:InsertOneRowTableRequest"/>
      <output name="InsertOneRowTableResponse" message="tns:InsertOneRowTableResponse"/>
    </operation>
  </portType>
  <binding name="InsertOneRowTableSqlBinding" type="tns:InsertOneRowTableSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="InsertOneRowTable">
      <soap:operation/>
      <input name="InsertOneRowTableRequest">
        <soap:body/>
      </input>
      <output name="InsertOneRowTableResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="InsertOneRowTableSql_sqlseService">
    <port name="InsertOneRowTableSql_sqlsePort" binding="tns:InsertOneRowTableSqlBinding">
      <soap:address location="http://localhost:18181/InsertOneRowTableSql/InsertOneRowTableSql/InsertOneRowTableSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="InsertOneRowTableSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="InsertOneRowTableSql_myrole" portType="tns:InsertOneRowTableSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
