<?xml version="1.0" encoding="UTF-8"?>
<definitions name="triggerReadC" targetNamespace="http://j2ee.netbeans.org/wsdl/JMSOndemand/triggerReadC"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/JMSOndemand/triggerReadC" xmlns:ns="http://xml.netbeans.org/schema/xxx" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/JMSOndemand/triggerReadC">
            <xsd:import namespace="http://xml.netbeans.org/schema/xxx" schemaLocation="xxx.xsd"/>
        </xsd:schema>
    </types>
    <message name="triggerReadCOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="triggerReadCOperationResponse">
        <part name="part1" type="ns:x"/>
    </message>
    <portType name="triggerReadCPortType">
        <operation name="triggerReadCOperation">
            <input name="input1" message="tns:triggerReadCOperationRequest"/>
            <output name="output1" message="tns:triggerReadCOperationResponse"/>
        </operation>
    </portType>
    <binding name="triggerReadCBinding" type="tns:triggerReadCPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="triggerReadCOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/JMSOndemand/triggerReadC"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/JMSOndemand/triggerReadC"/>
            </output>
        </operation>
    </binding>
    <service name="triggerReadCService">
        <port name="triggerReadCPort" binding="tns:triggerReadCBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/triggerReadCService/triggerReadCPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="triggerReadC">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="triggerReadCPortTypeRole" portType="tns:triggerReadCPortType"/>
    </plnk:partnerLinkType>
</definitions>
