<?xml version="1.0" encoding="UTF-8"?>
<definitions name="triggerRead" targetNamespace="http://j2ee.netbeans.org/wsdl/JMSOndemand/triggerRead"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/JMSOndemand/triggerRead" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="triggerReadOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="triggerReadOperationResponse">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="triggerReadPortType">
        <operation name="triggerReadOperation">
            <input name="input1" message="tns:triggerReadOperationRequest"/>
            <output name="output1" message="tns:triggerReadOperationResponse"/>
        </operation>
    </portType>
    <binding name="triggerReadBinding" type="tns:triggerReadPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="triggerReadOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/JMSOndemand/triggerRead"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/JMSOndemand/triggerRead"/>
            </output>
        </operation>
    </binding>
    <service name="triggerReadService">
        <port name="triggerReadPort" binding="tns:triggerReadBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/triggerReadService/triggerReadPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="triggerRead">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="triggerReadPortTypeRole" portType="tns:triggerReadPortType"/>
    </plnk:partnerLinkType>
</definitions>
