<?xml version="1.0" encoding="UTF-8"?>
<definitions name="EmailNotificationHandler" targetNamespace="http://j2ee.netbeans.org/wsdl/EmailNotificationHandler"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/EmailNotificationHandler"
    xmlns:smtp="http://schemas.sun.com/jbi/wsdl-extensions/smtp/">
    <types/>
    <message name="NotificationHandlerOperationRequest">
        <part name="addresses" type="xsd:string"/>
        <part name="subject" type="xsd:string"/>
        <part name="message" type="xsd:string"/>
        <part name="from"  type="xsd:string"/>
    </message>
    <portType name="NotificationHandlerPortType">
        <wsdl:operation name="NotificationHandlerOperation">
            <wsdl:input name="input1" message="tns:NotificationHandlerOperationRequest"/>
        </wsdl:operation>
    </portType>
    <binding name="NotificationHandlerBinding" type="tns:NotificationHandlerPortType">
        <smtp:binding/>
        <operation name="NotificationHandlerOperation">
            <smtp:operation/>
            <input name="input1">
                 <smtp:input message="message" to="addresses" subject="subject" from="from"/>
            </input>
        </operation>
    </binding>    
</definitions>
