<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://finance.fs.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://finance.fs.com/" name="FinancialIndexService" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://finance.fs.com/" 
      schemaLocation="FinancialIndexService.xsd" 
      xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
      xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </xsd:schema>
  </types>
  <message name="getFinancialIndex">
    <part name="parameters" element="tns:getFinancialIndex"/>
  </message>
  <message name="getFinancialIndexResponse">
    <part name="parameters" element="tns:getFinancialIndexResponse"/>
  </message>
  <portType name="FinancialIndex">
    <operation name="getFinancialIndex">
      <input message="tns:getFinancialIndex"/>
      <output message="tns:getFinancialIndexResponse"/>
    </operation>
  </portType>
  <binding name="FinancialIndexPortBinding" type="tns:FinancialIndex">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="getFinancialIndex">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="FinancialIndexService">
    <port name="FinancialIndexPort" binding="tns:FinancialIndexPortBinding">
      <soap:address location="http://localhost:${HttpDefaultPort}/FinancialIndexService/FinancialIndex" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </port>
  </service>
    <plink:partnerLinkType name="FinancialIndexPartnerLinkType">
        <plink:role name="FinancialIndexRole" portType="tns:FinancialIndex"/>
    </plink:partnerLinkType>
</definitions>