<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongParamValSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongParamValRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongParamValResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongParamValResponse">
    <part name="SelectWrongParamValResponsePart" element="tns:SelectWrongParamValResponse"/>
  </message>
  <message name="SelectWrongParamValRequest">
    <part name="SelectWrongParamValRequestPart" element="tns:SelectWrongParamValRequest"/>
  </message>
  <portType name="SelectWrongParamValSql_sqlsePortType">
    <operation name="SelectWrongParamVal">
      <input name="SelectWrongParamValRequest" message="tns:SelectWrongParamValRequest"/>
      <output name="SelectWrongParamValResponse" message="tns:SelectWrongParamValResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongParamValSqlBinding" type="tns:SelectWrongParamValSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongParamVal">
      <soap:operation/>
      <input name="SelectWrongParamValRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongParamValResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongParamValSql_sqlseService">
    <port name="SelectWrongParamValSql_sqlsePort" binding="tns:SelectWrongParamValSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongParamValSql/SelectWrongParamValSql/SelectWrongParamValSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongParamValSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongParamValSql_myrole" portType="tns:SelectWrongParamValSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
