<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/UpdateAllBpel"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/UpdateAllBpel" name="UpdateAllBpel" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/UpdateAllBpel">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="EMPLOYEE.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="UpdateAllBpelOperationRequest">
        <wsdl:part name="part1" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="UpdateAllBpelOperationReply">
        <wsdl:part name="part1" type="xsd:int"/>
    </wsdl:message>
    <wsdl:portType name="UpdateAllBpelPortType">
        <wsdl:operation name="UpdateAllBpelOperation">
            <wsdl:input name="input1" message="tns:UpdateAllBpelOperationRequest"/>
            <wsdl:output name="output1" message="tns:UpdateAllBpelOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="UpdateAllBpelBinding" type="tns:UpdateAllBpelPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="UpdateAllBpelOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/UpdateAllBpel"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/UpdateAllBpel"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="UpdateAllBpelService">
        <wsdl:port name="UpdateAllBpelPort" binding="tns:UpdateAllBpelBinding">
            <soap:address location="http://localhost:18181/UpdateAllBpelService/UpdateAllBpelPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="UpdateAllBpelPartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="UpdateAllBpelPortTypeRole" portType="tns:UpdateAllBpelPortType"/>
    </plnk:partnerLinkType>
</definitions>
