<?xml version="1.0" encoding="UTF-8"?>
<definitions 
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="I18nBasic" targetNamespace="http://localhost/I18nBpel/I18nBasic" xmlns:tns="http://localhost/I18nBpel/I18nBasic" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <message name="message1">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="portType1">
        <operation name="operation1">
            <input name="input1" message="tns:message1"/>
            <output name="output1" message="tns:message1"/>
        </operation>
    </portType>
    <binding name="binding1" type="tns:portType1">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="operation1">
        <input name="input1">
          <soap:body/>
        </input><output name="output1">
    <soap:body/>
</output>
        </operation>
    </binding>
    <service name="service1">
        <port name="port1" binding="tns:binding1">
            <soap:address location="http://localhost:18181/i18n_basic"/>
        </port>
    </service>
    <plink:partnerLinkType name="partnerlinktype1">
        <plink:role name="partnerlinktyperole1" portType="tns:portType1"/>
    </plink:partnerLinkType>
</definitions>
