<definitions name="JDBCInsertInOut" targetNamespace="http://j2ee.netbeans.org/wsdl/jseTxnPropTst/JDBCInsertInOut"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:jms="http://schemas.sun.com/jbi/wsdl-extensions/jms/" xmlns:tns="http://j2ee.netbeans.org/wsdl/jseTxnPropTst/JDBCInsertInOut" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="JMSInputMessage">
        <part name="part1" type="xsd:string"/>
    </message> 
    <message name="JMSOutputMessage">
        <part name="part1" type="xsd:string"/>
    </message>        
    <portType name="JMSPortType">
        <operation name="JMSOperation">
            <input name="input1" message="tns:JMSInputMessage"/>
            <output name="output1" message="tns:JMSOutputMessage"/>
        </operation>
    </portType>
    <binding name="JMSBinding" type="tns:JMSPortType">
        <jms:binding/>
        <operation name="JMSOperation">
            <jms:operation destination="POJOInOutQueue" destinationType="Queue" transaction="XATransaction" concurrencyMode="cc" maxConcurrentConsumers="1" redeliveryHandling="3:delete"/>
            <input name="input1">
                <jms:message messageType="TextMessage" textPart="part1"/>
            </input>
            <output name="output1">
                <jms:message messageType="TextMessage" textPart="part1"/>
            </output>
        </operation>
    </binding>
    <service name="JMSService">
        <port name="JDBCInsertInOut_Port" binding="tns:JMSBinding">
            <jms:address connectionURL="lookup://jms/tx/jmq1">
                <jms:jmsjcaOptions><![CDATA[]]></jms:jmsjcaOptions>
            </jms:address>
        </port>
    </service>
    <plnk:partnerLinkType name="JDBCInsertInOut">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="JMSPortTypeRole" portType="tns:JMSPortType"/>
    </plnk:partnerLinkType>
</definitions>

