<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ReliableMessaging_BasicService" targetNamespace="http://wsittest.jbi.sun.com/" xmlns:tns="http://wsittest.jbi.sun.com/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
<xsd:import namespace="http://wsittest.jbi.sun.com/" schemaLocation="http://localhost:12100/WSITTestApp-sun-http-binding/WSITTestBPEL/ReliableMessaging_Basic.xsd"/>
</xsd:schema>
  </types>
  <message name="echoResponse">
    <part name="parameters" element="tns:echoResponse">
    </part>
  </message>
  <message name="echo">
    <part name="parameters" element="tns:echo">
    </part>
  </message>
  <portType name="ReliableMessaging_Basic">
    <operation name="echo">
      <input message="tns:echo">
    </input>
      <output message="tns:echoResponse">
    </output>
    </operation>
  </portType>
  <binding name="ReliableMessaging_BasicPortBinding" type="tns:ReliableMessaging_Basic">
    <wsp:PolicyReference URI="#ReliableMessaging_BasicPortBindingPolicy"/>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="echo">
      <soap:operation soapAction="echo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ReliableMessaging_BasicService">
    <port name="ReliableMessaging_BasicPort" binding="tns:ReliableMessaging_BasicPortBinding">
      <soap:address location="http://WORKSTATION:12100/WSITTestServices/ReliableMessaging_BasicService"/>
    </port>
  </service>
    <wsp:UsingPolicy/>
    <wsp:Policy wsu:Id="ReliableMessaging_BasicPortBindingPolicy">
<wsp:ExactlyOne>
<wsp:All>
<ns1:RMAssertion xmlns:ns1="http://schemas.xmlsoap.org/ws/2005/02/rm/policy"/>
<ns2:UsingAddressing xmlns:ns2="http://www.w3.org/2006/05/addressing/wsdl"/>
</wsp:All>
</wsp:ExactlyOne>
</wsp:Policy>
    <plnk:partnerLinkType name="ReliableMessaging_BasicLinkType">
        <plnk:role name="ReliableMessaging_BasicRole" portType="tns:ReliableMessaging_Basic"/>
    </plnk:partnerLinkType>
</definitions>
