package it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany;


/**
* it/imolinfo/jbi4corba/test/webservice/generator/echocomplex/typedefany/EchoComplexTypeDefAnyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoTypeDefAny.idl
* mercoledì 10 febbraio 2010 15.46.41 CET
*/


//==================================================
public interface EchoComplexTypeDefAnyOperations 
{
  org.omg.CORBA.Any echo (org.omg.CORBA.Any msg);
  String echoinout (org.omg.CORBA.AnyHolder msg);
} // interface EchoComplexTypeDefAnyOperations
