package it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany;


/**
* it/imolinfo/jbi4corba/test/webservice/generator/echocomplex/typedefany/myValueTypeOfValueTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoTypeDefAny.idl
* mercoledì 10 febbraio 2010 15.46.41 CET
*/

abstract public class myValueTypeOfValueTypeHelper
{
  private static String  _id = "IDL:it/imolinfo/jbi4corba/test/webservice/generator/echocomplex/typedefany/myValueTypeOfValueType:1.0";

  public static void insert (org.omg.CORBA.Any a, it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany.ValueTypeOfValueType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany.ValueTypeOfValueType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany.ValueTypeOfValueTypeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany.myValueTypeOfValueTypeHelper.id (), "myValueTypeOfValueType", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany.ValueTypeOfValueType read (org.omg.CORBA.portable.InputStream istream)
  {
    it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany.ValueTypeOfValueType value = null;
    value = it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany.ValueTypeOfValueTypeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany.ValueTypeOfValueType value)
  {
    it.imolinfo.jbi4corba.test.webservice.generator.echocomplex.typedefany.ValueTypeOfValueTypeHelper.write (ostream, value);
  }

}
