CREATE TABLE PERSON (
    SSN VARCHAR(60) NOT NULL,
    FIRST_NAME VARCHAR(60),
    LAST_NAME VARCHAR(60),
    STREET VARCHAR(60),
    CITY VARCHAR(60),
    ZIPCODE VARCHAR(60),
    STATE VARCHAR(60),
    PRIMARY KEY (SSN)
)
