<?xml version="1.0" encoding="UTF-8"?>
<definitions name="NewPOJOProvider" targetNamespace="http://tst.pojo.sun.com/EchoNM2NM/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tst.pojo.sun.com/EchoNM2NM/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="EchoNM2NMOperationRequest">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <message name="EchoNM2NMOperationResponse">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <portType name="EchoNM2NMInterface">
        <operation name="EchoNM2NMOperation">
            <input name="input1" message="tns:EchoNM2NMOperationRequest"/>
            <output name="output1" message="tns:EchoNM2NMOperationResponse"/>
        </operation>
    </portType>
</definitions>
