<?xml version="1.0" encoding="UTF-8"?>
<definitions name="NewPOJOProvider" targetNamespace="http://tst.pojo.sun.com/EchoString2String/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tst.pojo.sun.com/EchoString2String/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="EchoString2StringOperationRequest">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <message name="EchoString2StringOperationResponse">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <portType name="EchoString2StringInterface">
        <operation name="EchoString2StringOperation">
            <input name="input1" message="tns:EchoString2StringOperationRequest"/>
            <output name="output1" message="tns:EchoString2StringOperationResponse"/>
        </operation>
    </portType>
</definitions>
