<?xml version="1.0" encoding="UTF-8"?>
<definitions name="NewPOJOProvider" targetNamespace="http://tst.pojo.sun.com/EchoSource2Source/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tst.pojo.sun.com/EchoSource2Source/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="EchoSource2SourceOperationRequest">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <message name="EchoSource2SourceOperationResponse">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <portType name="EchoSource2SourceInterface">
        <operation name="EchoSource2SourceOperation">
            <input name="input1" message="tns:EchoSource2SourceOperationRequest"/>
            <output name="output1" message="tns:EchoSource2SourceOperationResponse"/>
        </operation>
    </portType>
</definitions>
