<?xml version="1.0" encoding="UTF-8"?>


<wsdl:definitions name="IfFlow"
             targetNamespace="http://www.mycomp.org/DefaultServiceName"
             xmlns:tns="http://www.mycomp.org/DefaultServiceName"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"                          
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns0="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:message name="message1">
        <wsdl:part name="ifflowbranch1" type="xsd:string"/>
        <wsdl:part name="ifflowbranch2" type="xsd:string"/>
        <wsdl:part name="elseifflowbranch1" type="xsd:string"/>
        <wsdl:part name="elseifflowbranch2" type="xsd:string"/>
        <wsdl:part name="elseflowbranch1" type="xsd:string"/>
        <wsdl:part name="elseflowbranch2" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="IfFlowPortType">
        <wsdl:operation name="IfFlowOperation">
            <wsdl:input name="input1" message="tns:message1"/>
            <wsdl:output name="output1" message="tns:message1"/>
        </wsdl:operation>
    </wsdl:portType>

        <binding name="IfFlowSoapBinding" type="tns:IfFlowPortType">
            <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
                <operation name="IfFlowOperation">
                <input name="input1">
                     <soap:body/>
                </input><output name="output1">
    <soap:body/>
</output>
                </operation>
        </binding>

   
         <wsdl:service name="IfFlowService">
		<wsdl:port name="IfFlowPortName" binding="tns:IfFlowSoapBinding">                    
                     <soap:address location="http://localhost:${HttpDefaultPort}/IfFlow"/>
		</wsdl:port>
        </wsdl:service>

	<plnk:partnerLinkType name="IfFlowPartnerLinkType">
		<plnk:role name="IfFlowProvider" portType="tns:IfFlowPortType"/>
	</plnk:partnerLinkType>

</wsdl:definitions>


 

 

 

 

 
