//IDL
module it{
module imolinfo{
module jbi4corba{
module test{
module testproviderarray{

  // struct
  struct ComplexStruct {
    boolean            fieldBoolean;
    char               fieldChar;
    wchar              fieldWChar;

    // http://jira.codehaus.org/browse/XFIRE-462
    octet              fieldOctet;

    string             fieldString;
    wstring            fieldWString;
    short              fieldShort;
    unsigned short     fieldUnsignedShort;
    long               fieldLong;
    unsigned long      fieldUnsignedLong;
    long long          fieldLongLong;
    unsigned long long fieldUnsignedLongLong;
    float              fieldFloat;
    double             fieldDouble;

    // UNSUPPORTED
    // The fixed IDL type is not supported by idlj
    // http://java.sun.com/j2se/1.4.2/docs/guide/rmi-iiop/toJavaPortableUG.html
    //fixed              fieldFixed;
  };


	typedef ComplexStruct ArrayComplexStruct[2];


  typedef boolean            ArrayBoolean[2];
  typedef char               ArrayChar[2];
  typedef wchar              ArrayWChar[2];
  typedef octet              ArrayOctet[3];
  typedef string             ArrayString[2];
  typedef wstring            ArrayWString[2];
  typedef short              ArrayShort[2];
  typedef unsigned short     ArrayUnsignedShort[2];
  typedef long               ArrayLong[2];
  typedef unsigned long      ArrayUnsignedLong[2];
  typedef long long          ArrayLongLong[2];
  typedef unsigned long long ArrayUnsignedLongLong[2];
  typedef float              ArrayFloat[2];
  typedef double             ArrayDouble[2];

  typedef string             MatrixString[2][2];

  interface ArrayInterface {

    ArrayBoolean          echoArrayBoolean(in ArrayBoolean e);
    ArrayChar             echoArrayChar(in ArrayChar e);
    ArrayWChar            echoArrayWChar(in ArrayWChar e);
    ArrayOctet            echoArrayOctet(in ArrayOctet e);
    ArrayString           echoArrayString(in ArrayString e);
    ArrayWString          echoArrayWString(in ArrayWString e);
    ArrayShort            echoArrayShort(in ArrayShort e);
    ArrayUnsignedShort    echoArrayUnsignedShort(in ArrayUnsignedShort e);
    ArrayLong             echoArrayLong(in ArrayLong e);
    ArrayUnsignedLong     echoArrayUnsignedLong(in ArrayUnsignedLong e);
    ArrayLongLong         echoArrayLongLong(in ArrayLongLong e);
    ArrayUnsignedLongLong echoArrayUnsignedLongLong(in ArrayUnsignedLongLong e);
    ArrayFloat            echoArrayFloat(in ArrayFloat e);
    ArrayDouble           echoArrayDouble(in ArrayDouble e);

		ArrayComplexStruct    echoArrayComplexStruct(in ArrayComplexStruct e);

		MatrixString          echoMatrixString(in MatrixString e);
  };

};
};
};
};
};
