<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="EchoInOnly" targetNamespace="urn:jbi4corba/test-consumer-inonly" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:jbi4corba/test-consumer-inonly" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:jbi4corba/test-consumer-inonly" xmlns:tns="urn:jbi4corba/test-consumer-inonly" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="echoInOnlyOperation">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" name="arg0" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="echoInOnlyOperation">
    <wsdl:part name="parameters" element="tns:echoInOnlyOperation">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="EchoInOnlyPortType">
    <wsdl:operation name="echoInOnlyOperation">
      <wsdl:input name="echoInOnlyOperation" message="tns:echoInOnlyOperation">
    </wsdl:input>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EchoInOnlyCorbaBinding" type="tns:EchoInOnlyPortType">

    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="echoInOnlyOperation">
      <soap:operation/>
      <wsdl:input name="echoInOnlyOperation">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EchoInOnly">
    <wsdl:port name="EchoInOnlyCorbaPort" binding="tns:EchoInOnlyCorbaBinding">

      <soap:address location="http://localhost:8192/Service/test-consumer-inonly/"/>
    </wsdl:port>
  </wsdl:service>
<plnk:partnerLinkType name="EchoInOnly">
<plnk:role name="EchoInOnlyPortTypeRole" portType="tns:EchoInOnlyPortType"/>
</plnk:partnerLinkType>
</wsdl:definitions>
