//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 12:45:30 AM IST 
//


package com.sun.jbi.hl7bc.extservice.ack.hl7v26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CNE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CNE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v2xml}CNE.1" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}CNE.2" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}CNE.3" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}CNE.4" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}CNE.5" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}CNE.6" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}CNE.7" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}CNE.8" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}CNE.9" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CNE", propOrder = {
    "cne1",
    "cne2",
    "cne3",
    "cne4",
    "cne5",
    "cne6",
    "cne7",
    "cne8",
    "cne9"
})
@XmlSeeAlso({
    OSP1CONTENT.class,
    MSA6CONTENT.class,
    UVC1CONTENT.class,
    OCD1CONTENT.class
})
public class CNE {

    @XmlElement(name = "CNE.1")
    protected CNE1CONTENT cne1;
    @XmlElement(name = "CNE.2")
    protected CNE2CONTENT cne2;
    @XmlElement(name = "CNE.3")
    protected CNE3CONTENT cne3;
    @XmlElement(name = "CNE.4")
    protected CNE4CONTENT cne4;
    @XmlElement(name = "CNE.5")
    protected CNE5CONTENT cne5;
    @XmlElement(name = "CNE.6")
    protected CNE6CONTENT cne6;
    @XmlElement(name = "CNE.7")
    protected CNE7CONTENT cne7;
    @XmlElement(name = "CNE.8")
    protected CNE8CONTENT cne8;
    @XmlElement(name = "CNE.9")
    protected CNE9CONTENT cne9;

    /**
     * Gets the value of the cne1 property.
     * 
     * @return
     *     possible object is
     *     {@link CNE1CONTENT }
     *     
     */
    public CNE1CONTENT getCNE1() {
        return cne1;
    }

    /**
     * Sets the value of the cne1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNE1CONTENT }
     *     
     */
    public void setCNE1(CNE1CONTENT value) {
        this.cne1 = value;
    }

    /**
     * Gets the value of the cne2 property.
     * 
     * @return
     *     possible object is
     *     {@link CNE2CONTENT }
     *     
     */
    public CNE2CONTENT getCNE2() {
        return cne2;
    }

    /**
     * Sets the value of the cne2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNE2CONTENT }
     *     
     */
    public void setCNE2(CNE2CONTENT value) {
        this.cne2 = value;
    }

    /**
     * Gets the value of the cne3 property.
     * 
     * @return
     *     possible object is
     *     {@link CNE3CONTENT }
     *     
     */
    public CNE3CONTENT getCNE3() {
        return cne3;
    }

    /**
     * Sets the value of the cne3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNE3CONTENT }
     *     
     */
    public void setCNE3(CNE3CONTENT value) {
        this.cne3 = value;
    }

    /**
     * Gets the value of the cne4 property.
     * 
     * @return
     *     possible object is
     *     {@link CNE4CONTENT }
     *     
     */
    public CNE4CONTENT getCNE4() {
        return cne4;
    }

    /**
     * Sets the value of the cne4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNE4CONTENT }
     *     
     */
    public void setCNE4(CNE4CONTENT value) {
        this.cne4 = value;
    }

    /**
     * Gets the value of the cne5 property.
     * 
     * @return
     *     possible object is
     *     {@link CNE5CONTENT }
     *     
     */
    public CNE5CONTENT getCNE5() {
        return cne5;
    }

    /**
     * Sets the value of the cne5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNE5CONTENT }
     *     
     */
    public void setCNE5(CNE5CONTENT value) {
        this.cne5 = value;
    }

    /**
     * Gets the value of the cne6 property.
     * 
     * @return
     *     possible object is
     *     {@link CNE6CONTENT }
     *     
     */
    public CNE6CONTENT getCNE6() {
        return cne6;
    }

    /**
     * Sets the value of the cne6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNE6CONTENT }
     *     
     */
    public void setCNE6(CNE6CONTENT value) {
        this.cne6 = value;
    }

    /**
     * Gets the value of the cne7 property.
     * 
     * @return
     *     possible object is
     *     {@link CNE7CONTENT }
     *     
     */
    public CNE7CONTENT getCNE7() {
        return cne7;
    }

    /**
     * Sets the value of the cne7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNE7CONTENT }
     *     
     */
    public void setCNE7(CNE7CONTENT value) {
        this.cne7 = value;
    }

    /**
     * Gets the value of the cne8 property.
     * 
     * @return
     *     possible object is
     *     {@link CNE8CONTENT }
     *     
     */
    public CNE8CONTENT getCNE8() {
        return cne8;
    }

    /**
     * Sets the value of the cne8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNE8CONTENT }
     *     
     */
    public void setCNE8(CNE8CONTENT value) {
        this.cne8 = value;
    }

    /**
     * Gets the value of the cne9 property.
     * 
     * @return
     *     possible object is
     *     {@link CNE9CONTENT }
     *     
     */
    public CNE9CONTENT getCNE9() {
        return cne9;
    }

    /**
     * Sets the value of the cne9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNE9CONTENT }
     *     
     */
    public void setCNE9(CNE9CONTENT value) {
        this.cne9 = value;
    }

}
