//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 12:45:30 AM IST 
//


package com.sun.jbi.hl7bc.extservice.ack.hl7v26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DLN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DLN">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v2xml}DLN.1" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}DLN.2" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}DLN.3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DLN", propOrder = {
    "dln1",
    "dln2",
    "dln3"
})
public class DLN {

    @XmlElement(name = "DLN.1")
    protected DLN1CONTENT dln1;
    @XmlElement(name = "DLN.2")
    protected DLN2CONTENT dln2;
    @XmlElement(name = "DLN.3")
    protected DLN3CONTENT dln3;

    /**
     * Gets the value of the dln1 property.
     * 
     * @return
     *     possible object is
     *     {@link DLN1CONTENT }
     *     
     */
    public DLN1CONTENT getDLN1() {
        return dln1;
    }

    /**
     * Sets the value of the dln1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DLN1CONTENT }
     *     
     */
    public void setDLN1(DLN1CONTENT value) {
        this.dln1 = value;
    }

    /**
     * Gets the value of the dln2 property.
     * 
     * @return
     *     possible object is
     *     {@link DLN2CONTENT }
     *     
     */
    public DLN2CONTENT getDLN2() {
        return dln2;
    }

    /**
     * Sets the value of the dln2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DLN2CONTENT }
     *     
     */
    public void setDLN2(DLN2CONTENT value) {
        this.dln2 = value;
    }

    /**
     * Gets the value of the dln3 property.
     * 
     * @return
     *     possible object is
     *     {@link DLN3CONTENT }
     *     
     */
    public DLN3CONTENT getDLN3() {
        return dln3;
    }

    /**
     * Sets the value of the dln3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DLN3CONTENT }
     *     
     */
    public void setDLN3(DLN3CONTENT value) {
        this.dln3 = value;
    }

}
