//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 12:45:30 AM IST 
//


package com.sun.jbi.hl7bc.extservice.ack.hl7v26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PIP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PIP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v2xml}PIP.1" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}PIP.2" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}PIP.3" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}PIP.4" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}PIP.5" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PIP", propOrder = {
    "pip1",
    "pip2",
    "pip3",
    "pip4",
    "pip5"
})
public class PIP {

    @XmlElement(name = "PIP.1")
    protected PIP1CONTENT pip1;
    @XmlElement(name = "PIP.2")
    protected PIP2CONTENT pip2;
    @XmlElement(name = "PIP.3")
    protected PIP3CONTENT pip3;
    @XmlElement(name = "PIP.4")
    protected PIP4CONTENT pip4;
    @XmlElement(name = "PIP.5")
    protected PIP5CONTENT pip5;

    /**
     * Gets the value of the pip1 property.
     * 
     * @return
     *     possible object is
     *     {@link PIP1CONTENT }
     *     
     */
    public PIP1CONTENT getPIP1() {
        return pip1;
    }

    /**
     * Sets the value of the pip1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIP1CONTENT }
     *     
     */
    public void setPIP1(PIP1CONTENT value) {
        this.pip1 = value;
    }

    /**
     * Gets the value of the pip2 property.
     * 
     * @return
     *     possible object is
     *     {@link PIP2CONTENT }
     *     
     */
    public PIP2CONTENT getPIP2() {
        return pip2;
    }

    /**
     * Sets the value of the pip2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIP2CONTENT }
     *     
     */
    public void setPIP2(PIP2CONTENT value) {
        this.pip2 = value;
    }

    /**
     * Gets the value of the pip3 property.
     * 
     * @return
     *     possible object is
     *     {@link PIP3CONTENT }
     *     
     */
    public PIP3CONTENT getPIP3() {
        return pip3;
    }

    /**
     * Sets the value of the pip3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIP3CONTENT }
     *     
     */
    public void setPIP3(PIP3CONTENT value) {
        this.pip3 = value;
    }

    /**
     * Gets the value of the pip4 property.
     * 
     * @return
     *     possible object is
     *     {@link PIP4CONTENT }
     *     
     */
    public PIP4CONTENT getPIP4() {
        return pip4;
    }

    /**
     * Sets the value of the pip4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIP4CONTENT }
     *     
     */
    public void setPIP4(PIP4CONTENT value) {
        this.pip4 = value;
    }

    /**
     * Gets the value of the pip5 property.
     * 
     * @return
     *     possible object is
     *     {@link PIP5CONTENT }
     *     
     */
    public PIP5CONTENT getPIP5() {
        return pip5;
    }

    /**
     * Sets the value of the pip5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIP5CONTENT }
     *     
     */
    public void setPIP5(PIP5CONTENT value) {
        this.pip5 = value;
    }

}
