//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 12:45:30 AM IST 
//


package com.sun.jbi.hl7bc.extservice.ack.hl7v26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RI">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v2xml}RI.1" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}RI.2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RI", propOrder = {
    "ri1",
    "ri2"
})
@XmlSeeAlso({
    TQ2CONTENT.class
})
public class RI {

    @XmlElement(name = "RI.1")
    protected RI1CONTENT ri1;
    @XmlElement(name = "RI.2")
    protected RI2CONTENT ri2;

    /**
     * Gets the value of the ri1 property.
     * 
     * @return
     *     possible object is
     *     {@link RI1CONTENT }
     *     
     */
    public RI1CONTENT getRI1() {
        return ri1;
    }

    /**
     * Sets the value of the ri1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RI1CONTENT }
     *     
     */
    public void setRI1(RI1CONTENT value) {
        this.ri1 = value;
    }

    /**
     * Gets the value of the ri2 property.
     * 
     * @return
     *     possible object is
     *     {@link RI2CONTENT }
     *     
     */
    public RI2CONTENT getRI2() {
        return ri2;
    }

    /**
     * Sets the value of the ri2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RI2CONTENT }
     *     
     */
    public void setRI2(RI2CONTENT value) {
        this.ri2 = value;
    }

}
