//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 12:45:30 AM IST 
//


package com.sun.jbi.hl7bc.extservice.ack.hl7v26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v2xml}RP.1" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}RP.2" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}RP.3" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}RP.4" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RP", propOrder = {
    "rp1",
    "rp2",
    "rp3",
    "rp4"
})
public class RP {

    @XmlElement(name = "RP.1")
    protected RP1CONTENT rp1;
    @XmlElement(name = "RP.2")
    protected RP2CONTENT rp2;
    @XmlElement(name = "RP.3")
    protected RP3CONTENT rp3;
    @XmlElement(name = "RP.4")
    protected RP4CONTENT rp4;

    /**
     * Gets the value of the rp1 property.
     * 
     * @return
     *     possible object is
     *     {@link RP1CONTENT }
     *     
     */
    public RP1CONTENT getRP1() {
        return rp1;
    }

    /**
     * Sets the value of the rp1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RP1CONTENT }
     *     
     */
    public void setRP1(RP1CONTENT value) {
        this.rp1 = value;
    }

    /**
     * Gets the value of the rp2 property.
     * 
     * @return
     *     possible object is
     *     {@link RP2CONTENT }
     *     
     */
    public RP2CONTENT getRP2() {
        return rp2;
    }

    /**
     * Sets the value of the rp2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RP2CONTENT }
     *     
     */
    public void setRP2(RP2CONTENT value) {
        this.rp2 = value;
    }

    /**
     * Gets the value of the rp3 property.
     * 
     * @return
     *     possible object is
     *     {@link RP3CONTENT }
     *     
     */
    public RP3CONTENT getRP3() {
        return rp3;
    }

    /**
     * Sets the value of the rp3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RP3CONTENT }
     *     
     */
    public void setRP3(RP3CONTENT value) {
        this.rp3 = value;
    }

    /**
     * Gets the value of the rp4 property.
     * 
     * @return
     *     possible object is
     *     {@link RP4CONTENT }
     *     
     */
    public RP4CONTENT getRP4() {
        return rp4;
    }

    /**
     * Sets the value of the rp4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RP4CONTENT }
     *     
     */
    public void setRP4(RP4CONTENT value) {
        this.rp4 = value;
    }

}
