//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 12:45:30 AM IST 
//


package com.sun.jbi.hl7bc.extservice.ack.hl7v26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SAD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SAD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v2xml}SAD.1" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}SAD.2" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}SAD.3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SAD", propOrder = {
    "sad1",
    "sad2",
    "sad3"
})
@XmlSeeAlso({
    XAD1CONTENT.class
})
public class SAD {

    @XmlElement(name = "SAD.1")
    protected SAD1CONTENT sad1;
    @XmlElement(name = "SAD.2")
    protected SAD2CONTENT sad2;
    @XmlElement(name = "SAD.3")
    protected SAD3CONTENT sad3;

    /**
     * Gets the value of the sad1 property.
     * 
     * @return
     *     possible object is
     *     {@link SAD1CONTENT }
     *     
     */
    public SAD1CONTENT getSAD1() {
        return sad1;
    }

    /**
     * Sets the value of the sad1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAD1CONTENT }
     *     
     */
    public void setSAD1(SAD1CONTENT value) {
        this.sad1 = value;
    }

    /**
     * Gets the value of the sad2 property.
     * 
     * @return
     *     possible object is
     *     {@link SAD2CONTENT }
     *     
     */
    public SAD2CONTENT getSAD2() {
        return sad2;
    }

    /**
     * Sets the value of the sad2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAD2CONTENT }
     *     
     */
    public void setSAD2(SAD2CONTENT value) {
        this.sad2 = value;
    }

    /**
     * Gets the value of the sad3 property.
     * 
     * @return
     *     possible object is
     *     {@link SAD3CONTENT }
     *     
     */
    public SAD3CONTENT getSAD3() {
        return sad3;
    }

    /**
     * Sets the value of the sad3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAD3CONTENT }
     *     
     */
    public void setSAD3(SAD3CONTENT value) {
        this.sad3 = value;
    }

}
