//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 12:45:30 AM IST 
//


package com.sun.jbi.hl7bc.extservice.ack.hl7v26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for UAC.CONTENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UAC.CONTENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v2xml}UAC.1"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}UAC.2"/>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UAC.CONTENT", propOrder = {
    "uac1",
    "uac2",
    "any"
})
public class UACCONTENT {

    @XmlElement(name = "UAC.1", required = true)
    protected UAC1CONTENT uac1;
    @XmlElement(name = "UAC.2", required = true)
    protected UAC2CONTENT uac2;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the uac1 property.
     * 
     * @return
     *     possible object is
     *     {@link UAC1CONTENT }
     *     
     */
    public UAC1CONTENT getUAC1() {
        return uac1;
    }

    /**
     * Sets the value of the uac1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link UAC1CONTENT }
     *     
     */
    public void setUAC1(UAC1CONTENT value) {
        this.uac1 = value;
    }

    /**
     * Gets the value of the uac2 property.
     * 
     * @return
     *     possible object is
     *     {@link UAC2CONTENT }
     *     
     */
    public UAC2CONTENT getUAC2() {
        return uac2;
    }

    /**
     * Sets the value of the uac2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link UAC2CONTENT }
     *     
     */
    public void setUAC2(UAC2CONTENT value) {
        this.uac2 = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
