//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 12:45:30 AM IST 
//


package com.sun.jbi.hl7bc.extservice.ack.hl7v26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VR">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v2xml}VR.1" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}VR.2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VR", propOrder = {
    "vr1",
    "vr2"
})
public class VR {

    @XmlElement(name = "VR.1")
    protected VR1CONTENT vr1;
    @XmlElement(name = "VR.2")
    protected VR2CONTENT vr2;

    /**
     * Gets the value of the vr1 property.
     * 
     * @return
     *     possible object is
     *     {@link VR1CONTENT }
     *     
     */
    public VR1CONTENT getVR1() {
        return vr1;
    }

    /**
     * Sets the value of the vr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link VR1CONTENT }
     *     
     */
    public void setVR1(VR1CONTENT value) {
        this.vr1 = value;
    }

    /**
     * Gets the value of the vr2 property.
     * 
     * @return
     *     possible object is
     *     {@link VR2CONTENT }
     *     
     */
    public VR2CONTENT getVR2() {
        return vr2;
    }

    /**
     * Sets the value of the vr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link VR2CONTENT }
     *     
     */
    public void setVR2(VR2CONTENT value) {
        this.vr2 = value;
    }

}
