<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AlterEmptyTableSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="AlterEmptyTableRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="AlterEmptyTableResponse">
    <part name="AlterEmptyTableResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="AlterEmptyTableRequest">
    <part name="AlterEmptyTableRequestPart" element="tns:AlterEmptyTableRequest"/>
  </message>
  <portType name="AlterEmptyTableSql_sqlsePortType">
    <operation name="AlterEmptyTable">
      <input name="AlterEmptyTableRequest" message="tns:AlterEmptyTableRequest"/>
      <output name="AlterEmptyTableResponse" message="tns:AlterEmptyTableResponse"/>
    </operation>
  </portType>
  <binding name="AlterEmptyTableSqlBinding" type="tns:AlterEmptyTableSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="AlterEmptyTable">
      <soap:operation/>
      <input name="AlterEmptyTableRequest">
        <soap:body/>
      </input>
      <output name="AlterEmptyTableResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="AlterEmptyTableSql_sqlseService">
    <port name="AlterEmptyTableSql_sqlsePort" binding="tns:AlterEmptyTableSqlBinding">
      <soap:address location="http://localhost:18181/AlterEmptyTableSql/AlterEmptyTableSql/AlterEmptyTableSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="AlterEmptyTableSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="AlterEmptyTableSql_myrole" portType="tns:AlterEmptyTableSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
