<definitions targetNamespace="http://stc.com/xsddatatype_simpleTypes1" name="xsddatatype_simpleTypes1" xmlns:tns="http://stc.com/xsddatatype_simpleTypes1" xmlns:slnk1="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns0="http://stc.com/xsddatatype_simpleTypes1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/">
    <types>
        <xsd:schema targetNamespace="http://stc.com/xsddatatype_simpleTypes1" elementFormDefault="qualified" xmlns:tns="http://stc.com/xsddatatype_simpleTypes1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/">
            <xsd:element name="Comment" type="xsd:string"/>
        </xsd:schema>
    </types>
    <message name="xsddatatype_simpleTypes1">
        <part name="part" element="tns:Comment"/>
    </message>
    <portType name="xsddatatype_simpleTypes1">
        <operation name="xsddatatype_simpleTypes1">
            <input message="tns:xsddatatype_simpleTypes1"/>
            <output message="tns:xsddatatype_simpleTypes1"/>
        </operation>
    </portType>
    <binding name="Binding" type="tns:xsddatatype_simpleTypes1">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="xsddatatype_simpleTypes1">
            <soap:operation soapAction="xsddatatype_simpleTypes1"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="xsddatatype_simpleTypes1Service">
        <port name="port" binding="tns:Binding">
            <soap:address location="http://localhost:12010/xsddatatype_simpleTypes1"/>
        </port>
    </service>
    <plnk:partnerLinkType name="SLT" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plnk:role name="server" portType="tns:xsddatatype_simpleTypes1"/>
    </plnk:partnerLinkType>
</definitions>
