<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongParamViewFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongParamViewFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongParamViewFullQualResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongParamViewFullQualResponse">
    <part name="SelectWrongParamViewFullQualResponsePart" element="tns:SelectWrongParamViewFullQualResponse"/>
  </message>
  <message name="SelectWrongParamViewFullQualRequest">
    <part name="SelectWrongParamViewFullQualRequestPart" element="tns:SelectWrongParamViewFullQualRequest"/>
  </message>
  <portType name="SelectWrongParamViewFullQualSql_sqlsePortType">
    <operation name="SelectWrongParamViewFullQual">
      <input name="SelectWrongParamViewFullQualRequest" message="tns:SelectWrongParamViewFullQualRequest"/>
      <output name="SelectWrongParamViewFullQualResponse" message="tns:SelectWrongParamViewFullQualResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongParamViewFullQualSqlBinding" type="tns:SelectWrongParamViewFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongParamViewFullQual">
      <soap:operation/>
      <input name="SelectWrongParamViewFullQualRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongParamViewFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongParamViewFullQualSql_sqlseService">
    <port name="SelectWrongParamViewFullQualSql_sqlsePort" binding="tns:SelectWrongParamViewFullQualSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongParamViewFullQualSql/SelectWrongParamViewFullQualSql/SelectWrongParamViewFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongParamViewFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongParamViewFullQualSql_myrole" portType="tns:SelectWrongParamViewFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
