<?xml version="1.0" encoding="windows-1252"?>
<definitions name="calcPOTotalValue" targetNamespace="http://j2ee.netbeans.org/wsdl/InOutService/calcPOTotalValue"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://j2ee.netbeans.org/wsdl/InOutService/calcPOTotalValue"
    xmlns:ns="http://xml.netbeans.org/schema/POSchema"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/InOutService/calcPOTotalValue">
            <xsd:import namespace="http://xml.netbeans.org/schema/POSchema" schemaLocation="POSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="poMsg">
        <part name="part1" element="ns:order"/>
    </message>
    <portType name="callbackCalcTotalValuePO">
        <operation name="getPO">
            <input name="input1" message="tns:poMsg"/>
        </operation>
    </portType>
</definitions>
