-- Drop the tables and the indexes. Note that you need to be connected using the same
-- username/password to do this.
DROP INDEX ENGINECORRIDINDEX ON ENGINECORRELATION;
DROP INDEX STATESTATUSINDEX ON STATE;
DROP INDEX STATEENGINEIDINDEX ON STATE;
DROP INDEX CRMPINDEX ON CRMP;
DROP INDEX ENGINELASTUT ON ENGINE;
DROP INDEX CRMPREPLYVARINDEX ON CRMP;
DROP INDEX VARIABLEFKEY ON VARIABLE;
DROP INDEX VARIABLEATTACHMENTFKEY ON VARIABLEATTACHMENT;
DROP INDEX FOREACHFKEY ON FOREACH;
DROP INDEX INSTCORRFKEY ON INSTANCECORRELATION;
DROP INDEX LCPFKEY ON LASTCHECKPOINT;
DROP INDEX SCOPEFKEY ON SCOPE;
DROP INDEX CRMPFKEY ON CRMP;
DROP INDEX SIMPLEVARFKEY ON SIMPLEVARIABLE;
DROP INDEX PARTNERLINKFKEY ON PARTNERLINK;
DROP INDEX NMPROPERTYFKEY ON NMPROPERTY;
DROP INDEX NMSIMPLEPROPERTYFKEY ON NMSIMPLEPROPERTY;

DROP TABLE CRMP;
DROP TABLE SCOPE;
DROP TABLE LASTCHECKPOINT;
DROP TABLE ENGINECORRELATION;
DROP TABLE INSTANCECORRELATION;
DROP TABLE FOREACH;
DROP TABLE VARIABLE;
DROP TABLE SIMPLEVARIABLE;
DROP TABLE NMPROPERTY;
DROP TABLE NMSIMPLEPROPERTY;
DROP TABLE VARIABLEATTACHMENT;
DROP TABLE WAITINGIMA;
DROP TABLE EVENTHANDLER;
DROP TABLE STATE;
DROP TABLE ENGINE;
DROP TABLE PARTNERLINK;
DROP TABLE OUTSTANDINGMSGEX;
