<?xml version="1.0" encoding="UTF-8"?>
<definitions name="createtablescnuSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="createtablescnuRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="createtablescnuResponse">
    <part name="createtablescnuResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="createtablescnuRequest">
    <part name="createtablescnuRequestPart" element="tns:createtablescnuRequest"/>
  </message>
  <portType name="createtablescnuSQL_sqlsePortType">
    <operation name="createtablescnu">
      <input name="createtablescnuRequest" message="tns:createtablescnuRequest"/>
      <output name="createtablescnuResponse" message="tns:createtablescnuResponse"/>
    </operation>
  </portType>
  <binding name="createtablescnuSQLBinding" type="tns:createtablescnuSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="createtablescnu">
      <soap:operation style="document"/>
      <input name="createtablescnuRequest">
        <soap:body use="literal"/>
      </input>
      <output name="createtablescnuResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="createtablescnuSQL_sqlseService">
    <port name="createtablescnuSQL_sqlsePort" binding="tns:createtablescnuSQLBinding">
      <soap:address location="http://localhost:18181/createtablescnuSQL/createtablescnuSQL/createtablescnuSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="createtablescnuSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="createtablescnuSQL_myrole" portType="tns:createtablescnuSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
