<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns="http://j2ee.netbeans.org/wsdl/OnAlarmWSDL" xmlns:ns1="http://j2ee.netbeans.org/wsdl/subBP" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties">
    <import namespace="http://j2ee.netbeans.org/wsdl/OnAlarmWSDL" location="OnAlarmWSDL.wsdl"/>
    <import namespace="http://j2ee.netbeans.org/wsdl/subBP" location="subBP.wsdl"/>
    <vprop:property name="wzrd_prop_string_string" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string" messageType="ns:OnAlarmWSDLOperationRequest" part="ID"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string" messageType="ns1:callbackOperationRequest" part="CallBackcorrelatingVal"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string" messageType="ns1:subBPOperationRequest" part="part1"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string" messageType="ns1:correlatesubBPOperationRequest" part="part1"/>
</definitions>
