<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/helloPartner"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/helloPartner" name="helloPartner" xmlns:ns="http://xml.netbeans.org/schema/hello" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/helloPartner">
            <xsd:import namespace="http://xml.netbeans.org/schema/hello" schemaLocation="hello.xsd"/>
        </xsd:schema>
    </types>
    <message name="helloPartnerOperationRequest">
        <part name="part1" element="ns:input"/>
    </message>
    <message name="helloPartnerOperationReply">
        <part name="part1" element="ns:output"/>
    </message>
    <portType name="helloPartnerPortType">
        <wsdl:operation name="helloPartnerOperation">
            <wsdl:input name="input1" message="tns:helloPartnerOperationRequest"/>
            <wsdl:output name="output1" message="tns:helloPartnerOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="helloPartnerBinding" type="tns:helloPartnerPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="helloPartnerOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    
    
    <service name="helloPartnerService">
        <wsdl:port name="helloPartnerPort" binding="tns:helloPartnerBinding">
            <soap:address location="http://localhost:8080/HelloWS/helloPartnerService" /> 
        </wsdl:port>
    </service>
    
    <plnk:partnerLinkType name="helloPartnerPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="helloPartnerPortTypeRole" portType="tns:helloPartnerPortType"/>
    </plnk:partnerLinkType>
</definitions>
