<?xml version="1.0" encoding="UTF-8"?>
<definitions name="IOWSDL3" targetNamespace="http://j2ee.netbeans.org/wsdl/IOWSDL3"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://j2ee.netbeans.org/wsdl/IOWSDL3">
    <types/>
    <message name="IOWSDL3OperationRequest">
        <part name="InputPart" type="xsd:string"/>
    </message>
    <message name="IOWSDL3OperationReply">
        <part name="OutputPart" type="xsd:string"/>
    </message>
    <portType name="IOWSDL3PortType">
        <wsdl:operation name="IOWSDL3Operation">
            <wsdl:input name="input1" message="tns:IOWSDL3OperationRequest"/>
            <wsdl:output name="output1" message="tns:IOWSDL3OperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="IOWSDL3Binding" type="tns:IOWSDL3PortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="IOWSDL3Operation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/IOWSDL3"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/IOWSDL3"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="IOWSDL3Service">
        <wsdl:port name="IOWSDL3Port" binding="tns:IOWSDL3Binding">
            <soap:address location="http://localhost:18181/TermainationHandlerBpel/ExitInFH/IOWSDL3Service/IOWSDL3Port"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="IOWSDL3Plink">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="IOWSDL3PortTypeRole" portType="tns:IOWSDL3PortType"/>
    </plnk:partnerLinkType>
</definitions>
