<definitions targetNamespace="urn:TestReceivechild3TargetNamespace"
             name="TestReceivechild3Definition"
             xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:tns="urn:TestReceivechild3TargetNamespace"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:slnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <plnk:partnerLinkType name="TestReceivechild3ServiceLinkType"
                          xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plnk:role name="TestReceivechild3ServerRole"
                   portType="tns:TestReceivechild3PortType"></plnk:role>
    </plnk:partnerLinkType>
    <vprop:property type="xsd:string"
                   name="TestReceivechild3Prop"></vprop:property>
    <vprop:propertyAlias part="TestReceivechild3Part"
                        propertyName="tns:TestReceivechild3Prop"
                        messageType="tns:TestReceivechild3Message">
        <vprop:query>string</vprop:query>
    </vprop:propertyAlias>
    <types>
        <xsd:schema targetNamespace="urn:TestReceivechild3TargetNamespace"
                    attributeFormDefault="unqualified"
                    elementFormDefault="qualified"
                    xmlns:tns="urn:TestReceivechild3TargetNamespace"
                    xmlns:ns1="urn:TestReceivechild3TargetNamespace"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    xmlns="http://schemas.xmlsoap.org/wsdl/"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
            
                    <xsd:complexType name="TestReceivechild3Type">
                <xsd:sequence>
                    <xsd:element type="xsd:string"
                                 name="string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="TestReceivechild3Message">
        <part name="TestReceivechild3Part"
              type="tns:TestReceivechild3Type"></part>
    </message>
    <portType name="TestReceivechild3PortType">
        <operation name="TestReceivechild3Operation">
            <input message="tns:TestReceivechild3Message"></input>
            <output message="tns:TestReceivechild3Message"></output>
        </operation>
    </portType>
    <binding name="TestReceivechild3Binding"
             type="tns:TestReceivechild3PortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="TestReceivechild3Operation">
            <soap:operation soapAction="TestReceivechild3Operation"/>
            <input>
                <soap:body parts="TestReceivechild3Part"
                           use="literal"/>
            </input>
            <output>
                <soap:body parts="TestReceivechild3Part"
                           use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="TestReceivechild3Service">
        <port name="TestReceivechild3Port"
              binding="tns:TestReceivechild3Binding">
            <soap:address location="http://localhost:12100/service/TestReceivechild3"/>
        </port>
    </service>
</definitions>
