<definitions targetNamespace="urn:TestReceivechild2TargetNamespace"
             name="TestReceivechild2Definition"
             xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:tns="urn:TestReceivechild2TargetNamespace"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:slnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <plnk:partnerLinkType name="TestReceivechild2ServiceLinkType"
                          xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plnk:role name="TestReceivechild2ServerRole"
                   portType="tns:TestReceivechild2PortType"></plnk:role>
    </plnk:partnerLinkType>
    <vprop:property type="xsd:string"
                   name="TestReceivechild2Prop"></vprop:property>
    <vprop:propertyAlias part="TestReceivechild2Part"
                        propertyName="tns:TestReceivechild2Prop"
                        messageType="tns:TestReceivechild2Message">
        <vprop:query>string</vprop:query>
    </vprop:propertyAlias>
    <types>
        <xsd:schema targetNamespace="urn:TestReceivechild2TargetNamespace"
                    attributeFormDefault="unqualified"
                    elementFormDefault="qualified"
                    xmlns:tns="urn:TestReceivechild2TargetNamespace"
                    xmlns:ns1="urn:TestReceivechild2TargetNamespace"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    xmlns="http://schemas.xmlsoap.org/wsdl/"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
            
                    <xsd:complexType name="TestReceivechild2Type">
                <xsd:sequence>
                    <xsd:element type="xsd:string"
                                 name="string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="TestReceivechild2Message">
        <part name="TestReceivechild2Part"
              type="tns:TestReceivechild2Type"></part>
    </message>
    <portType name="TestReceivechild2PortType">
        <operation name="TestReceivechild2Operation">
            <input message="tns:TestReceivechild2Message"></input>
            <output message="tns:TestReceivechild2Message"></output>
        </operation>
    </portType>
    <binding name="TestReceivechild2Binding"
             type="tns:TestReceivechild2PortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="TestReceivechild2Operation">
            <soap:operation soapAction="TestReceivechild2Operation"/>
            <input>
                <soap:body parts="TestReceivechild2Part"
                           use="literal"/>
            </input>
            <output>
                <soap:body parts="TestReceivechild2Part"
                           use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="TestReceivechild2Service">
        <port name="TestReceivechild2Port"
              binding="tns:TestReceivechild2Binding">
            <soap:address location="http://localhost:12100/service/TestReceivechild2"/>
        </port>
    </service>
</definitions>
