<definitions targetNamespace="urn:TestReceivechild4TargetNamespace"
             name="TestReceivechild4Definition"
             xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:tns="urn:TestReceivechild4TargetNamespace"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:slnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <plnk:partnerLinkType name="TestReceivechild4ServiceLinkType"
                          xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plnk:role name="TestReceivechild4ServerRole"
                   portType="tns:TestReceivechild4PortType"></plnk:role>
    </plnk:partnerLinkType>
    <vprop:property type="xsd:string"
                   name="TestReceivechild4Prop"></vprop:property>
    <vprop:propertyAlias part="TestReceivechild4Part"
                        propertyName="tns:TestReceivechild4Prop"
                        messageType="tns:TestReceivechild4Message">
        <vprop:query>string</vprop:query>
    </vprop:propertyAlias>
    <types>
        <xsd:schema targetNamespace="urn:TestReceivechild4TargetNamespace"
                    attributeFormDefault="unqualified"
                    elementFormDefault="qualified"
                    xmlns:tns="urn:TestReceivechild4TargetNamespace"
                    xmlns:ns1="urn:TestReceivechild4TargetNamespace"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    xmlns="http://schemas.xmlsoap.org/wsdl/"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
            
                    <xsd:complexType name="TestReceivechild4Type">
                <xsd:sequence>
                    <xsd:element type="xsd:string"
                                 name="string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="TestReceivechild4Message">
        <part name="TestReceivechild4Part"
              type="tns:TestReceivechild4Type"></part>
    </message>
    <portType name="TestReceivechild4PortType">
        <operation name="TestReceivechild4Operation">
            <input message="tns:TestReceivechild4Message"></input>
            <output message="tns:TestReceivechild4Message"></output>
        </operation>
    </portType>
    <binding name="TestReceivechild4Binding"
             type="tns:TestReceivechild4PortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="TestReceivechild4Operation">
            <soap:operation soapAction="TestReceivechild4Operation"/>
            <input>
                <soap:body parts="TestReceivechild4Part"
                           use="literal"/>
            </input>
            <output>
                <soap:body parts="TestReceivechild4Part"
                           use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="TestReceivechild4Service">
        <port name="TestReceivechild4Port"
              binding="tns:TestReceivechild4Binding">
            <soap:address location="http://localhost:12100/service/TestReceivechild4"/>
        </port>
    </service>
</definitions>
