<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectMultiParamFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectMultiParamFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectMultiParamFullQualResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectMultiParamFullQualRequest">
    <part name="SelectMultiParamFullQualRequestPart" element="tns:SelectMultiParamFullQualRequest"/>
  </message>
  <message name="SelectMultiParamFullQualResponse">
    <part name="SelectMultiParamFullQualResponsePart" element="tns:SelectMultiParamFullQualResponse"/>
  </message>
  <portType name="SelectMultiParamFullQualSql_sqlsePortType">
    <operation name="SelectMultiParamFullQual">
      <input name="SelectMultiParamFullQualRequest" message="tns:SelectMultiParamFullQualRequest"/>
      <output name="SelectMultiParamFullQualResponse" message="tns:SelectMultiParamFullQualResponse"/>
    </operation>
  </portType>
  <binding name="SelectMultiParamFullQualSqlBinding" type="tns:SelectMultiParamFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectMultiParamFullQual">
      <soap:operation/>
      <input name="SelectMultiParamFullQualRequest">
        <soap:body/>
      </input>
      <output name="SelectMultiParamFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectMultiParamFullQualSql_sqlseService">
    <port name="SelectMultiParamFullQualSql_sqlsePort" binding="tns:SelectMultiParamFullQualSqlBinding">
      <soap:address location="http://localhost:18181/SelectMultiParamFullQualSql/SelectMultiParamFullQualSql/SelectMultiParamFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectMultiParamFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectMultiParamFullQualSql_myrole" portType="tns:SelectMultiParamFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
