<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DeleteWrongTabSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="DeleteWrongTabRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="DeleteWrongTabRequest">
    <part name="DeleteWrongTabRequestPart" element="tns:DeleteWrongTabRequest"/>
  </message>
  <message name="DeleteWrongTabResponse">
    <part name="DeleteWrongTabResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="DeleteWrongTabSql_sqlsePortType">
    <operation name="DeleteWrongTab">
      <input name="DeleteWrongTabRequest" message="tns:DeleteWrongTabRequest"/>
      <output name="DeleteWrongTabResponse" message="tns:DeleteWrongTabResponse"/>
    </operation>
  </portType>
  <binding name="DeleteWrongTabSqlBinding" type="tns:DeleteWrongTabSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="DeleteWrongTab">
      <soap:operation/>
      <input name="DeleteWrongTabRequest">
        <soap:body/>
      </input>
      <output name="DeleteWrongTabResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="DeleteWrongTabSql_sqlseService">
    <port name="DeleteWrongTabSql_sqlsePort" binding="tns:DeleteWrongTabSqlBinding">
      <soap:address location="http://localhost:18181/DeleteWrongTabSql/DeleteWrongTabSql/DeleteWrongTabSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="DeleteWrongTabSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="DeleteWrongTabSql_myrole" portType="tns:DeleteWrongTabSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
