<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Catalog2_WSDefinition" targetNamespace="http://j2ee.netbeans.org/wsdl/Catalog2_WSDefinition"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Catalog2_WSDefinition" xmlns:ns0="http://xml.netbeans.org/schema/Catalog2_Schema" xmlns:ns="http://xml.netbeans.org/schema/Catalog1_Schema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://j2ee.netbeans.org/wsdl/Catalog1_WSDefinition">
    <import location="CatalogBpel1/Catalog1_WSDefinition.wsdl" namespace="http://j2ee.netbeans.org/wsdl/Catalog1_WSDefinition"/>
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/Catalog2_WSDefinition">
            <xsd:import namespace="http://xml.netbeans.org/schema/Catalog1_Schema" schemaLocation="CatalogBpel1/Catalog1_Schema.xsd"/>
            <xsd:import namespace="http://xml.netbeans.org/schema/Catalog2_Schema" schemaLocation="Catalog2_Schema.xsd"/>
        </xsd:schema>
    </types>
    <message name="Catalog2_WSDefinitionOperationRequest">
        <part name="part1" element="ns:catalog1_root"/>
    </message>
    <message name="Catalog2_WSDefinitionOperationResponse">
        <part name="part1" element="ns0:catalog2_use_catalog1_type"/>
    </message>
    <portType name="Catalog2_WSDefinitionPortType">
        <operation name="Catalog2_WSDefinitionOperation">
            <input name="input1" message="tns:Catalog2_WSDefinitionOperationRequest"/>
            <output name="output1" message="tns:Catalog2_WSDefinitionOperationResponse"/>
        </operation>
        <operation name="Catalog2_OperationUseCatalog1Messages">
            <input name="input2" message="ns1:Catalog1_WSDefinitionOperationRequest"/>
            <output name="output2" message="ns1:Catalog1_WSDefinitionOperationResponse"/>
        </operation>
    </portType>
    <binding name="Catalog2_WSDefinitionBinding" type="tns:Catalog2_WSDefinitionPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Catalog2_WSDefinitionOperation">
            <soap:operation soapAction="operation1" style="document"/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="Catalog2_OperationUseCatalog1Messages">
            <soap:operation soapAction="operation2" style="document"/>
            <input name="input2">
                <soap:body/>
            </input>
            <output name="output2">
                <soap:body/>
            </output>
        </operation>
    </binding>
    <service name="Catalog2_WSDefinitionService">
        <port name="Catalog2_WSDefinitionPort" binding="tns:Catalog2_WSDefinitionBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/Catalog2_WSDefinitionService/Catalog2_WSDefinitionPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="Catalog2_WSDefinition">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="Catalog2_WSDefinitionPortTypeRole" portType="tns:Catalog2_WSDefinitionPortType"/>
    </plnk:partnerLinkType>
</definitions>
