<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongParamNameViewSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongParamNameViewRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongParamNameViewResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongParamNameViewRequest">
    <part name="SelectWrongParamNameViewRequestPart" element="tns:SelectWrongParamNameViewRequest"/>
  </message>
  <message name="SelectWrongParamNameViewResponse">
    <part name="SelectWrongParamNameViewResponsePart" element="tns:SelectWrongParamNameViewResponse"/>
  </message>
  <portType name="SelectWrongParamNameViewSql_sqlsePortType">
    <operation name="SelectWrongParamNameView">
      <input name="SelectWrongParamNameViewRequest" message="tns:SelectWrongParamNameViewRequest"/>
      <output name="SelectWrongParamNameViewResponse" message="tns:SelectWrongParamNameViewResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongParamNameViewSqlBinding" type="tns:SelectWrongParamNameViewSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongParamNameView">
      <soap:operation/>
      <input name="SelectWrongParamNameViewRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongParamNameViewResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongParamNameViewSql_sqlseService">
    <port name="SelectWrongParamNameViewSql_sqlsePort" binding="tns:SelectWrongParamNameViewSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongParamNameViewSql/SelectWrongParamNameViewSql/SelectWrongParamNameViewSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongParamNameViewSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongParamNameViewSql_myrole" portType="tns:SelectWrongParamNameViewSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
