<?xml version="1.0" encoding="UTF-8"?>


<wsdl:definitions name="echo_1"
             targetNamespace="http://www.mycomp.org/echo/echo_1"
             xmlns:tns="http://www.mycomp.org/echo/echo_1"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"                          
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="urn:GoogleSearch">
    <wsdl:import location="api.google.com/GoogleSearch.wsdl" namespace="urn:GoogleSearch"/>

    <wsdl:message name="message_0">
        <wsdl:part name="part_0" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="MyPortType">
        <wsdl:operation name="operation_0">
            <wsdl:input name="input" message="tns:message_0"/>
            <wsdl:output name="output" message="tns:message_0"/>
        </wsdl:operation>
    </wsdl:portType>

        <binding name="SoapBinding" type="tns:MyPortType">
            <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
                <operation name="operation_0">
                <input name="input">
                     <soap:body/>
                </input><output name="output">
    <soap:body/>
</output>
                </operation>
        </binding>

   
         <wsdl:service name="echo_1Service">
		<wsdl:port name="echo_1PortName" binding="tns:SoapBinding">                    
                     <soap:address location="http://localhost:18181/echo/echo_1"/>
		</wsdl:port>
        </wsdl:service>

	<plnk:partnerLinkType name="echo_1PartnerLinkType">
		<plnk:role name="echo_1Provider" 
			portType="tns:MyPortType">
		</plnk:role>
	</plnk:partnerLinkType>

</wsdl:definitions>


 

 

 

 

 
