<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Echo" targetNamespace="it.imolinfo.jbi4corba.test.webservice.generator.echoComplex" xmlns:imolacorba="uri://schemas.imola.it/jbi/wsdl-extensions/corba/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="it.imolinfo.jbi4corba.test.webservice.generator.echoComplex" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="it.imolinfo.jbi4corba.test.webservice.generator.echoComplex" xmlns="it.imolinfo.jbi4corba.test.webservice.generator.echoComplex" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="echo">
<xs:complexType>
<xs:sequence>
<xs:element name="msg" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="echoResponse">
<xs:complexType>
<xs:sequence>
<xs:element name="return" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="echo">
    <wsdl:part name="parameters" element="tns:echo">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="echoResponse">
    <wsdl:part name="parameters" element="tns:echoResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Echo">
    <wsdl:operation name="echo">
      <wsdl:input name="echo" message="tns:echo">
    </wsdl:input>
      <wsdl:output name="echoResponse" message="tns:echoResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EchoCorbaBinding" type="tns:Echo">
<imolacorba:binding>
<imolacorba:idl root="true" filename="EchoMultiple.idl" relativepath=".">
//IDL
module it{
module imolinfo{
module jbi4corba{
module test{
module webservice{
module generator{
  interface Echo {
    string echo(in string msg);
  };
	
  interface Echo2 {
    string echo2(in string msg);
  };
};
};
};
};
};
};
</imolacorba:idl>
</imolacorba:binding>
    <wsdl:operation name="echo">
      <wsdl:input name="echo">
      </wsdl:input>
      <wsdl:output name="echoResponse">
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Echo">
    <wsdl:port name="EchoCorbaPort" binding="tns:EchoCorbaBinding">
<imolacorba:address name="CORBA_SERVICE_NAME" localizationType="NameService">
<imolacorba:orb>
<imolacorba:property name="quo" value="2"/>
<imolacorba:property name="qua" value=""/>
<imolacorba:property name="qui" value="1"/>
</imolacorba:orb>
</imolacorba:address>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
