<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="it.imolinfo.jbi4corba.test" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="EchoConsInOnly" targetNamespace="it.imolinfo.jbi4corba.test">
  <wsdl:types>
  </wsdl:types>
  <wsdl:message name="EchoConsInOnlyOperationRequest">
    <wsdl:part name="part1" type="xsd:string"/>
  </wsdl:message>
  <wsdl:portType name="EchoConsInOnlyPortType">
    <wsdl:operation name="EchoConsInOnlyOperation">
      <wsdl:input message="tns:EchoConsInOnlyOperationRequest" name="input1"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EchoConsInOnlyBinding" type="tns:EchoConsInOnlyPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="EchoConsInOnlyOperation">
      <soap:operation/>
      <wsdl:input name="input1">
        <soap:body namespace="it.imolinfo.jbi4corba.test" use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EchoConsInOnlyService">
    <wsdl:port binding="tns:EchoConsInOnlyBinding" name="EchoConsInOnlyPort">
      <soap:address location="http://localhost:18181/EchoConsInOnlyService/EchoConsInOnlyPort"/>
    </wsdl:port>
  </wsdl:service>
    <plnk:partnerLinkType name="EchoConsInOnly1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="EchoConsInOnlyPortTypeRole" portType="tns:EchoConsInOnlyPortType"/>
    </plnk:partnerLinkType>
</wsdl:definitions>