<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="foo" targetNamespace="http://it.imolinfo.jbi4corba.test.webservice.generator.foo" xmlns:ns1="http://it.imolinfo.jbi4corba.test.webservice.generator.it.imolinfo.jbi4corba.test.foo" xmlns:imolacorba="uri://schemas.imola.it/jbi/wsdl-extensions/corba/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://it.imolinfo.jbi4corba.test.webservice.generator.foo" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://it.imolinfo.jbi4corba.test.webservice.generator.it.imolinfo.jbi4corba.test.foo" location="foo.wsdl">
    </wsdl:import>
  <wsdl:binding name="fooCorbaBinding">
<imolacorba:binding>
<imolacorba:idl root="true" filename="TestInclude.idl" relativepath=".">
//IDL
module it{
module imolinfo{
module jbi4corba{
module test{
module webservice{
module generator{
	
	#include &quot;include1.idl&quot;
	#include &quot;include2.idl&quot;
	#include &quot;imola/include1.idl&quot;

	enum EchoComplexEnum {E1, E2, E3};

	interface foo {

		EchoComplexEnum echoEnum(in EchoComplexEnum e);

	};
};
};
};
};
};
};
</imolacorba:idl>
<imolacorba:idl root="false" filename="include2.idl" relativepath="">
module it{
module imolinfo{
module jbi4corba{
module test{


	#include &quot;include1.idl&quot;
	enum EchoComplexEnum {E1, E2, E3};

	interface foo {

		EchoComplexEnum echoEnum(in EchoComplexEnum e);

	};


};
};
};
};
</imolacorba:idl>
<imolacorba:idl root="false" filename="imola/include1.idl" relativepath="">
//idl modulo 1,2
module it{
module imolinfo{
module jbi4corba{
		
	
		// struct
  		struct echoMyStruct {
    		boolean            fieldBoolean;
    		char               fieldChar;
    		wchar              fieldWChar;

    		
  		};	

	      };
	};
};
</imolacorba:idl>
<imolacorba:idl root="false" filename="include1.idl" relativepath="">
//idl
module it{
module imolinfo{
module jbi4corba{
		
		// struct
  		struct ComplexStruct {
    		boolean            fieldBoolean;
    		char               fieldChar;
    		wchar              fieldWChar;
                wstring            fieldWString;
    		short              fieldShort;
    		unsigned short     fieldUnsignedShort;
    		long               fieldLong;
    		unsigned long      fieldUnsignedLong;
    		long long          fieldLongLong;
    		unsigned long long fieldUnsignedLongLong;
    		float              fieldFloat;
    		double             fieldDouble;

    		
  		};	

	      };
	};
};
</imolacorba:idl>
</imolacorba:binding>
    <wsdl:operation name="echoEnum">
      <wsdl:input name="echoEnum">
      </wsdl:input>
      <wsdl:output name="echoEnumResponse">
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="foo">
    <wsdl:port name="fooCorbaPort" binding="tns:fooCorbaBinding">
<imolacorba:address name="foo" localizationType="NameService">
<imolacorba:orb>
<imolacorba:property name="org.omg.CORBA.ORBInitialPort" value="1050"/>
<imolacorba:property name="org.omg.CORBA.ORBClass" value="com.sun.corba.ee.impl.orb.ORBImpl"/>
<imolacorba:property name="org.omg.CORBA.ORBInitialHost" value="localhost"/>
</imolacorba:orb>
</imolacorba:address>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
