<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/SoapWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/SoapWSDL" name="SoapWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema">
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/SoapWSDL">
            <xsd:import schemaLocation="DRIVERTEST_EMP.xsd" namespace="http://j2ee.netbeans.org/xsd/tableSchema"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="SoapWSDLOperationRequest">
        <wsdl:part name="part1" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="SoapWSDLOperationReply">
        <wsdl:part name="part1" element="ns:DRIVERTEST_EMP"/>
    </wsdl:message>
    <wsdl:portType name="SoapWSDLPortType">
        <wsdl:operation name="SoapWSDLOperation">
            <wsdl:input name="input1" message="tns:SoapWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:SoapWSDLOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SoapWSDLBinding" type="tns:SoapWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SoapWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SoapWSDL"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SoapWSDL"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SoapWSDLService">
        <wsdl:port name="SoapWSDLPort" binding="tns:SoapWSDLBinding">
            <soap:address location="http://localhost:18181/SoapWSDLService/SoapWSDLPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="SoapWSDLPartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SoapWSDLPortTypeRole" portType="tns:SoapWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
