<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/RecRecCorrAnyParentWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/RecRecCorrAnyParentWSDL" name="RecRecCorrAnyParentWSDL" xmlns:ns="http://xml.netbeans.org/schema/dataTypes.xsd" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/">
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/RecRecCorrAnyParentWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/dataTypes.xsd" schemaLocation="../dataTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="RecRecCorrAnyParentWSDLOperationRequest">
        <wsdl:part name="part1" element="ns:helloObj"/>
    </wsdl:message>
    <wsdl:message name="RecRecCorrAnyParentWSDLOperationReply">
        <wsdl:part name="part1" element="ns:helloObj"/>
    </wsdl:message>
    <wsdl:portType name="RecRecCorrAnyParentWSDLPortType">
        <wsdl:operation name="RecRecCorrAnyParentWSDLOperation">
            <wsdl:input name="input1" message="tns:RecRecCorrAnyParentWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:RecRecCorrAnyParentWSDLOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RecRecCorrAnyParentWSDLBinding" type="tns:RecRecCorrAnyParentWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="RecRecCorrAnyParentWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="RecRecCorrAnyParentWSDLService">
        <wsdl:port name="RecRecCorrAnyParentWSDLPort" binding="tns:RecRecCorrAnyParentWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/RecRecCorrAnyParentWSDLService/RecRecCorrAnyParentWSDLPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="RecRecCorrAnyParentWSDLPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="RecRecCorrAnyParentWSDLPortTypeRole" portType="tns:RecRecCorrAnyParentWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
