<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableColSpecSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableColSpecRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableColSpecResponse">
    <part name="CreateTableColSpecResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateTableColSpecRequest">
    <part name="CreateTableColSpecRequestPart" element="tns:CreateTableColSpecRequest"/>
  </message>
  <portType name="CreateTableColSpecSql_sqlsePortType">
    <operation name="CreateTableColSpec">
      <input name="CreateTableColSpecRequest" message="tns:CreateTableColSpecRequest"/>
      <output name="CreateTableColSpecResponse" message="tns:CreateTableColSpecResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableColSpecSqlBinding" type="tns:CreateTableColSpecSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableColSpec">
      <soap:operation/>
      <input name="CreateTableColSpecRequest">
        <soap:body/>
      </input>
      <output name="CreateTableColSpecResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableColSpecSql_sqlseService">
    <port name="CreateTableColSpecSql_sqlsePort" binding="tns:CreateTableColSpecSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableColSpecSql/CreateTableColSpecSql/CreateTableColSpecSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableColSpecSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableColSpecSql_myrole" portType="tns:CreateTableColSpecSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
