<?xml version="1.0" encoding="UTF-8"?>
<definitions name="createtablecolspSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="createtablecolspRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="createtablecolspResponse">
    <part name="createtablecolspResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="createtablecolspRequest">
    <part name="createtablecolspRequestPart" element="tns:createtablecolspRequest"/>
  </message>
  <portType name="createtablecolspSQL_sqlsePortType">
    <operation name="createtablecolsp">
      <input name="createtablecolspRequest" message="tns:createtablecolspRequest"/>
      <output name="createtablecolspResponse" message="tns:createtablecolspResponse"/>
    </operation>
  </portType>
  <binding name="createtablecolspSQLBinding" type="tns:createtablecolspSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="createtablecolsp">
      <soap:operation style="document"/>
      <input name="createtablecolspRequest">
        <soap:body use="literal"/>
      </input>
      <output name="createtablecolspResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="createtablecolspSQL_sqlseService">
    <port name="createtablecolspSQL_sqlsePort" binding="tns:createtablecolspSQLBinding">
      <soap:address location="http://localhost:18181/createtablecolspSQL/createtablecolspSQL/createtablecolspSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="createtablecolspSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="createtablecolspSQL_myrole" portType="tns:createtablecolspSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
