<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableCapColSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableCapColRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableCapColResponse">
    <part name="CreateTableCapColResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateTableCapColRequest">
    <part name="CreateTableCapColRequestPart" element="tns:CreateTableCapColRequest"/>
  </message>
  <portType name="CreateTableCapColSql_sqlsePortType">
    <operation name="CreateTableCapCol">
      <input name="CreateTableCapColRequest" message="tns:CreateTableCapColRequest"/>
      <output name="CreateTableCapColResponse" message="tns:CreateTableCapColResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableCapColSqlBinding" type="tns:CreateTableCapColSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableCapCol">
      <soap:operation/>
      <input name="CreateTableCapColRequest">
        <soap:body/>
      </input>
      <output name="CreateTableCapColResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableCapColSql_sqlseService">
    <port name="CreateTableCapColSql_sqlsePort" binding="tns:CreateTableCapColSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableCapColSql/CreateTableCapColSql/CreateTableCapColSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableCapColSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableCapColSql_myrole" portType="tns:CreateTableCapColSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
