<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DeleteNonExistColFullSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="DeleteNonExistColfullRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="DeleteNonExistColfullResponse">
    <part name="DeleteNonExistColfullResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="DeleteNonExistColfullRequest">
    <part name="DeleteNonExistColfullRequestPart" element="tns:DeleteNonExistColfullRequest"/>
  </message>
  <portType name="DeleteNonExistColFullSql_sqlsePortType">
    <operation name="DeleteNonExistColfull">
      <input name="DeleteNonExistColfullRequest" message="tns:DeleteNonExistColfullRequest"/>
      <output name="DeleteNonExistColfullResponse" message="tns:DeleteNonExistColfullResponse"/>
    </operation>
  </portType>
  <binding name="DeleteNonExistColFullSqlBinding" type="tns:DeleteNonExistColFullSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="DeleteNonExistColfull">
      <soap:operation/>
      <input name="DeleteNonExistColfullRequest">
        <soap:body/>
      </input>
      <output name="DeleteNonExistColfullResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="DeleteNonExistColFullSql_sqlseService">
    <port name="DeleteNonExistColFullSql_sqlsePort" binding="tns:DeleteNonExistColFullSqlBinding">
      <soap:address location="http://localhost:18181/DeleteNonExistColFullSql/DeleteNonExistColFullSql/DeleteNonExistColFullSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="DeleteNonExistColFullSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="DeleteNonExistColFullSql_myrole" portType="tns:DeleteNonExistColFullSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
