package it.imolinfo.jbi4corba.test;

/**
* it/imolinfo/jbi4corba/test/EchoObj2Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test_Object_DP.idl
* martedì 25 agosto 2009 17.06.36 CEST
*/

public final class EchoObj2Holder implements org.omg.CORBA.portable.Streamable
{
  public it.imolinfo.jbi4corba.test.EchoObj2 value = null;

  public EchoObj2Holder ()
  {
  }

  public EchoObj2Holder (it.imolinfo.jbi4corba.test.EchoObj2 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = it.imolinfo.jbi4corba.test.EchoObj2Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    it.imolinfo.jbi4corba.test.EchoObj2Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return it.imolinfo.jbi4corba.test.EchoObj2Helper.type ();
  }

}
