<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/Pick_And_EvtHdlr_parentBPWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Pick_And_EvtHdlr_parentBPWSDL" name="Pick_And_EvtHdlr_parentBPWSDL" xmlns:ns="http://xml.netbeans.org/schema/dataTypes.xsd" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns0="http://j2ee.netbeans.org/wsdl/Invoke_ReqRespsubBPWSDL" xmlns:ns1="http://j2ee.netbeans.org/wsdl/Pick_And_EveHdlr">
    <wsdl:import location="../../Invoke_ReqResp/Invoke_ReqRespsubBPWSDL.wsdl" namespace="http://j2ee.netbeans.org/wsdl/Invoke_ReqRespsubBPWSDL"/>
    <wsdl:import location="Pick_And_EveHdlr.wsdl" namespace="http://j2ee.netbeans.org/wsdl/Pick_And_EveHdlr"/>
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/Pick_And_EvtHdlr_parentBPWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/dataTypes.xsd" schemaLocation="../../dataTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="Pick_And_EvtHdlr_parentBPWSDLOperationRequest">
        <wsdl:part name="part1" element="ns:helloObj"/>
    </wsdl:message>
    <wsdl:message name="Pick_And_EvtHdlr_parentBPWSDLOperationReply">
        <wsdl:part name="part1" element="ns:helloObj"/>
    </wsdl:message>
    <wsdl:portType name="Pick_And_EvtHdlr_parentBPWSDLPortType">
        <wsdl:operation name="Pick_And_EvtHdlr_parentBPWSDLOperation">
            <wsdl:input name="input1" message="tns:Pick_And_EvtHdlr_parentBPWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:Pick_And_EvtHdlr_parentBPWSDLOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="Pick_And_EvtHdlr_parentBPWSDLBinding" type="tns:Pick_And_EvtHdlr_parentBPWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Pick_And_EvtHdlr_parentBPWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="Pick_And_EvtHdlr_parentBPWSDLService">
        <wsdl:port name="Pick_And_EvtHdlr_parentBPWSDLPort" binding="tns:Pick_And_EvtHdlr_parentBPWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/Pick_And_EvtHdlr_parentBPWSDLService/Pick_And_EvtHdlr_parentBPWSDLPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="Pick_And_EvtHdlr_parentBPWSDLPartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="Pick_And_EvtHdlr_parentBPWSDLPortTypeRole" portType="tns:Pick_And_EvtHdlr_parentBPWSDLPortType"/>
    </plnk:partnerLinkType>

    <vprop:property name="property1" type="xsd:nonNegativeInteger"/>
    <vprop:propertyAlias propertyName="tns:property1"
    messageType="ns0:Invoke_ReqRespsubBPWSDLOperationRequest" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:nonNegativeInteger</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property1"
    messageType="ns0:Invoke_ReqRespsubBPWSDLOperationReply" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:nonNegativeInteger</vprop:query>
    </vprop:propertyAlias>   
    <vprop:propertyAlias propertyName="tns:property1"
    messageType="ns1:Pick_And_EveHdlrOperationRequest1" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:nonNegativeInteger</vprop:query>
    </vprop:propertyAlias>  
    <vprop:propertyAlias propertyName="tns:property1"
    messageType="ns1:Pick_And_EveHdlrOperationRequest2" part="part">
        <vprop:query>/ns:helloObj/ns:recursive/ns:nonNegativeInteger</vprop:query>
    </vprop:propertyAlias>      
    
    <vprop:property name="property2" type="xsd:decimal"/>
    <vprop:propertyAlias propertyName="tns:property2"
    messageType="ns0:Invoke_ReqRespsubBPWSDLOperationRequest" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:decimal</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property2"
    messageType="ns0:Invoke_ReqRespsubBPWSDLOperationReply" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:decimal</vprop:query>
    </vprop:propertyAlias>   
    <vprop:propertyAlias propertyName="tns:property2"
    messageType="ns1:Pick_And_EveHdlrOperationRequest1" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:decimal</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property2"
    messageType="ns1:Pick_And_EveHdlrOperationRequest2" part="part">
        <vprop:query>/ns:helloObj/ns:recursive/ns:decimal</vprop:query>
    </vprop:propertyAlias>     
    
    <vprop:property name="property3" type="xsd:long"/>
    <vprop:propertyAlias propertyName="tns:property3"
    messageType="ns0:Invoke_ReqRespsubBPWSDLOperationRequest" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:long</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:property3"
    messageType="ns0:Invoke_ReqRespsubBPWSDLOperationReply" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:long</vprop:query>
    </vprop:propertyAlias>   
    <vprop:propertyAlias propertyName="tns:property3"
    messageType="ns1:Pick_And_EveHdlrOperationRequest1" part="part1">
        <vprop:query>/ns:helloObj/ns:recursive/ns:long</vprop:query>
    </vprop:propertyAlias>    
    <vprop:propertyAlias propertyName="tns:property3"
    messageType="ns1:Pick_And_EveHdlrOperationRequest2" part="part">
        <vprop:query>/ns:helloObj/ns:recursive/ns:long</vprop:query>
    </vprop:propertyAlias>     
    
</definitions>
