<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ExitInRepeatUntil" targetNamespace="http://j2ee.netbeans.org/wsdl/ExitInRepeatUntil"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://j2ee.netbeans.org/wsdl/ExitInRepeatUntil">
    <types/>
    <message name="ExitInRepeatUntilOperationRequest">
        <part name="InputPart" type="xsd:string"/>
    </message>
    <message name="ExitInRepeatUntilOperationReply">
        <part name="OutputPart" type="xsd:string"/>
    </message>
    <portType name="ExitInRepeatUntilPortType">
        <wsdl:operation name="ExitInRepeatUntilOperation">
            <wsdl:input name="input1" message="tns:ExitInRepeatUntilOperationRequest"/>
            <wsdl:output name="output1" message="tns:ExitInRepeatUntilOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="ExitInRepeatUntilBinding" type="tns:ExitInRepeatUntilPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ExitInRepeatUntilOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ExitInRepeatUntil"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ExitInRepeatUntil"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="ExitInRepeatUntilService">
        <wsdl:port name="ExitInRepeatUntilPort" binding="tns:ExitInRepeatUntilBinding">
            <soap:address location="http://localhost:18181/TerminationHandlerBpel/ExitInRepeatUntil/ExitInRepeatUntilService/ExitInRepeatUntilPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="ExitInRepeatUntilPlink">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="ExitInRepeatUntilPortTypeRole" portType="tns:ExitInRepeatUntilPortType"/>
    </plnk:partnerLinkType>
</definitions>
