<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DropAllRowsSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="DropAllRowsRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="DropAllRowsResponse">
    <part name="DropAllRowsResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="DropAllRowsRequest">
    <part name="DropAllRowsRequestPart" element="tns:DropAllRowsRequest"/>
  </message>
  <portType name="DropAllRowsSql_sqlsePortType">
    <operation name="DropAllRows">
      <input name="DropAllRowsRequest" message="tns:DropAllRowsRequest"/>
      <output name="DropAllRowsResponse" message="tns:DropAllRowsResponse"/>
    </operation>
  </portType>
  <binding name="DropAllRowsSqlBinding" type="tns:DropAllRowsSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="DropAllRows">
      <soap:operation/>
      <input name="DropAllRowsRequest">
        <soap:body/>
      </input>
      <output name="DropAllRowsResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="DropAllRowsSql_sqlseService">
    <port name="DropAllRowsSql_sqlsePort" binding="tns:DropAllRowsSqlBinding">
      <soap:address location="http://localhost:18181/DropAllRowsSql/DropAllRowsSql/DropAllRowsSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="DropAllRowsSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="DropAllRowsSql_myrole" portType="tns:DropAllRowsSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
