<?xml version="1.0" encoding="UTF-8"?>
<definitions name="altertablenonemptycolfullqualSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="altertablenonemptycolfullqualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="altertablenonemptycolfullqualResponse">
    <part name="altertablenonemptycolfullqualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="altertablenonemptycolfullqualRequest">
    <part name="altertablenonemptycolfullqualRequestPart" element="tns:altertablenonemptycolfullqualRequest"/>
  </message>
  <portType name="altertablenonemptycolfullqualSQL_sqlsePortType">
    <operation name="altertablenonemptycolfullqual">
      <input name="altertablenonemptycolfullqualRequest" message="tns:altertablenonemptycolfullqualRequest"/>
      <output name="altertablenonemptycolfullqualResponse" message="tns:altertablenonemptycolfullqualResponse"/>
    </operation>
  </portType>
  <binding name="altertablenonemptycolfullqualSQLBinding" type="tns:altertablenonemptycolfullqualSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="altertablenonemptycolfullqual">
      <soap:operation style="document"/>
      <input name="altertablenonemptycolfullqualRequest">
        <soap:body use="literal"/>
      </input>
      <output name="altertablenonemptycolfullqualResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="altertablenonemptycolfullqualSQL_sqlseService">
    <port name="altertablenonemptycolfullqualSQL_sqlsePort" binding="tns:altertablenonemptycolfullqualSQLBinding">
      <soap:address location="http://localhost:18181/altertablenonemptycolfullqualSQL/altertablenonemptycolfullqualSQL/altertablenonemptycolfullqualSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="altertablenonemptycolfullqualSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="altertablenonemptycolfullqualSQL_myrole" portType="tns:altertablenonemptycolfullqualSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
