<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableCapSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableCapRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableCapRequest">
    <part name="CreateTableCapRequestPart" element="tns:CreateTableCapRequest"/>
  </message>
  <message name="CreateTableCapResponse">
    <part name="CreateTableCapResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="CreateTableCapSql_sqlsePortType">
    <operation name="CreateTableCap">
      <input name="CreateTableCapRequest" message="tns:CreateTableCapRequest"/>
      <output name="CreateTableCapResponse" message="tns:CreateTableCapResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableCapSqlBinding" type="tns:CreateTableCapSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableCap">
      <soap:operation/>
      <input name="CreateTableCapRequest">
        <soap:body/>
      </input>
      <output name="CreateTableCapResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableCapSql_sqlseService">
    <port name="CreateTableCapSql_sqlsePort" binding="tns:CreateTableCapSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableCapSql/CreateTableCapSql/CreateTableCapSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableCapSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableCapSql_myrole" portType="tns:CreateTableCapSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
