<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="InboundInLinedOutboundAttchWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/InboundInLinedOutboundAttchWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/InboundInLinedOutboundAttchWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://example.org/mime/InboundInlined">
    <import location="InboundInLinedOutboundAttch.wsdl" namespace="http://example.org/mime/InboundInlined"/>
    <plnk:partnerLinkType name="InboundInLinedOutboundAttchLinkType">
        <plnk:role name="InbounfInlinedRole" portType="ns:InboundInLinedOutboundAttch"/>
    </plnk:partnerLinkType>
</definitions>
