//idl modulo 1,2
module it{
module imolinfo{
module jbi4corba{
		
	
		// struct
  		struct echoMyStruct {
    		boolean            fieldBoolean;
    		char               fieldChar;
    		wchar              fieldWChar;

    		
  		};	

	      };
	};
};