<?xml version="1.0" encoding="UTF-8"?>
<definitions name="selectwrongtabnamefullqualSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="selectwrongtabnamefullqualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="selectwrongtabnamefullqualResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="selectwrongtabnamefullqualResponse">
    <part name="selectwrongtabnamefullqualResponsePart" element="tns:selectwrongtabnamefullqualResponse"/>
  </message>
  <message name="selectwrongtabnamefullqualRequest">
    <part name="selectwrongtabnamefullqualRequestPart" element="tns:selectwrongtabnamefullqualRequest"/>
  </message>
  <portType name="selectwrongtabnamefullqualSQL_sqlsePortType">
    <operation name="selectwrongtabnamefullqual">
      <input name="selectwrongtabnamefullqualRequest" message="tns:selectwrongtabnamefullqualRequest"/>
      <output name="selectwrongtabnamefullqualResponse" message="tns:selectwrongtabnamefullqualResponse"/>
    </operation>
  </portType>
  <binding name="selectwrongtabnamefullqualSQLBinding" type="tns:selectwrongtabnamefullqualSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="selectwrongtabnamefullqual">
      <soap:operation style="document"/>
      <input name="selectwrongtabnamefullqualRequest">
        <soap:body use="literal"/>
      </input>
      <output name="selectwrongtabnamefullqualResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="selectwrongtabnamefullqualSQL_sqlseService">
    <port name="selectwrongtabnamefullqualSQL_sqlsePort" binding="tns:selectwrongtabnamefullqualSQLBinding">
      <soap:address location="http://localhost:18181/selectwrongtabnamefullqualSQL/selectwrongtabnamefullqualSQL/selectwrongtabnamefullqualSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="selectwrongtabnamefullqualSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="selectwrongtabnamefullqualSQL_myrole" portType="tns:selectwrongtabnamefullqualSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
