<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/SMTPSendWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/SMTPSendWSDL" name="SMTPSendWSDL" xmlns:ns="http://xml.netbeans.org/schema/newXMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:smtp="http://schemas.sun.com/jbi/wsdl-extensions/smtp/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/SMTPSendWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/newXMLSchema" schemaLocation="FBCAddressSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="SMTPSendWSDLOperationRequest">
        <part name="part1" element="ns:Address"/>
    </message>
    <portType name="SMTPSendWSDLPortType">
        <wsdl:operation name="SMTPSendWSDLOperation">
            <wsdl:input name="input1" message="tns:SMTPSendWSDLOperationRequest"/>
        </wsdl:operation>
    </portType>
    <binding name="SMTPSendWSDLBinding" type="tns:SMTPSendWSDLPortType">
        <smtp:binding/>
        <wsdl:operation name="SMTPSendWSDLOperation">
            <smtp:operation/>
            <wsdl:input name="input1">
                <smtp:input message="part1"/>
            </wsdl:input>
        </wsdl:operation>
    </binding>
    <service name="SMTPSendWSDLService">
        <wsdl:port name="SMTPSendWSDLPort" binding="tns:SMTPSendWSDLBinding">
            <smtp:address location="mailto:mailwayi@boreas.stc.com" smtpserver="boreas.stc.com"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="SMTPSendWSDL1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SMTPSendWSDLPortTypeRole" portType="tns:SMTPSendWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
