<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/TriggerWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/TriggerWSDL" name="TriggerWSDL" xmlns:ns="http://xml.netbeans.org/schema/newXMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/TriggerWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/newXMLSchema" schemaLocation="FBCAddressSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="TriggerWSDLOperationRequest">
        <part name="part1" element="ns:Address"/>
    </message>
    <message name="TriggerWSDLOperationReply">
        <part name="part1" element="ns:Address"/>
    </message>
    <portType name="TriggerWSDLPortType">
        <wsdl:operation name="TriggerWSDLOperation">
            <wsdl:input name="input1" message="tns:TriggerWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:TriggerWSDLOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="TriggerWSDLBinding" type="tns:TriggerWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="TriggerWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="TriggerWSDLService">
        <wsdl:port name="TriggerWSDLPort" binding="tns:TriggerWSDLBinding">
            <soap:address location="http://localhost:18181/TriggerWSDLService/TriggerWSDLPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="TriggerWSDL1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="TriggerWSDLPortTypeRole" portType="tns:TriggerWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
