<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WWOrderRouterStatic" targetNamespace="http://cbr.pojo.openesb.glassfish.org/WWOrderRouterStatic/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cbr.pojo.openesb.glassfish.org/WWOrderRouterStatic/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="WWOrderRouterStaticOperationRequest">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <message name="WWOrderRouterStaticOperationResponse">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <portType name="WWOrderRouterStaticInterface">
        <operation name="WWOrderRouterStaticOperation">
            <input name="input1" message="tns:WWOrderRouterStaticOperationRequest"/>
            <output name="output1" message="tns:WWOrderRouterStaticOperationResponse"/>
        </operation>
    </portType>
</definitions>
