package it.imolinfo.jbi4corba.test.testprovidercomplexmult;


/**
* it/imolinfo/jbi4corba/test/testprovidercomplexmult/EchoComplex3.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoMultipleComplex.idl
* mercoledì 19 novembre 2008 17.11.46 CET
*/

public interface EchoComplex3 extends EchoComplex3Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EchoComplex3
