package it.imolinfo.jbi4corba.test.testprovidercomplexmult;


/**
* it/imolinfo/jbi4corba/test/testprovidercomplexmult/MyLong.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoMultipleComplex.idl
* mercoledì 19 novembre 2008 17.11.46 CET
*/


// value type (boxed) - primitive
public abstract class MyLong implements org.omg.CORBA.portable.StreamableValue
{
  public int data = (int)0;

  private static String[] _truncatable_ids = {
    it.imolinfo.jbi4corba.test.testprovidercomplexmult.MyLongHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.data = istream.read_long ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_long (this.data);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return it.imolinfo.jbi4corba.test.testprovidercomplexmult.MyLongHelper.type ();
  }
} // class MyLong
