<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/CacheAspect"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             name="CacheAspect" 
             xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
             xmlns:tns="http://j2ee.netbeans.org/wsdl/CacheAspect" 
             xmlns:ns0="http://xml.netbeans.org/schema/SynchronousSample" 
             xmlns:ns1="http://localhost/SynchronousSample/SynchronousSample" 
             xmlns:http="http://schemas.xmlsoap.org/wsdl/http/">
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/CacheAspect">
            <xsd:import namespace="http://xml.netbeans.org/schema/SynchronousSample" schemaLocation="SynchronousSample.xsd"/>
        </xsd:schema>    
    </wsdl:types>
    <wsdl:import location="SynchronousSample.wsdl" namespace="http://localhost/SynchronousSample/SynchronousSample"/>
    <wsdl:portType name="cachePortType">
        <wsdl:operation name="operation1">
            <wsdl:input name="input1" message="ns1:requestMessage"/>
            <wsdl:output name="output1" message="ns1:responseMessage"/>
        </wsdl:operation>
    </wsdl:portType>    
    <wsdl:binding name="cacheBinding1" type="tns:cachePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <wsdl:operation name="operation1">
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>    
    <wsdl:service name="CacheService1">
        <wsdl:port name="CachePort1" binding="tns:cacheBinding1">
            <wsdl:documentation/>
            <soap:address location="http://localhost:28181/CacheSynchronousSample"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
                          name="cachePartnerlinktype1">
        <plnk:role name="cachePartnerlinktyperole1" portType="tns:cachePortType"/>
    </plnk:partnerLinkType>    
</definitions>
