<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WithinIf" targetNamespace="http://j2ee.netbeans.org/wsdl/WithinIf"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://j2ee.netbeans.org/wsdl/WithinIf">
    <types/>
    <message name="WithinIfOperationRequest">
        <part name="part1" type="xsd:string"/>
        <part name="part2" type="xsd:string"/>
    </message>
    <message name="WithinIfOperationReply">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="WithinIfPortType">
        <wsdl:operation name="WithinIfOperation">
            <wsdl:input name="input1" message="tns:WithinIfOperationRequest"/>
            <wsdl:output name="output1" message="tns:WithinIfOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="WithinIfBinding" type="tns:WithinIfPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="WithinIfOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/WithinIf"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/WithinIf"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="WithinIfService">
        <wsdl:port name="WithinIfPort" binding="tns:WithinIfBinding">
            <soap:address location="http://localhost:18181/WithinIfService/WithinIfPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="WithinIf1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="WithinIfPortTypeRole" portType="tns:WithinIfPortType"/>
    </plnk:partnerLinkType>
</definitions>
