/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jbi_swiftbc_extensions_jni_HandleServer */

#ifndef _Included_com_sun_jbi_swiftbc_extensions_jni_HandleServer
#define _Included_com_sun_jbi_swiftbc_extensions_jni_HandleServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_jbi_swiftbc_extensions_jni_HandleServer
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_jbi_swiftbc_extensions_jni_HandleServer_free
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_jbi_swiftbc_extensions_jni_HandleServer
 * Method:    getRequest
 * Signature: (Lcom/sun/jbi/swiftbc/extensions/SwiftMessage;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jbi_swiftbc_extensions_jni_HandleServer_getRequest__Lcom_sun_jbi_swiftbc_extensions_SwiftMessage_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sun_jbi_swiftbc_extensions_jni_HandleServer
 * Method:    getRequest
 * Signature: (JLcom/sun/jbi/swiftbc/extensions/SwiftMessage;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jbi_swiftbc_extensions_jni_HandleServer_getRequest__JLcom_sun_jbi_swiftbc_extensions_SwiftMessage_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_sun_jbi_swiftbc_extensions_jni_HandleServer
 * Method:    putResponse
 * Signature: (JLcom/sun/jbi/swiftbc/extensions/SwiftMessage;)V
 */
JNIEXPORT void JNICALL Java_com_sun_jbi_swiftbc_extensions_jni_HandleServer_putResponse
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
