/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter */

#ifndef _Included_com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter
#define _Included_com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter
 * Method:    alloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter_free
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter
 * Method:    set
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter_set
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter
 * Method:    getNativeBuffer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter_getNativeBuffer
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_jbi_swiftbc_extensions_jni_SAGJNILetter_getLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
