<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AlterTableSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="AlterTableRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="AlterTableResponse">
    <part name="AlterTableResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="AlterTableRequest">
    <part name="AlterTableRequestPart" element="tns:AlterTableRequest"/>
  </message>
  <portType name="AlterTableSql_sqlsePortType">
    <operation name="AlterTable">
      <input name="AlterTableRequest" message="tns:AlterTableRequest"/>
      <output name="AlterTableResponse" message="tns:AlterTableResponse"/>
    </operation>
  </portType>
  <binding name="AlterTableSqlBinding" type="tns:AlterTableSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="AlterTable">
      <soap:operation/>
      <input name="AlterTableRequest">
        <soap:body/>
      </input>
      <output name="AlterTableResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="AlterTableSql_sqlseService">
    <port name="AlterTableSql_sqlsePort" binding="tns:AlterTableSqlBinding">
      <soap:address location="http://localhost:18181/AlterTableSql/AlterTableSql/AlterTableSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="AlterTableSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="AlterTableSql_myrole" portType="tns:AlterTableSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
