<?xml version="1.0" encoding="UTF-8"?>
<definitions name="OneWayCallbackBpelService" targetNamespace="http://j2ee.netbeans.org/wsdl/OneWayCallbackBpelService"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://j2ee.netbeans.org/wsdl/OneWayCallbackBpelService"
    xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" 
    xmlns:sref="http://docs.oasis-open.org/wsbpel/2.0/serviceref" >
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/OneWayCallbackBpelService" xmlns:tns="http://j2ee.netbeans.org/wsdl/OneWayCallbackBpelService">
            <xsd:import schemaLocation="addressing.xsd" namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
            <xsd:import schemaLocation="ws-bpel_serviceref.xsd" namespace="http://docs.oasis-open.org/wsbpel/2.0/serviceref"/>
            <xsd:complexType name="EPR">
                <xsd:sequence>
                    <xsd:element ref="wsa:EndpointReference"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="ServiceRef">
                <xsd:sequence>
                    <xsd:element ref="sref:service-ref"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="OneWayCallbackBpelServiceInOperationRequest">
        <part name="Data" type="xsd:string"/>
        <part name="EPR" element="wsa:EndpointReference"/>
    </message>
    <portType name="OneWayCallbackBpelServiceInPortType">
        <operation name="OneWayCallbackBpelServiceInOperation">
            <input name="input1" message="tns:OneWayCallbackBpelServiceInOperationRequest"/>
        </operation>
    </portType>
    <binding name="OneWayCallbackBpelServiceInBinding" type="tns:OneWayCallbackBpelServiceInPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="OneWayCallbackBpelServiceInOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/OneWayCallbackBpelService"/>
            </input>
        </operation>
    </binding>
    <service name="OneWayCallbackBpelServiceInService">
        <port name="OneWayCallbackBpelServiceInPort" binding="tns:OneWayCallbackBpelServiceInBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/OneWayCallbackBpelServiceInService/OneWayCallbackBpelServiceInPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="OneWayCallbackBpelServiceIn">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="OneWayCallbackBpelServiceInPortTypeRole" portType="tns:OneWayCallbackBpelServiceInPortType"/>
    </plnk:partnerLinkType>
</definitions>
