<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ForEachInFlowBranch" targetNamespace="http://j2ee.netbeans.org/wsdl/ForEachInFlowBranch"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/ForEachInFlowBranch" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="ForEachInFlowBranchOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="ForEachInFlowBranchPortType">
        <wsdl:operation name="ForEachInFlowBranchOperation">
            <wsdl:input name="input1" message="tns:ForEachInFlowBranchOperationRequest"/>
        </wsdl:operation>
    </portType>
    <binding name="ForEachInFlowBranchBinding" type="tns:ForEachInFlowBranchPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ForEachInFlowBranchOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ForEachInFlowBranch"/>
            </wsdl:input>
        </wsdl:operation>
    </binding>
    <service name="ForEachInFlowBranchService">
        <wsdl:port name="ForEachInFlowBranchPort" binding="tns:ForEachInFlowBranchBinding">
            <soap:address location="http://localhost:18181/ForEachInFlowBranchService/ForEachInFlowBranchPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="ForEachInFlowBranch">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="ForEachInFlowBranchPortTypeRole" portType="tns:ForEachInFlowBranchPortType"/>
    </plnk:partnerLinkType>
    <portType name="ForEachInFlowBranch1PortType">
        <wsdl:operation name="ForEachInFlowBranch1Operation">
            <wsdl:input name="input1" message="tns:ForEachInFlowBranchOperationRequest"/>
        </wsdl:operation>
    </portType>
    <binding name="ForEachInFlowBranch1Binding" type="tns:ForEachInFlowBranch1PortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ForEachInFlowBranch1Operation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ForEachInFlowBranch"/>
            </wsdl:input>
        </wsdl:operation>
    </binding>
    <service name="ForEachInFlowBranch1Service">
        <wsdl:port name="ForEachInFlowBranch1Port" binding="tns:ForEachInFlowBranch1Binding">
            <soap:address location="http://localhost:18181/ForEachInFlowBranch1Service/ForEachInFlowBranch1Port"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="ForEachInFlowBranch1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="ForEachInFlowBranch1PortTypeRole" portType="tns:ForEachInFlowBranch1PortType"/>
    </plnk:partnerLinkType>    
</definitions>
