<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongParamViewSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongParamViewRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongParamViewResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongParamViewResponse">
    <part name="SelectWrongParamViewResponsePart" element="tns:SelectWrongParamViewResponse"/>
  </message>
  <message name="SelectWrongParamViewRequest">
    <part name="SelectWrongParamViewRequestPart" element="tns:SelectWrongParamViewRequest"/>
  </message>
  <portType name="SelectWrongParamViewSql_sqlsePortType">
    <operation name="SelectWrongParamView">
      <input name="SelectWrongParamViewRequest" message="tns:SelectWrongParamViewRequest"/>
      <output name="SelectWrongParamViewResponse" message="tns:SelectWrongParamViewResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongParamViewSqlBinding" type="tns:SelectWrongParamViewSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongParamView">
      <soap:operation/>
      <input name="SelectWrongParamViewRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongParamViewResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongParamViewSql_sqlseService">
    <port name="SelectWrongParamViewSql_sqlsePort" binding="tns:SelectWrongParamViewSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongParamViewSql/SelectWrongParamViewSql/SelectWrongParamViewSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongParamViewSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongParamViewSql_myrole" portType="tns:SelectWrongParamViewSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
