package it.imolinfo.jbi4corba.test.rtti;


/**
* it/imolinfo/jbi4corba/test/rtti/rtti_test.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RttiPragmaPrefix.idl
* Wednesday, July 22, 2009 4:13:00 PM CEST
*/

public interface rtti_test extends rtti_testOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface rtti_test
