<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/repeatingNode"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/repeatingNode" name="repeatingNode" xmlns:ns="http://xml.netbeans.org/schema/newXMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/repeatingNode">
            <xsd:import xmlns="http://www.w3.org/2001/XMLSchema" namespace="http://xml.netbeans.org/schema/newXMLSchema" schemaLocation="repeatingNode.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="repeatingNodeOperationRequest">
        <wsdl:part name="part1" element="ns:newElement"/>
    </wsdl:message>
    <wsdl:message name="repeatingNodeOperationReply">
        <wsdl:part name="part1" element="ns:newElement"/>
    </wsdl:message>
    <wsdl:portType name="repeatingNodePortType">
        <wsdl:operation name="repeatingNodeOperation">
            <wsdl:input name="input1" message="tns:repeatingNodeOperationRequest"/>
            <wsdl:output name="output1" message="tns:repeatingNodeOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="repeatingNodeBinding" type="tns:repeatingNodePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="repeatingNodeOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="repeatingNodeService">
        <wsdl:port name="repeatingNodePort" binding="tns:repeatingNodeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/repeatingNodeService/repeatingNodePort"/>
        </wsdl:port>
    </wsdl:service>
    <plink:partnerLinkType name="repeatingNodePartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plink:role name="repeatingNodePortTypeRole" portType="tns:repeatingNodePortType"/>
    </plink:partnerLinkType>
</definitions>
