<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/SoapFeeder4FileOneWayIn"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/SoapFeeder4FileOneWayIn" name="SoapFeeder4FileOneWayIn" xmlns:ns="http://xml.netbeans.org/schema/SimpleSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/SoapFeeder4FileOneWayIn">
            <xsd:import namespace="http://xml.netbeans.org/schema/SimpleSchema" schemaLocation="SimpleSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="SoapFeeder4FileOneWayInOperationRequest">
        <part name="part1" type="ns:requestType"/>
    </message>
    <message name="SoapFeeder4FileOneWayInOperationReply">
        <part name="part1" type="ns:responseType"/>
    </message>
    <portType name="SoapFeeder4FileOneWayInPortType">
        <wsdl:operation name="SoapFeeder4FileOneWayInOperation">
            <wsdl:input name="input1" message="tns:SoapFeeder4FileOneWayInOperationRequest"/>
            <wsdl:output name="output1" message="tns:SoapFeeder4FileOneWayInOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="SoapFeeder4FileOneWayInBinding" type="tns:SoapFeeder4FileOneWayInPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SoapFeeder4FileOneWayInOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SoapFeeder4FileOneWayIn"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SoapFeeder4FileOneWayIn"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="SoapFeeder4FileOneWayInService">
        <wsdl:port name="SoapFeeder4FileOneWayInPort" binding="tns:SoapFeeder4FileOneWayInBinding">
            <soap:address location="http://localhost:18181/SoapFeeder4FileOneWayInService/SoapFeeder4FileOneWayInPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="SoapFeeder4FileOneWayInPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SoapFeeder4FileOneWayInPortTypeRole" portType="tns:SoapFeeder4FileOneWayInPortType"/>
    </plnk:partnerLinkType>
</definitions>
