<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/flowWith3ReceivesDriverWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/flowWith3ReceivesDriverWSDL" name="flowWith3ReceivesDriverWSDL" xmlns:ns="http://xml.netbeans.org/schema/Corr-Flow-inlineSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/" xmlns:hl7="http://schemas.sun.com/jbi/wsdl-extensions/hl7/" xmlns:ns1="http://xml.netbeans.org/schema/dataTypes.xsd">
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/flowWith3ReceivesDriverWSDL">
            <xsd:import schemaLocation="../dataTypes.xsd" namespace="http://xml.netbeans.org/schema/dataTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="flowWith3ReceivesDriverWSDLOperationRequest">
        <wsdl:part name="part1" element="ns1:helloObj"/>
    </wsdl:message>
    <wsdl:message name="flowWith3ReceivesDriverWSDLOperationReply">
        <wsdl:part name="part1" element="ns1:helloObj"/>
    </wsdl:message>
    <wsdl:portType name="flowWith3ReceivesDriverWSDLPortType">
        <wsdl:operation name="flowWith3ReceivesDriverWSDLOperation">
            <wsdl:input name="input1" message="tns:flowWith3ReceivesDriverWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:flowWith3ReceivesDriverWSDLOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="flowWith3ReceivesDriverWSDLBinding" type="tns:flowWith3ReceivesDriverWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="flowWith3ReceivesDriverWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="flowWith3ReceivesDriverWSDLService">
        <wsdl:port name="flowWith3ReceivesDriverWSDLPort" binding="tns:flowWith3ReceivesDriverWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/flowWith3ReceivesDriverWSDLService/flowWith3ReceivesDriverWSDLPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="flowWith3ReceivesDriverWSDLPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="flowWith3ReceivesDriverWSDLPortTypeRole" portType="tns:flowWith3ReceivesDriverWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
