<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InsertWrongTypeSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="InsertWrongTypeRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="InsertWrongTypeRequest">
    <part name="InsertWrongTypeRequestPart" element="tns:InsertWrongTypeRequest"/>
  </message>
  <message name="InsertWrongTypeResponse">
    <part name="InsertWrongTypeResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="InsertWrongTypeSql_sqlsePortType">
    <operation name="InsertWrongType">
      <input name="InsertWrongTypeRequest" message="tns:InsertWrongTypeRequest"/>
      <output name="InsertWrongTypeResponse" message="tns:InsertWrongTypeResponse"/>
    </operation>
  </portType>
  <binding name="InsertWrongTypeSqlBinding" type="tns:InsertWrongTypeSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="InsertWrongType">
      <soap:operation/>
      <input name="InsertWrongTypeRequest">
        <soap:body/>
      </input>
      <output name="InsertWrongTypeResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="InsertWrongTypeSql_sqlseService">
    <port name="InsertWrongTypeSql_sqlsePort" binding="tns:InsertWrongTypeSqlBinding">
      <soap:address location="http://localhost:18181/InsertWrongTypeSql/InsertWrongTypeSql/InsertWrongTypeSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="InsertWrongTypeSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="InsertWrongTypeSql_myrole" portType="tns:InsertWrongTypeSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
