<definitions targetNamespace="urn:CorrInvOnMsgChildTargetNamespace"
             name="CorrInvOnMsgChildDefinition"
             xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:tns="urn:CorrInvOnMsgChildTargetNamespace"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:slnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:parentWSDL="corrInvOnMsgParent">
    <plnk:partnerLinkType name="CorrInvOnMsgChildServiceLinkType"
                          xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plnk:role name="CorrInvOnMsgChildServerRole"
                   portType="tns:CorrInvOnMsgChildPortType"></plnk:role>
    </plnk:partnerLinkType>
    <vprop:propertyAlias part="CorrInvOnMsgChildPart"
                        propertyName="parentWSDL:property"
                        messageType="tns:CorrInvOnMsgChildMessage">
        <vprop:query>string</vprop:query>
    </vprop:propertyAlias>
    <import location="corrInvOnMsg_parent.wsdl" namespace="corrInvOnMsgParent"/>
    <types>
        <xsd:schema targetNamespace="urn:CorrInvOnMsgChildTargetNamespace"
                    attributeFormDefault="unqualified"
                    elementFormDefault="qualified"
                    xmlns:tns="urn:CorrInvOnMsgChildTargetNamespace"
                    xmlns:ns1="urn:CorrInvOnMsgChildTargetNamespace"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    xmlns="http://schemas.xmlsoap.org/wsdl/"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
            
                    <xsd:complexType name="CorrInvOnMsgChildType">
                <xsd:sequence>
                    <xsd:element type="xsd:string"
                                 name="string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="CorrInvOnMsgChildMessage">
        <part name="CorrInvOnMsgChildPart"
              type="tns:CorrInvOnMsgChildType"></part>
    </message>
    <portType name="CorrInvOnMsgChildPortType">
        <operation name="CorrInvOnMsgChildOperation">
            <input message="tns:CorrInvOnMsgChildMessage"></input>
            <output message="tns:CorrInvOnMsgChildMessage"></output>
        </operation>
    </portType>
    <binding name="CorrInvOnMsgChildBinding"
             type="tns:CorrInvOnMsgChildPortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CorrInvOnMsgChildOperation">
            <soap:operation soapAction="CorrInvOnMsgChildOperation"/>
            <input>
                <soap:body parts="CorrInvOnMsgChildPart"
                           use="literal"/>
            </input>
            <output>
                <soap:body parts="CorrInvOnMsgChildPart"
                           use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="CorrInvOnMsgChildService">
        <port name="CorrInvOnMsgChildPort"
              binding="tns:CorrInvOnMsgChildBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/service/CorrInvOnMsgChild"/>
        </port>
    </service>
</definitions>
