<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InsertOneRowTableFullSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="InsertOneRowTableFullRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="InsertOneRowTableFullRequest">
    <part name="InsertOneRowTableFullRequestPart" element="tns:InsertOneRowTableFullRequest"/>
  </message>
  <message name="InsertOneRowTableFullResponse">
    <part name="InsertOneRowTableFullResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="InsertOneRowTableFullSql_sqlsePortType">
    <operation name="InsertOneRowTableFull">
      <input name="InsertOneRowTableFullRequest" message="tns:InsertOneRowTableFullRequest"/>
      <output name="InsertOneRowTableFullResponse" message="tns:InsertOneRowTableFullResponse"/>
    </operation>
  </portType>
  <binding name="InsertOneRowTableFullSqlBinding" type="tns:InsertOneRowTableFullSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="InsertOneRowTableFull">
      <soap:operation/>
      <input name="InsertOneRowTableFullRequest">
        <soap:body/>
      </input>
      <output name="InsertOneRowTableFullResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="InsertOneRowTableFullSql_sqlseService">
    <port name="InsertOneRowTableFullSql_sqlsePort" binding="tns:InsertOneRowTableFullSqlBinding">
      <soap:address location="http://localhost:18181/InsertOneRowTableFullSql/InsertOneRowTableFullSql/InsertOneRowTableFullSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="InsertOneRowTableFullSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="InsertOneRowTableFullSql_myrole" portType="tns:InsertOneRowTableFullSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
