DROP TABLE Task_Timer CASCADE CONSTRAINTS;
DROP TABLE Task_Assignee CASCADE CONSTRAINTS;
DROP TABLE Task_Excluded_Assignee CASCADE CONSTRAINTS;
DROP TABLE Task_Instance CASCADE CONSTRAINTS;
DROP SEQUENCE TASKASSIGNEEID;
DROP SEQUENCE TASKEXCLUDEDASSIGNEEID;
DROP SEQUENCE TASKINSTANCEID;
DROP SEQUENCE TASKTIMERID;
