<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://enterprise.netbeans.org/bpel/dynamicaddressingNMproperty/dynamicaddressingNMPA/nmPropertiesDefinitions" xmlns:tns="http://enterprise.netbeans.org/bpel/dynamicaddressingNMproperty/dynamicaddressingNMPA/nmPropertiesDefinitions" xmlns:nmp="http://www.sun.com/wsbpel/2.0/process/executable/SUNExtension/NMProperty" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns="http://localhost/Synchronous/Synchronous">
    <import namespace="http://localhost/Synchronous/Synchronous" location="Synchronous.wsdl"/>
    <types/>
    <vprop:property name="addressNMP" type="xsd:string"/>
    <vprop:propertyAlias messageType="ns:requestMessage" part="inputType" propertyName="tns:addressNMP" nmp:nmProperty="org.glassfish.openesb.outbound.address.url"/>
</definitions>
