package it.imolinfo.jbi4corba.test.testprovidercomplexinout;


/**
* it/imolinfo/jbi4corba/test/testprovidercomplexinout/EchoComplexExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoComplexInOut.idl
* Tuesday, February 5, 2008 11:09:37 AM GMT
*/


// exception
abstract public class EchoComplexExceptionHelper
{
  private static String  _id = "IDL:it/imolinfo/jbi4corba/test/testprovidercomplexinout/EchoComplexException:1.0";

  public static void insert (org.omg.CORBA.Any a, it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoComplexException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoComplexException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoStructHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (it.imolinfo.jbi4corba.test.testprovidercomplexinout.SeqEchoStructHelper.id (), "SeqEchoStruct", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "reason",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoComplexExceptionHelper.id (), "EchoComplexException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoComplexException read (org.omg.CORBA.portable.InputStream istream)
  {
    it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoComplexException value = new it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoComplexException ();
    // read and discard the repository ID
    istream.read_string ();
    value.reason = it.imolinfo.jbi4corba.test.testprovidercomplexinout.SeqEchoStructHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoComplexException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    it.imolinfo.jbi4corba.test.testprovidercomplexinout.SeqEchoStructHelper.write (ostream, value.reason);
  }

}
