package it.imolinfo.jbi4corba.test.testprovidercomplexinout;


/**
* it/imolinfo/jbi4corba/test/testprovidercomplexinout/StructOfStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoComplexInOut.idl
* Tuesday, February 5, 2008 11:09:37 AM GMT
*/

public final class StructOfStruct implements org.omg.CORBA.portable.IDLEntity
{
  public it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoStruct internalStruct = null;

  public StructOfStruct ()
  {
  } // ctor

  public StructOfStruct (it.imolinfo.jbi4corba.test.testprovidercomplexinout.EchoStruct _internalStruct)
  {
    internalStruct = _internalStruct;
  } // ctor

} // class StructOfStruct
