<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DropWrongTableSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="DropWrongTableRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="DropWrongTableRequest">
    <part name="DropWrongTableRequestPart" element="tns:DropWrongTableRequest"/>
  </message>
  <message name="DropWrongTableResponse">
    <part name="DropWrongTableResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="DropWrongTableSql_sqlsePortType">
    <operation name="DropWrongTable">
      <input name="DropWrongTableRequest" message="tns:DropWrongTableRequest"/>
      <output name="DropWrongTableResponse" message="tns:DropWrongTableResponse"/>
    </operation>
  </portType>
  <binding name="DropWrongTableSqlBinding" type="tns:DropWrongTableSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="DropWrongTable">
      <soap:operation/>
      <input name="DropWrongTableRequest">
        <soap:body/>
      </input>
      <output name="DropWrongTableResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="DropWrongTableSql_sqlseService">
    <port name="DropWrongTableSql_sqlsePort" binding="tns:DropWrongTableSqlBinding">
      <soap:address location="http://localhost:18181/DropWrongTableSql/DropWrongTableSql/DropWrongTableSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="DropWrongTableSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="DropWrongTableSql_myrole" portType="tns:DropWrongTableSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
