<?xml version="1.0" encoding="UTF-8"?>
<definitions name="FTP_PROCESS_EBCDIC_HELLO_REPLY_UTF8" targetNamespace="http://j2ee.netbeans.org/wsdl/HelloDuke_EBCDIC_2_UTF8/FTP_PROCESS_EBCDIC_HELLO_REPLY_UTF8"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ftp="http://schemas.sun.com/jbi/wsdl-extensions/ftp/" xmlns:tns="http://j2ee.netbeans.org/wsdl/HelloDuke_EBCDIC_2_UTF8/FTP_PROCESS_EBCDIC_HELLO_REPLY_UTF8" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types/>
    <message name="InboundRequestResponseMessagingOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="InboundRequestResponseMessagingOperationResponse">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="InboundRequestResponseMessagingPortType">
        <operation name="InboundRequestResponseMessagingOperation">
            <input name="input1" message="tns:InboundRequestResponseMessagingOperationRequest"/>
            <output name="output1" message="tns:InboundRequestResponseMessagingOperationResponse"/>
        </operation>
    </portType>
    <binding name="InboundRequestResponseMessagingBinding" type="tns:InboundRequestResponseMessagingPortType">
        <ftp:binding/>
        <operation name="InboundRequestResponseMessagingOperation">
            <ftp:operation/>
            <input name="input1">
                <ftp:message messageRepository="HELLODUKE_EBCDIC_UTF8" messageName="" messageNamePrefixIB="" pollIntervalMillis="5000" archive="true" protect="true" stage="true" use="literal" messageCorrelate="true" fileType="text" characterEncoding="IBM037" part="part1"/>
            </input>
            <output name="output1">
                <ftp:message messageRepository="HELLODUKE_EBCDIC_UTF8" messageName="" messageNamePrefixOB="" archive="true" protect="true" stage="true" use="literal" messageCorrelate="true" fileType="text" part="part1"/>
            </output>
        </operation>
    </binding>
    <service name="InboundRequestResponseMessagingService">
        <port name="FTP_PROCESS_EBCDIC_HELLO_REPLY_UTF8_InboundRequestResponseMessagingPort" binding="tns:InboundRequestResponseMessagingBinding">
            <ftp:address url="ftp://${test_ftp_user}:${test_ftp_password}@${test_ftp_server_name}:${test_ftp_server_port}" useUserDefinedHeuristics="false" userDefDirListStyle="" userDefDirListHeuristics="" mode="BINARY" securedFTP="None" enableCCC="false" cmdChannelTimeout="45000" dataChannelTimeout="45000" controlChannelEncoding=""/>
        </port>
    </service>
    <plnk:partnerLinkType name="FTP_PROCESS_EBCDIC_HELLO_REPLY_UTF8">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="InboundRequestResponseMessagingPortTypeRole" portType="tns:InboundRequestResponseMessagingPortType"/>
    </plnk:partnerLinkType>
</definitions>
