<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateViewSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateViewRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateViewRequest">
    <part name="CreateViewRequestPart" element="tns:CreateViewRequest"/>
  </message>
  <message name="CreateViewResponse">
    <part name="CreateViewResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="CreateViewSql_sqlsePortType">
    <operation name="CreateView">
      <input name="CreateViewRequest" message="tns:CreateViewRequest"/>
      <output name="CreateViewResponse" message="tns:CreateViewResponse"/>
    </operation>
  </portType>
  <binding name="CreateViewSqlBinding" type="tns:CreateViewSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateView">
      <soap:operation/>
      <input name="CreateViewRequest">
        <soap:body/>
      </input>
      <output name="CreateViewResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateViewSql_sqlseService">
    <port name="CreateViewSql_sqlsePort" binding="tns:CreateViewSqlBinding">
      <soap:address location="http://localhost:18181/CreateViewSql/CreateViewSql/CreateViewSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateViewSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateViewSql_myrole" portType="tns:CreateViewSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
