<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:ship="http://shipping.tracking" name="ShipmentResourceWrapper" targetNamespace="http://shipping.condition/ShipmentResourceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://shipping.condition/ShipmentResourceWrapper">
    <import location="SR.wsdl" namespace="http://shipping.tracking"/>
    <plnk:partnerLinkType name="ShipmentResourceLinkType">
        <plnk:role name="ShipmentResourceRole" portType="ship:ShipmentResourcePortType"/>
    </plnk:partnerLinkType>
</definitions>
