<?xml version="1.0" encoding="utf-8" ?>
<!-- $Header: /cvs/open-jbi-components/driver-tests/bpelse/blueprints/cmdLine/soa/bpel/BluePrint2/src/POService.wsdl,v 1.11 2010/02/04 06:08:09 fkieviet Exp $ -->
<definitions targetNamespace="http://manufacturing.org/wsdl/purchase/bp2"
             name="POService"
             xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:tns="http://manufacturing.org/wsdl/purchase/bp2"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:inv="http://manufacturing.org/xsd/inventory"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:sns="http://manufacturing.org/xsd/purchase">
    <plink:partnerLinkType name="purchasingLT">
        <plink:role name="purchaseService"
                    portType="tns:purchaseOrderPT"></plink:role>
    </plink:partnerLinkType>
    <message name="POMessage">
        <part name="purchaseOrder"
              element="sns:purchaseOrder"></part>
    </message>
    <message name="orderFaultType">
        <part name="faultInfo"
              type="xsd:string"></part>
    </message>
    <portType name="purchaseOrderPT">
        <operation name="sendPurchaseOrder">
            <input name="sendPurchaseOrderRequest" message="tns:POMessage"></input>
            <output name="sendPurchaseOrderReply" message="tns:POMessage"></output>
            <fault name="cannotCompleteOrder"
                   message="tns:orderFaultType"></fault>
        </operation>
    </portType>
    <binding name="purchaseOrderBinding"
             type="tns:purchaseOrderPT">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="sendPurchaseOrder">
            <soap:operation style="rpc"/>
            <input name="sendPurchaseOrderRequest">
                <soap:body parts="purchaseOrder"
                           use="literal"/>
            </input>
            <output name="sendPurchaseOrderReply">
                <soap:body parts="purchaseOrder"
                           use="literal"/>
            </output>
            <fault name="cannotCompleteOrder">
                <soap:fault name="faultInfo"
                            use="literal"/>
            </fault>
        </operation>
    </binding>
    <service name="purchaseOrderService">
        <port name="purchaseOrderPort"
              binding="tns:purchaseOrderBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/wsdl/purchase/PurchaseOrder/Servicelocation/bp2"/>
        </port>
    </service>
    <types>
        <xsd:schema targetNamespace="http://manufacturing.org/wsdl/purchase/bp2">
            <xsd:import schemaLocation="inventory.xsd" namespace="http://manufacturing.org/xsd/inventory"/>
        </xsd:schema>
        <xsd:schema targetNamespace="http://manufacturing.org/wsdl/purchase/bp2">
            <xsd:import schemaLocation="purchaseOrder.xsd" namespace="http://manufacturing.org/xsd/purchase"/>
        </xsd:schema>
    </types>
</definitions>
