package it.imolinfo.jbi4corba.test.testprovidersimple;


/**
* it/imolinfo/jbi4corba/test/testprovidersimple/EchoInOut.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoInOut.idl
* Monday, February 4, 2008 2:11:58 PM GMT
*/

public interface EchoInOut extends EchoInOutOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EchoInOut
