<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:scopedVar1TargetNamespace" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="scopedVar1Definition" targetNamespace="urn:scopedVar1TargetNamespace">
    <types>
        <xsd:schema xmlns:ns1="urn:scopedVar1TargetNamespace" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:scopedVar1TargetNamespace">
            <xsd:complexType name="scopedVar1Type">
                <xsd:sequence>
                    <xsd:element name="string" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="scopedVar1Message">
        <part name="scopedVar1Part" type="tns:scopedVar1Type"/>
    </message>
    <portType name="scopedVar1PortType">
        <operation name="scopedVar1Operation">
            <input message="tns:scopedVar1Message"/>
            <output message="tns:scopedVar1Message"/>
        </operation>
    </portType>
    <binding name="scopedVar1Binding" type="tns:scopedVar1PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="scopedVar1Operation">
            <soap:operation soapAction="scopedVar1Operation"/>
            <input>
                <soap:body parts="scopedVar1Part" use="literal"/>
            </input>
            <output>
                <soap:body parts="scopedVar1Part" use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="scopedVar1Service">
        <port binding="tns:scopedVar1Binding" name="scopedVar1Port">
            <soap:address location="http://localhost:${HttpDefaultPort}/service/scopedVar1"/>
        </port>
    </service>
    <plnk:partnerLinkType xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="scopedVar1ServiceLinkType">
	<plnk:role name="scopedVar1ServerRole" portType="tns:scopedVar1PortType"/>
   </plnk:partnerLinkType>
</definitions>
