<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableFullCapSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableFullCapRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableFullCapResponse">
    <part name="CreateTableFullCapResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateTableFullCapRequest">
    <part name="CreateTableFullCapRequestPart" element="tns:CreateTableFullCapRequest"/>
  </message>
  <portType name="CreateTableFullCapSql_sqlsePortType">
    <operation name="CreateTableFullCap">
      <input name="CreateTableFullCapRequest" message="tns:CreateTableFullCapRequest"/>
      <output name="CreateTableFullCapResponse" message="tns:CreateTableFullCapResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableFullCapSqlBinding" type="tns:CreateTableFullCapSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableFullCap">
      <soap:operation/>
      <input name="CreateTableFullCapRequest">
        <soap:body/>
      </input>
      <output name="CreateTableFullCapResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableFullCapSql_sqlseService">
    <port name="CreateTableFullCapSql_sqlsePort" binding="tns:CreateTableFullCapSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableFullCapSql/CreateTableFullCapSql/CreateTableFullCapSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableFullCapSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableFullCapSql_myrole" portType="tns:CreateTableFullCapSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
