<?xml version="1.0" encoding="UTF-8"?>
<definitions name="junitWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/junitWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/junitWSDL" xmlns:ns0="sun.com/soabi/snmpbc/getresponses" xmlns:ns="sun.com/soabi/snmpbc/getrequests" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/junitWSDL">
            <xsd:import namespace="sun.com/soabi/snmpbc/getresponses" schemaLocation="GetResponses.xsd"/>
            <xsd:import namespace="sun.com/soabi/snmpbc/getrequests" schemaLocation="GetRequests.xsd"/>
        </xsd:schema>
    </types>
    <message name="junitWSDLOperationRequest">
        <part name="part1" element="ns:GetRequests"/>
    </message>
    <message name="junitWSDLOperationReply">
        <part name="part1" element="ns0:GetResponses"/>
    </message>
    <portType name="junitWSDLPortType">
        <wsdl:operation name="junitWSDLOperation">
            <wsdl:input name="input1" message="tns:junitWSDLOperationRequest"/>
            <wsdl:output name="output1" message="tns:junitWSDLOperationReply"/>
        </wsdl:operation>
    </portType>
    <binding name="junitWSDLBinding" type="tns:junitWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="junitWSDLOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </binding>
    <service name="junitWSDLService">
        <wsdl:port name="junitWSDLPort" binding="tns:junitWSDLBinding">
            <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="junitWSDL1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="junitWSDLPortTypeRole" portType="tns:junitWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
