<?xml version="1.0" encoding="UTF-8"?>
<definitions name="selectwrongparamnameSQL" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="selectwrongparamnameRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="selectwrongparamnameResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="selectwrongparamnameResponse">
    <part name="selectwrongparamnameResponsePart" element="tns:selectwrongparamnameResponse"/>
  </message>
  <message name="selectwrongparamnameRequest">
    <part name="selectwrongparamnameRequestPart" element="tns:selectwrongparamnameRequest"/>
  </message>
  <portType name="selectwrongparamnameSQL_sqlsePortType">
    <operation name="selectwrongparamname">
      <input name="selectwrongparamnameRequest" message="tns:selectwrongparamnameRequest"/>
      <output name="selectwrongparamnameResponse" message="tns:selectwrongparamnameResponse"/>
    </operation>
  </portType>
  <binding name="selectwrongparamnameSQLBinding" type="tns:selectwrongparamnameSQL_sqlsePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="selectwrongparamname">
      <soap:operation style="document"/>
      <input name="selectwrongparamnameRequest">
        <soap:body use="literal"/>
      </input>
      <output name="selectwrongparamnameResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="selectwrongparamnameSQL_sqlseService">
    <port name="selectwrongparamnameSQL_sqlsePort" binding="tns:selectwrongparamnameSQLBinding">
      <soap:address location="http://localhost:18181/selectwrongparamnameSQL/selectwrongparamnameSQL/selectwrongparamnameSQL_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="selectwrongparamnameSQL_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="selectwrongparamnameSQL_myrole" portType="tns:selectwrongparamnameSQL_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
