package it.imolinfo.jbi4corba.test.testprovidercrb106.singleparam;


/**
* it/imolinfo/jbi4corba/test/testprovidercrb106/singleparam/InterfaceSingleParam.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/EchoCrb106Single.idl
* giovedì 22 novembre 2007 16.36.59 CET
*/


//==================================================
public interface InterfaceSingleParam extends InterfaceSingleParamOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfaceSingleParam
