<?xml version="1.0" encoding="UTF-8"?>
<definitions name="UpdateCondSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="UpdateCondRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="UpdateCondResponse">
    <part name="UpdateCondResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="UpdateCondRequest">
    <part name="UpdateCondRequestPart" element="tns:UpdateCondRequest"/>
  </message>
  <portType name="UpdateCondSql_sqlsePortType">
    <operation name="UpdateCond">
      <input name="UpdateCondRequest" message="tns:UpdateCondRequest"/>
      <output name="UpdateCondResponse" message="tns:UpdateCondResponse"/>
    </operation>
  </portType>
  <binding name="UpdateCondSqlBinding" type="tns:UpdateCondSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="UpdateCond">
      <soap:operation/>
      <input name="UpdateCondRequest">
        <soap:body/>
      </input>
      <output name="UpdateCondResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="UpdateCondSql_sqlseService">
    <port name="UpdateCondSql_sqlsePort" binding="tns:UpdateCondSqlBinding">
      <soap:address location="http://localhost:18181/UpdateCondSql/UpdateCondSql/UpdateCondSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="UpdateCondSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="UpdateCondSql_myrole" portType="tns:UpdateCondSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
