<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongParamTabFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongParamTabFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongParamTabFullQualResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongParamTabFullQualRequest">
    <part name="SelectWrongParamTabFullQualRequestPart" element="tns:SelectWrongParamTabFullQualRequest"/>
  </message>
  <message name="SelectWrongParamTabFullQualResponse">
    <part name="SelectWrongParamTabFullQualResponsePart" element="tns:SelectWrongParamTabFullQualResponse"/>
  </message>
  <portType name="SelectWrongParamTabFullQualSql_sqlsePortType">
    <operation name="SelectWrongParamTabFullQual">
      <input name="SelectWrongParamTabFullQualRequest" message="tns:SelectWrongParamTabFullQualRequest"/>
      <output name="SelectWrongParamTabFullQualResponse" message="tns:SelectWrongParamTabFullQualResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongParamTabFullQualSqlBinding" type="tns:SelectWrongParamTabFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongParamTabFullQual">
      <soap:operation/>
      <input name="SelectWrongParamTabFullQualRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongParamTabFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongParamTabFullQualSql_sqlseService">
    <port name="SelectWrongParamTabFullQualSql_sqlsePort" binding="tns:SelectWrongParamTabFullQualSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongParamTabFullQualSql/SelectWrongParamTabFullQualSql/SelectWrongParamTabFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongParamTabFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongParamTabFullQualSql_myrole" portType="tns:SelectWrongParamTabFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
