package it.imolinfo.jbi4corba.test.testproviderfault;

/**
* it/imolinfo/jbi4corba/test/testproviderfault/EchoComplexArrayExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test.idl
* Thursday, February 19, 2009 6:25:12 PM CET
*/

public final class EchoComplexArrayExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public it.imolinfo.jbi4corba.test.testproviderfault.EchoComplexArrayException value = null;

  public EchoComplexArrayExceptionHolder ()
  {
  }

  public EchoComplexArrayExceptionHolder (it.imolinfo.jbi4corba.test.testproviderfault.EchoComplexArrayException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = it.imolinfo.jbi4corba.test.testproviderfault.EchoComplexArrayExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    it.imolinfo.jbi4corba.test.testproviderfault.EchoComplexArrayExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return it.imolinfo.jbi4corba.test.testproviderfault.EchoComplexArrayExceptionHelper.type ();
  }

}
