<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SelectWrongParamFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="SelectWrongParamFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="SelectWrongParamFullQualResponse"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element></xsd:schema>
  </types>
  <message name="SelectWrongParamFullQualResponse">
    <part name="SelectWrongParamFullQualResponsePart" element="tns:SelectWrongParamFullQualResponse"/>
  </message>
  <message name="SelectWrongParamFullQualRequest">
    <part name="SelectWrongParamFullQualRequestPart" element="tns:SelectWrongParamFullQualRequest"/>
  </message>
  <portType name="SelectWrongParamFullQualSql_sqlsePortType">
    <operation name="SelectWrongParamFullQual">
      <input name="SelectWrongParamFullQualRequest" message="tns:SelectWrongParamFullQualRequest"/>
      <output name="SelectWrongParamFullQualResponse" message="tns:SelectWrongParamFullQualResponse"/>
    </operation>
  </portType>
  <binding name="SelectWrongParamFullQualSqlBinding" type="tns:SelectWrongParamFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="SelectWrongParamFullQual">
      <soap:operation/>
      <input name="SelectWrongParamFullQualRequest">
        <soap:body/>
      </input>
      <output name="SelectWrongParamFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="SelectWrongParamFullQualSql_sqlseService">
    <port name="SelectWrongParamFullQualSql_sqlsePort" binding="tns:SelectWrongParamFullQualSqlBinding">
      <soap:address location="http://localhost:18181/SelectWrongParamFullQualSql/SelectWrongParamFullQualSql/SelectWrongParamFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="SelectWrongParamFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="SelectWrongParamFullQualSql_myrole" portType="tns:SelectWrongParamFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
