<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SapHttpBasicAuth" targetNamespace="http://j2ee.netbeans.org/wsdl/SapHttpBasicAuth"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/" xmlns:tns="http://j2ee.netbeans.org/wsdl/SapHttpBasicAuth">
    <types/>
    <message name="SapHttpBasicAuthOperationRequest">
        <part name="AirlineID" type="xsd:string"/>
        <part name="ConnectionID" type="xsd:string"/>
        <part name="FlightDate" type="xsd:string"/>
    </message>
    <message name="SapHttpBasicAuthOperationReply">
        <part name="Airline" type="xsd:string"/>
    </message>
    <portType name="SapHttpBasicAuthPortType">
        <operation name="SapHttpBasicAuthOperation">
            <input name="input1" message="tns:SapHttpBasicAuthOperationRequest"/>
            <output name="output1" message="tns:SapHttpBasicAuthOperationReply"/>
        </operation>
    </portType>
    <binding name="SapHttpBasicAuthBinding" type="tns:SapHttpBasicAuthPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="SapHttpBasicAuthOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SapHttpBasicAuth"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/SapHttpBasicAuth"/>
            </output>
        </operation>
    </binding>
    <service name="SapHttpBasicAuthService">
        <port name="SapHttpBasicAuthPort" binding="tns:SapHttpBasicAuthBinding">
            <soap:address location="http://localhost:18181/SapHttpBasicAuthService/SapHttpBasicAuthPort"/>
        </port>
    </service>
    <plink:partnerLinkType name="SapHttpBasicAuthPartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plink:role name="SapHttpBasicAuthPortTypeRole" portType="tns:SapHttpBasicAuthPortType"/>
    </plink:partnerLinkType>
</definitions>
