<definitions targetNamespace="urn:request-response-initiateno-childTargetNamespace"
             name="request-response-initiateno-childDefinition"
             xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
             xmlns:tns="urn:request-response-initiateno-childTargetNamespace"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:slnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:parentWSDL="request-response-initiateno-parent">
    <plnk:partnerLinkType name="request-response-initiateno-childServiceLinkType"
                          xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plnk:role name="request-response-initiateno-childServerRole"
                   portType="tns:request-response-initiateno-childPortType"></plnk:role>
    </plnk:partnerLinkType>
    <vprop:property type="xsd:string"
                   name="request-response-initiateno-childProp"></vprop:property>
    <vprop:propertyAlias part="request-response-initiateno-childPart"
                        propertyName="tns:request-response-initiateno-childProp"
                        messageType="tns:request-response-initiateno-childMessage">
        <vprop:query>string</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias part="request-response-initiateno-childPart"
                        propertyName="parentWSDL:property"
                        messageType="tns:request-response-initiateno-childMessage">
        <vprop:query>string</vprop:query>
    </vprop:propertyAlias>    
    <vprop:propertyAlias propertyName="parentWSDL:property"
                        messageType="parentWSDL:request-response-initiateno-parentMessage1"
                        part="request-response-initiateno-parentPart">
            <vprop:query>/request-response-initiateno-parentElement/string</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:request-response-initiateno-childProp"
                        messageType="parentWSDL:request-response-initiateno-parentMessage1"
                        part="request-response-initiateno-parentPart">
            <vprop:query>/request-response-initiateno-parentElement/string</vprop:query>
    </vprop:propertyAlias>    
    <import location="request-response-initiateno-parent.wsdl" namespace="request-response-initiateno-parent"/>
    <types>
        <xsd:schema targetNamespace="urn:request-response-initiateno-childTargetNamespace"
                    attributeFormDefault="unqualified"
                    elementFormDefault="qualified"
                    xmlns:tns="urn:request-response-initiateno-childTargetNamespace"
                    xmlns:ns1="urn:request-response-initiateno-childTargetNamespace"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    xmlns="http://schemas.xmlsoap.org/wsdl/"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
            
                    <xsd:complexType name="request-response-initiateno-childType">
                <xsd:sequence>
                    <xsd:element type="xsd:string"
                                 name="string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="request-response-initiateno-childMessage">
        <part name="request-response-initiateno-childPart"
              type="tns:request-response-initiateno-childType"></part>
    </message>
    <portType name="request-response-initiateno-childPortType">
        <operation name="request-response-initiateno-childOperation">
            <input message="tns:request-response-initiateno-childMessage"></input>
            <output message="tns:request-response-initiateno-childMessage"></output>
        </operation>
    </portType>
    <binding name="request-response-initiateno-childBinding"
             type="tns:request-response-initiateno-childPortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="request-response-initiateno-childOperation">
            <soap:operation soapAction="request-response-initiateno-childOperation"/>
            <input>
                <soap:body parts="request-response-initiateno-childPart"
                           use="literal"/>
            </input>
            <output>
                <soap:body parts="request-response-initiateno-childPart"
                           use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="request-response-initiateno-childService">
        <port name="request-response-initiateno-childPort"
              binding="tns:request-response-initiateno-childBinding">
            <soap:address location="http://localhost:12100/service/request-response-initiateno-child"/>
        </port>
    </service>
</definitions>
