<?xml version="1.0" encoding="UTF-8"?>
<definitions name="dateTimeSubBP" targetNamespace="http://j2ee.netbeans.org/wsdl/dateTimeSubBP"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/dateTimeSubBP" xmlns:ns="http://xml.netbeans.org/schema/xmlSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/dateTimeSubBP">
            <xsd:import namespace="http://xml.netbeans.org/schema/xmlSchema" schemaLocation="xmlSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="dateTimeSubBPOperationRequest">
        <part name="part1" element="ns:newElement"/>
    </message>
    <message name="dateTimeSubBPOperationResponse">
        <part name="part1" element="ns:newElement"/>
    </message>
    <portType name="dateTimeSubBPPortType">
        <operation name="dateTimeSubBPOperation">
            <input name="input1" message="tns:dateTimeSubBPOperationRequest"/>
            <output name="output1" message="tns:dateTimeSubBPOperationResponse"/>
        </operation>
    </portType>
    <binding name="dateTimeSubBPBinding" type="tns:dateTimeSubBPPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="dateTimeSubBPOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="dateTimeSubBPService">
        <port name="dateTimeSubBPPort" binding="tns:dateTimeSubBPBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/dateTimeSubBPService/dateTimeSubBPPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="dateTimeSubBP">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="dateTimeSubBPPortTypeRole" portType="tns:dateTimeSubBPPortType"/>
    </plnk:partnerLinkType>
</definitions>
