<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             targetNamespace="http://enterprise.netbeans.org/casa/dynamicPartnerLinkJBI"
             xmlns:myns="http://enterprise.netbeans.org/casa/dynamicPartnerLinkJBI" xmlns:ns="http://j2ee.netbeans.org/wsdl/provider" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/">
    <import namespace="http://j2ee.netbeans.org/wsdl/provider" location="../jbiServiceUnits/dynamicPartnerLinkBPEL/provider.wsdl"/>
    <portType name="dummyCasaPortType"/>
    <binding name="casaBinding1" type="ns:providerPortType">
        <file:binding/>
        <wsdl:operation name="providerOperation">
            <file:operation/>
            <wsdl:input name="input1">
                <file:message use="literal" fileName="test.xml" pollingInterval="1000" multipleRecordsPerFile="true" addEOL="true"/>
            </wsdl:input>
        </wsdl:operation>
    </binding>
    <service name="casaService1">
        <port name="casaPort1" binding="myns:casaBinding1">
            <file:address fileDirectory="C:\Temp"/>
        </port>
    </service>
</definitions>
