<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateViewFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateViewFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateViewFullQualResponse">
    <part name="CreateViewFullQualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateViewFullQualRequest">
    <part name="CreateViewFullQualRequestPart" element="tns:CreateViewFullQualRequest"/>
  </message>
  <portType name="CreateViewFullQualSql_sqlsePortType">
    <operation name="CreateViewFullQual">
      <input name="CreateViewFullQualRequest" message="tns:CreateViewFullQualRequest"/>
      <output name="CreateViewFullQualResponse" message="tns:CreateViewFullQualResponse"/>
    </operation>
  </portType>
  <binding name="CreateViewFullQualSqlBinding" type="tns:CreateViewFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateViewFullQual">
      <soap:operation/>
      <input name="CreateViewFullQualRequest">
        <soap:body/>
      </input>
      <output name="CreateViewFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateViewFullQualSql_sqlseService">
    <port name="CreateViewFullQualSql_sqlsePort" binding="tns:CreateViewFullQualSqlBinding">
      <soap:address location="http://localhost:18181/CreateViewFullQualSql/CreateViewFullQualSql/CreateViewFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateViewFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateViewFullQualSql_myrole" portType="tns:CreateViewFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
