<definitions targetNamespace="http://stc.com/xsddatatype10" 
    name="xsddatatype10" 
    xmlns:tns="http://stc.com/xsddatatype10"    
    xmlns:ns1="urn:SampleXSD2"     
    xmlns:slnk1="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
    xmlns:tns0="http://stc.com/xsddatatype10" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/">

     <import location="SampleXSD2.xsd" namespace="urn:SampleXSD2"/>     
    <message name="xsddatatype10">
        <part name="part" type="ns1:USAddressType"/>
    </message>
    <portType name="xsddatatype10">
        <operation name="xsddatatype10">
            <input message="tns:xsddatatype10"/>
            <output message="tns:xsddatatype10"/>
        </operation>
    </portType>
    <binding name="Binding" type="tns:xsddatatype10">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="xsddatatype10">
            <soap:operation soapAction="xsddatatype10"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="xsddatatype10Service">
        <port name="port" binding="tns:Binding">
            <soap:address location="http://localhost:${HttpDefaultPort}/xsddatatype10"/>
        </port>
    </service>
    <plnk:partnerLinkType name="SLT" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plnk:role name="server" portType="tns:xsddatatype10"/>
    </plnk:partnerLinkType>
</definitions>
