<definitions targetNamespace="http://stc.com/xsddatatype12" 
    name="xsddatatype12" 
    xmlns:tns="http://stc.com/xsddatatype12" 
    xmlns:ns1="urn:SampleXSD" 
    xmlns:slnk1="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
    xmlns:tns0="http://stc.com/xsddatatype12" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/">
    
        <import location="SampleXSD.xsd" namespace="urn:SampleXSD"/>
	<message name="xsddatatype12">
		<part name="part" element="ns1:Item"/>
	</message>
	<portType name="xsddatatype12">
		<operation name="xsddatatype12">
			<input message="tns:xsddatatype12"/>
			<output message="tns:xsddatatype12"/>
		</operation>
	</portType>
	<binding name="Binding" type="tns:xsddatatype12">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="xsddatatype12">
			<soap:operation soapAction="xsddatatype12"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="xsddatatype12Service">
		<port name="port" binding="tns:Binding">
			<soap:address location="http://localhost:${HttpDefaultPort}/xsddatatype12"/>
		</port>
	</service>
	<plnk:partnerLinkType name="SLT" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
		<plnk:role name="server" portType="tns:xsddatatype12"/>
	</plnk:partnerLinkType>
</definitions>
