<definitions targetNamespace="http://stc.com/xsddatatype7" 
    name="xsddatatype7" 
    xmlns:tns="http://stc.com/xsddatatype7" 
    xmlns:ns1="urn:SampleXSD"      
    xmlns:slnk1="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
    xmlns:tns0="http://stc.com/xsddatatype7" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/">
    
    <import location="SampleXSD.xsd" namespace="urn:SampleXSD"/>     
    <message name="xsddatatype7">
        <part name="part" element="ns1:person"/>
    </message>
    <portType name="xsddatatype7">
        <operation name="xsddatatype7">
            <input message="tns:xsddatatype7"/>
            <output message="tns:xsddatatype7"/>
        </operation>
    </portType>
    <binding name="Binding" type="tns:xsddatatype7">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="xsddatatype7">
            <soap:operation soapAction="xsddatatype7"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="xsddatatype7Service">
        <port name="port" binding="tns:Binding">
            <soap:address location="http://localhost:${HttpDefaultPort}/xsddatatype7"/>
        </port>
    </service>
    <plnk:partnerLinkType name="SLT" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plnk:role name="server" portType="tns:xsddatatype7"/>
    </plnk:partnerLinkType>
</definitions>
