<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/UpdateTrigger"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/UpdateTrigger" name="UpdateTrigger" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" xmlns:jms="http://schemas.sun.com/jbi/wsdl-extensions/jms/">
    <wsdl:types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/UpdateTrigger">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="TestTable.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="UpdateTriggerOperationRequest">
        <wsdl:part name="part1" element="ns:TestTable"/>
    </wsdl:message>
    <wsdl:message name="UpdateTriggerOperationReply">
        <wsdl:part name="part1" type="xsd:int"/>
    </wsdl:message>
    <wsdl:portType name="UpdateTriggerPortType">
        <wsdl:operation name="UpdateTriggerOperation">
            <wsdl:input name="input1" message="tns:UpdateTriggerOperationRequest"/>
            <wsdl:output name="output1" message="tns:UpdateTriggerOperationReply"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="UpdateTriggerBinding" type="tns:UpdateTriggerPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="UpdateTriggerOperation">
            <soap:operation style="document"/>
            <wsdl:input name="input1">
                <soap:body use="literal" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://j2ee.netbeans.org/wsdl/UpdateTrigger" parts="part1"/>
            </wsdl:input>
            <wsdl:output name="output1">
                <soap:body use="literal" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://j2ee.netbeans.org/wsdl/UpdateTrigger" parts="part1"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="UpdateTriggerService">
        <wsdl:port name="UpdateTriggerPort" binding="tns:UpdateTriggerBinding">
            <soap:address location="http://localhost:18181/UpdateTriggerService/UpdateTriggerPort"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="UpdateTriggerPartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="UpdateTriggerPortTypeRole" portType="tns:UpdateTriggerPortType"/>
    </plnk:partnerLinkType>
</definitions>
