//IDL
#include "RttiPragmaPrefixIncluded.idl"
#pragma prefix "3yy4.321"
module it{
module imolinfo{
module jbi4corba{
module test{
module rtti{

	interface rtti_test {
		//union
		string enum_echo1(in rttitypes::ThirdUnion msg);
		rttitypes::ThirdUnion enum_echo2(inout rttitypes::SecondUnion msg);
		rttitypes::ComplexStruct1 enum_echo3(in string msg);
		string enum_echo4(in rttitypes::ComplexStruct1 msg);
		string enum_echo5(inout rttitypes::ComplexStruct1 msg);
		rttitypes::ComplexStruct1 enum_echo6(in string msg);
		rttitypes::ArrayComplexStruct1 enum_echo7(in string msg);
		rttitypes::SecondUnion enum_echo8(in string msg)
		raises(rttitypes::EchoUnionException);
		string enum_echo9(in rttitypes::ArrayComplexStruct1 msg);
		//enum
		rttitypes::EchoComplexEnum echoEnum(in rttitypes::EchoComplexEnum e);
		//any
		string any_echo1(inout any msg);
		any any_echo2(in any msg) raises(rttitypes::EchoAnyException);
		rttitypes::ComplexStruct2 any_echo3(in rttitypes::TempUnion1 msg);
		rttitypes::ArrayOfAny any_echo4(inout rttitypes::ComplexStruct2 msg);
		};

};};};};}; 
