<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="VariableLevelhelloWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/VariableLevelhelloWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/VariableLevelhelloWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://example.org/mime/VariableLevelCopy">
    <import location="VariableLevelhello.wsdl" namespace="http://example.org/mime/VariableLevelCopy"/>
    <plnk:partnerLinkType name="VariableLevelHelloLinkType">
        <plnk:role name="VariableLevelHelloRole" portType="ns:VariableLevelHello"/>
    </plnk:partnerLinkType>
</definitions>
