<?xml version="1.0" encoding="UTF-8"?>
<definitions name="UpdateAllColumnsSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="UpdateAllColumnsRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="UpdateAllColumnsResponse">
    <part name="UpdateAllColumnsResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="UpdateAllColumnsRequest">
    <part name="UpdateAllColumnsRequestPart" element="tns:UpdateAllColumnsRequest"/>
  </message>
  <portType name="UpdateAllColumnsSql_sqlsePortType">
    <operation name="UpdateAllColumns">
      <input name="UpdateAllColumnsRequest" message="tns:UpdateAllColumnsRequest"/>
      <output name="UpdateAllColumnsResponse" message="tns:UpdateAllColumnsResponse"/>
    </operation>
  </portType>
  <binding name="UpdateAllColumnsSqlBinding" type="tns:UpdateAllColumnsSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="UpdateAllColumns">
      <soap:operation/>
      <input name="UpdateAllColumnsRequest">
        <soap:body/>
      </input>
      <output name="UpdateAllColumnsResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="UpdateAllColumnsSql_sqlseService">
    <port name="UpdateAllColumnsSql_sqlsePort" binding="tns:UpdateAllColumnsSqlBinding">
      <soap:address location="http://localhost:18181/UpdateAllColumnsSql/UpdateAllColumnsSql/UpdateAllColumnsSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="UpdateAllColumnsSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="UpdateAllColumnsSql_myrole" portType="tns:UpdateAllColumnsSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
