<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TxnTstDriver" targetNamespace="http://txn.tst.sun.com/TxnTstDriver/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://txn.tst.sun.com/TxnTstDriver/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="TxnTstDriverOperationRequest">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <message name="TxnTstDriverOperationResponse">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <portType name="TxnTstDriverInterface">
        <operation name="TxnTstDriverOperation">
            <input name="input1" message="tns:TxnTstDriverOperationRequest"/>
            <output name="output1" message="tns:TxnTstDriverOperationResponse"/>
        </operation>
    </portType>
</definitions>
