<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AlterNonEmptyTableFullSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="AlterNonEmptyTableFullRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="AlterNonEmptyTableFullResponse">
    <part name="AlterNonEmptyTableFullResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="AlterNonEmptyTableFullRequest">
    <part name="AlterNonEmptyTableFullRequestPart" element="tns:AlterNonEmptyTableFullRequest"/>
  </message>
  <portType name="AlterNonEmptyTableFullSql_sqlsePortType">
    <operation name="AlterNonEmptyTableFull">
      <input name="AlterNonEmptyTableFullRequest" message="tns:AlterNonEmptyTableFullRequest"/>
      <output name="AlterNonEmptyTableFullResponse" message="tns:AlterNonEmptyTableFullResponse"/>
    </operation>
  </portType>
  <binding name="AlterNonEmptyTableFullSqlBinding" type="tns:AlterNonEmptyTableFullSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="AlterNonEmptyTableFull">
      <soap:operation/>
      <input name="AlterNonEmptyTableFullRequest">
        <soap:body/>
      </input>
      <output name="AlterNonEmptyTableFullResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="AlterNonEmptyTableFullSql_sqlseService">
    <port name="AlterNonEmptyTableFullSql_sqlsePort" binding="tns:AlterNonEmptyTableFullSqlBinding">
      <soap:address location="http://localhost:18181/AlterNonEmptyTableFullSql/AlterNonEmptyTableFullSql/AlterNonEmptyTableFullSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="AlterNonEmptyTableFullSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="AlterNonEmptyTableFullSql_myrole" portType="tns:AlterNonEmptyTableFullSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
