<?xml version="1.0" encoding="UTF-8"?>
<definitions name="attr" targetNamespace="http://j2ee.netbeans.org/wsdl/Soap12Attribute/attr"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Soap12Attribute/attr" xmlns:ns="http://xml.netbeans.org/schema/attr" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/Soap12Attribute/attr">
            <xsd:import namespace="http://xml.netbeans.org/schema/attr" schemaLocation="attr.xsd"/>
        </xsd:schema>
    </types>
    <message name="attrOperationRequest">
        <part name="part1" element="ns:x"/>
    </message>
    <message name="attrOperationResponse">
        <part name="part1" element="ns:x"/>
    </message>
    <portType name="attrPortType">
        <operation name="attrOperation">
            <input name="input1" message="tns:attrOperationRequest"/>
            <output name="output1" message="tns:attrOperationResponse"/>
        </operation>
    </portType>
    <binding name="attrBinding" type="tns:attrPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="attrOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="attrService">
        <port name="attrPort" binding="tns:attrBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/attrService/attrPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="attr">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="attrPortTypeRole" portType="tns:attrPortType"/>
    </plnk:partnerLinkType>
</definitions>
