<?xml version="1.0" encoding="UTF-8"?>
<definitions name="rpcAttr12" targetNamespace="http://j2ee.netbeans.org/wsdl/Soap12Attribute/rpcAttr12"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Soap12Attribute/rpcAttr12" xmlns:ns="http://xml.netbeans.org/schema/attr" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/Soap12Attribute/rpcAttr12">
            <xsd:import namespace="http://xml.netbeans.org/schema/attr" schemaLocation="attr.xsd"/>
        </xsd:schema>
    </types>
    <message name="rpcAttr12OperationRequest">
        <part name="part1" type="ns:xyz"/>
    </message>
    <message name="rpcAttr12OperationResponse">
        <part name="part1" type="ns:xyz"/>
    </message>
    <portType name="rpcAttr12PortType">
        <operation name="rpcAttr12Operation">
            <input name="input1" message="tns:rpcAttr12OperationRequest"/>
            <output name="output1" message="tns:rpcAttr12OperationResponse"/>
        </operation>
    </portType>
    <binding name="rpcAttr12Binding" type="tns:rpcAttr12PortType">
        <soap12:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="rpcAttr12Operation">
            <soap12:operation/>
            <input name="input1">
                <soap12:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/Soap12Attribute/rpcAttr12"/>
            </input>
            <output name="output1">
                <soap12:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/Soap12Attribute/rpcAttr12"/>
            </output>
        </operation>
    </binding>
    <service name="rpcAttr12Service">
        <port name="rpcAttr12Port" binding="tns:rpcAttr12Binding">
            <soap12:address location="http://localhost:${HttpDefaultPort}/rpcAttr12Service/rpcAttr12Port"/>
        </port>
    </service>
    <plnk:partnerLinkType name="rpcAttr12">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="rpcAttr12PortTypeRole" portType="tns:rpcAttr12PortType"/>
    </plnk:partnerLinkType>
</definitions>
