<?xml version="1.0" encoding="UTF-8"?>
<definitions name="UpdateWrongColFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="UpdateWrongColFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="UpdateWrongColFullQualResponse">
    <part name="UpdateWrongColFullQualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="UpdateWrongColFullQualRequest">
    <part name="UpdateWrongColFullQualRequestPart" element="tns:UpdateWrongColFullQualRequest"/>
  </message>
  <portType name="UpdateWrongColFullQualSql_sqlsePortType">
    <operation name="UpdateWrongColFullQual">
      <input name="UpdateWrongColFullQualRequest" message="tns:UpdateWrongColFullQualRequest"/>
      <output name="UpdateWrongColFullQualResponse" message="tns:UpdateWrongColFullQualResponse"/>
    </operation>
  </portType>
  <binding name="UpdateWrongColFullQualSqlBinding" type="tns:UpdateWrongColFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="UpdateWrongColFullQual">
      <soap:operation/>
      <input name="UpdateWrongColFullQualRequest">
        <soap:body/>
      </input>
      <output name="UpdateWrongColFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="UpdateWrongColFullQualSql_sqlseService">
    <port name="UpdateWrongColFullQualSql_sqlsePort" binding="tns:UpdateWrongColFullQualSqlBinding">
      <soap:address location="http://localhost:18181/UpdateWrongColFullQualSql/UpdateWrongColFullQualSql/UpdateWrongColFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="UpdateWrongColFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="UpdateWrongColFullQualSql_myrole" portType="tns:UpdateWrongColFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
