-- Drop the tables and the indexes. Note that you need to be connected using the same
-- username/password to do this.
DROP INDEX ENGINECORRIDINDEX;
DROP INDEX STATESTATUSINDEX;
DROP INDEX STATEENGINEIDINDEX;
DROP INDEX CRMPINDEX;
DROP INDEX ENGINELASTUT;
DROP INDEX CRMPREPLYVARINDEX;
DROP INDEX VARIABLEFKEY;
DROP INDEX VARIABLEATTACHMENTFKEY;
DROP INDEX FOREACHFKEY;
DROP INDEX INSTCORRFKEY;
DROP INDEX LCPFKEY;
DROP INDEX SCOPEFKEY;
DROP INDEX CRMPFKEY;
DROP INDEX SIMPLEVARFKEY;
DROP INDEX PARTNERLINKFKEY;
DROP INDEX NMPROPERTYFKEY;
DROP INDEX NMSIMPLEPROPERTYFKEY;

DROP TABLE CRMP;
DROP TABLE SCOPE;
DROP TABLE LASTCHECKPOINT;
DROP TABLE ENGINECORRELATION;
DROP TABLE INSTANCECORRELATION;
DROP TABLE FOREACH;
DROP TABLE VARIABLE;
DROP TABLE SIMPLEVARIABLE;
DROP TABLE NMPROPERTY;
DROP TABLE NMSIMPLEPROPERTY;
DROP TABLE VARIABLEATTACHMENT;
DROP TABLE WAITINGIMA;
DROP TABLE EVENTHANDLER;
DROP TABLE STATE;
DROP TABLE ENGINE;
DROP TABLE PARTNERLINK;
DROP TABLE OUTSTANDINGMSGEX;
