<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DropAllRowsFullSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="DropAllRowsFullRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="DropAllRowsFullResponse">
    <part name="DropAllRowsFullResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="DropAllRowsFullRequest">
    <part name="DropAllRowsFullRequestPart" element="tns:DropAllRowsFullRequest"/>
  </message>
  <portType name="DropAllRowsFullSql_sqlsePortType">
    <operation name="DropAllRowsFull">
      <input name="DropAllRowsFullRequest" message="tns:DropAllRowsFullRequest"/>
      <output name="DropAllRowsFullResponse" message="tns:DropAllRowsFullResponse"/>
    </operation>
  </portType>
  <binding name="DropAllRowsFullSqlBinding" type="tns:DropAllRowsFullSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="DropAllRowsFull">
      <soap:operation/>
      <input name="DropAllRowsFullRequest">
        <soap:body/>
      </input>
      <output name="DropAllRowsFullResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="DropAllRowsFullSql_sqlseService">
    <port name="DropAllRowsFullSql_sqlsePort" binding="tns:DropAllRowsFullSqlBinding">
      <soap:address location="http://localhost:18181/DropAllRowsFullSql/DropAllRowsFullSql/DropAllRowsFullSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="DropAllRowsFullSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="DropAllRowsFullSql_myrole" portType="tns:DropAllRowsFullSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
