<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DeleteCondSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="DeleteCondRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="DeleteCondResponse">
    <part name="DeleteCondResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="DeleteCondRequest">
    <part name="DeleteCondRequestPart" element="tns:DeleteCondRequest"/>
  </message>
  <portType name="DeleteCondSql_sqlsePortType">
    <operation name="DeleteCond">
      <input name="DeleteCondRequest" message="tns:DeleteCondRequest"/>
      <output name="DeleteCondResponse" message="tns:DeleteCondResponse"/>
    </operation>
  </portType>
  <binding name="DeleteCondSqlBinding" type="tns:DeleteCondSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="DeleteCond">
      <soap:operation/>
      <input name="DeleteCondRequest">
        <soap:body/>
      </input>
      <output name="DeleteCondResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="DeleteCondSql_sqlseService">
    <port name="DeleteCondSql_sqlsePort" binding="tns:DeleteCondSqlBinding">
      <soap:address location="http://localhost:18181/DeleteCondSql/DeleteCondSql/DeleteCondSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="DeleteCondSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="DeleteCondSql_myrole" portType="tns:DeleteCondSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
