<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Assign_NoElement" targetNamespace="http://j2ee.netbeans.org/wsdl/Assign_NoElement"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:ns="http://xml.netbeans.org/schema/MessageType" 
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://j2ee.netbeans.org/wsdl/Assign_NoElement">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/Assign_NoElement">
        <xsd:import namespace="http://xml.netbeans.org/schema/MessageType" schemaLocation="MessageType.xsd"/>
        </xsd:schema>
    </types>
    <message name="Assign_NoElementOperationRequest">
        <part name="InPart" element="ns:xsdMessage"/>
    </message>
    <message name="Assign_NoElementOperationReply">
        <part name="OutPart" element="ns:xsdMessage"/>
    </message>
    <message name="Assign_NoElementOperationFault">
        <part name="FaultPart" type="xsd:string"/>
    </message>
    <portType name="Assign_NoElementPortType">
        <operation name="Assign_NoElementOperation">
            <input name="input1" message="tns:Assign_NoElementOperationRequest"/>
            <output name="output1" message="tns:Assign_NoElementOperationReply"/>
        </operation>
    </portType>
    <binding name="Assign_NoElementBinding" type="tns:Assign_NoElementPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Assign_NoElementOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="Assign_NoElementService">
        <port name="Assign_NoElementPort" binding="tns:Assign_NoElementBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/SelectionFailure/Assign_NoElement/FailureInAssign/Assign_NoElementService/Assign_NoElementPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="Assign_NoElementPlink">
        <plnk:role name="Assign_NoElementPortTypeRole" portType="tns:Assign_NoElementPortType"/>
    </plnk:partnerLinkType>
</definitions>
