<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="jcdLoadBuiltInManuWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/jcdLoadBuiltInManuWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/jcdLoadBuiltInManuWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="urn:stc:egate:jce:prjPfizerSupplyChainEAP_CAPS_prjLoadTracker_TechnicalSvcs_OTDs_Custom_jcdLoadBuiltInManu">
    <import location="jcdLoadBuiltInManu.wsdl" namespace="urn:stc:egate:jce:prjPfizerSupplyChainEAP_CAPS_prjLoadTracker_TechnicalSvcs_OTDs_Custom_jcdLoadBuiltInManu"/>
    <plnk:partnerLinkType name="ExecuteLinkType">
        <plnk:role name="ExecuteRole" portType="ns:ExecutePortType"/>
    </plnk:partnerLinkType>
</definitions>
