<?xml version="1.0" encoding="UTF-8"?>
<definitions name="UpdateAllSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="UpdateAllRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="UpdateAllRequest">
    <part name="UpdateAllRequestPart" element="tns:UpdateAllRequest"/>
  </message>
  <message name="UpdateAllResponse">
    <part name="UpdateAllResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="UpdateAllSql_sqlsePortType">
    <operation name="UpdateAll">
      <input name="UpdateAllRequest" message="tns:UpdateAllRequest"/>
      <output name="UpdateAllResponse" message="tns:UpdateAllResponse"/>
    </operation>
  </portType>
  <binding name="UpdateAllSqlBinding" type="tns:UpdateAllSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="UpdateAll">
      <soap:operation/>
      <input name="UpdateAllRequest">
        <soap:body/>
      </input>
      <output name="UpdateAllResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="UpdateAllSql_sqlseService">
    <port name="UpdateAllSql_sqlsePort" binding="tns:UpdateAllSqlBinding">
      <soap:address location="http://localhost:18181/UpdateAllSql/UpdateAllSql/UpdateAllSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="UpdateAllSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="UpdateAllSql_myrole" portType="tns:UpdateAllSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
