<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://j2ee.netbeans.org/wsdl/SoapOneWayOutDoc"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/SoapOneWayOutDoc" name="SoapOneWayOutDoc" xmlns:ns="http://xml.netbeans.org/schema/ElementSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/SoapOneWayOutDoc">
            <xsd:import namespace="http://xml.netbeans.org/schema/ElementSchema" schemaLocation="ElementSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="SoapOneWayOutDocOperationRequest">
        <part name="part1" element="ns:requestElement"/>
    </message>
    <portType name="SoapOneWayOutDocPortType">
        <wsdl:operation name="SoapOneWayOutDocOperation">
            <wsdl:input name="input1" message="tns:SoapOneWayOutDocOperationRequest"/>
        </wsdl:operation>
    </portType>
    <binding name="SoapOneWayOutDocBinding" type="tns:SoapOneWayOutDocPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SoapOneWayOutDocOperation">
            <soap:operation/>
            <wsdl:input name="input1">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </binding>
    <service name="SoapOneWayOutDocService">
        <wsdl:port name="SoapOneWayOutDocPort" binding="tns:SoapOneWayOutDocBinding">
            <soap:address location="http://localhost:18181/SoapOneWayOutDocService/SoapOneWayOutDocPort"/>
        </wsdl:port>
    </service>
    <plnk:partnerLinkType name="SoapOneWayOutDocPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SoapOneWayOutDocPortTypeRole" portType="tns:SoapOneWayOutDocPortType"/>
    </plnk:partnerLinkType>
</definitions>
