package rttitypes;

/**
* rttitypes/ComplexStruct2Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RttiPragmaPrefix.idl
* Wednesday, July 22, 2009 4:13:00 PM CEST
*/

public final class ComplexStruct2Holder implements org.omg.CORBA.portable.Streamable
{
  public rttitypes.ComplexStruct2 value = null;

  public ComplexStruct2Holder ()
  {
  }

  public ComplexStruct2Holder (rttitypes.ComplexStruct2 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rttitypes.ComplexStruct2Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rttitypes.ComplexStruct2Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rttitypes.ComplexStruct2Helper.type ();
  }

}
