package rttitypes;


/**
* rttitypes/EchoUnionExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RttiPragmaPrefix.idl
* Wednesday, July 22, 2009 4:13:00 PM CEST
*/

abstract public class EchoUnionExceptionHelper
{
  private static String  _id = "IDL:3hh4.123/rttitypes/EchoUnionException:1.0";

  public static void insert (org.omg.CORBA.Any a, rttitypes.EchoUnionException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static rttitypes.EchoUnionException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = rttitypes.ThirdUnionHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "reason",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (rttitypes.EchoUnionExceptionHelper.id (), "EchoUnionException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static rttitypes.EchoUnionException read (org.omg.CORBA.portable.InputStream istream)
  {
    rttitypes.EchoUnionException value = new rttitypes.EchoUnionException ();
    // read and discard the repository ID
    istream.read_string ();
    value.reason = rttitypes.ThirdUnionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, rttitypes.EchoUnionException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    rttitypes.ThirdUnionHelper.write (ostream, value.reason);
  }

}
