package rttitypes;

/**
* rttitypes/TempUnionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RttiPragmaPrefix.idl
* Wednesday, July 22, 2009 4:13:00 PM CEST
*/

public final class TempUnionHolder implements org.omg.CORBA.portable.Streamable
{
  public rttitypes.TempUnion value = null;

  public TempUnionHolder ()
  {
  }

  public TempUnionHolder (rttitypes.TempUnion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rttitypes.TempUnionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rttitypes.TempUnionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rttitypes.TempUnionHelper.type ();
  }

}
