package rttitypes;


/**
* rttitypes/ThirdUnionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RttiPragmaPrefix.idl
* Wednesday, July 22, 2009 4:13:00 PM CEST
*/

abstract public class ThirdUnionHelper
{
  private static String  _id = "IDL:3hh4.123/rttitypes/ThirdUnion:1.0";

  public static void insert (org.omg.CORBA.Any a, rttitypes.ThirdUnion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static rttitypes.ThirdUnion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [4];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for primo (case label 1)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)1);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
      _members0[0] = new org.omg.CORBA.UnionMember (
        "primo",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for secondo (case label 2)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)2);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
      _members0[1] = new org.omg.CORBA.UnionMember (
        "secondo",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for third (case label 3)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)3);
      _tcOf_members0 = rttitypes.FirstUnionHelper.type ();
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
      _members0[2] = new org.omg.CORBA.UnionMember (
        "third",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for altro (Default case)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_octet ((byte)0); // default member label
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
      _members0[3] = new org.omg.CORBA.UnionMember (
        "altro",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (rttitypes.ThirdUnionHelper.id (), "ThirdUnion", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static rttitypes.ThirdUnion read (org.omg.CORBA.portable.InputStream istream)
  {
    rttitypes.ThirdUnion value = new rttitypes.ThirdUnion ();
    short _dis0 = (short)0;
    _dis0 = istream.read_short ();
    switch (_dis0)
    {
      case 1:
        int _primo = (int)0;
        _primo = istream.read_long ();
        value.primo (_primo);
        break;
      case 2:
        short _secondo = (short)0;
        _secondo = istream.read_short ();
        value.secondo (_secondo);
        break;
      case 3:
        rttitypes.FirstUnion _third[] = null;
        int _len1 = istream.read_long ();
        _third = new rttitypes.FirstUnion[_len1];
        for (int _o2 = 0;_o2 < _third.length; ++_o2)
          _third[_o2] = rttitypes.FirstUnionHelper.read (istream);
        value.third (_third);
        break;
      default:
        boolean _altro = false;
        _altro = istream.read_boolean ();
        value.altro (_dis0, _altro);
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, rttitypes.ThirdUnion value)
  {
    ostream.write_short (value.discriminator ());
    switch (value.discriminator ())
    {
      case 1:
        ostream.write_long (value.primo ());
        break;
      case 2:
        ostream.write_short (value.secondo ());
        break;
      case 3:
        ostream.write_long (value.third ().length);
        for (int _i0 = 0;_i0 < value.third ().length; ++_i0)
          rttitypes.FirstUnionHelper.write (ostream, value.third ()[_i0]);
        break;
      default:
        ostream.write_boolean (value.altro ());
        break;
    }
  }

}
