//From: ftp://ftp.3gpp.org/Specs/2005-03/Rel-6/32_series/32303-630.zip
//File: NotificationIRPConstDefs.idl

#ifndef _NOTIFICATIONIRPCONSTDEFS_IDL_
#define _NOTIFICATIONIRPCONSTDEFS_IDL_

#include "ManagedGenericIRPConstDefs.idl"

// This statement must appear after all include statements
#pragma prefix "3gppsa5.org"


/* ## Module: NotificationIRPConstDefs
This module contains definitions specific for Notification IRP.
================================================================
*/
module NotificationIRPConstDefs
{


   /*
   Define the parameters (in the notification header) specified in
   the Notification IRP: IS. 
   */
   interface AttributeNameValue
   {
      const string NOTIFICATION_ID = "a";
      const string EVENT_TIME = "b";
      const string SYSTEM_DN = "c";
      const string MANAGED_OBJECT_CLASS = "d";
      const string MANAGED_OBJECT_INSTANCE = "e";
   };

   /*
   It defines the notification categories.
   A notification category is identified by the IRP name and its version number.
   */
   typedef ManagedGenericIRPConstDefs::VersionNumberSet NotificationCategorySet;

   /*
   It defines the notification types of a particular notification category.
   */
   typedef sequence <string> NotificationTypePerNotificationCategory;

   /*
   This sequence identifies all notification types of all notification
   categories identified by NotificationCategorySet.  The number of elements
   in this sequence shall be identical to that of NotificationCategorySet.
   */
   typedef sequence <NotificationTypePerNotificationCategory>
       NotificationTypesSet;

   /*
   It defines a sequence of SubscriptionIds.
   */
   typedef string SubscriptionId;
   typedef sequence <SubscriptionId> SubscriptionIdSet;

   /*
   This indicates if the subscription is Active (not suspended), Suspended,
   or Invalid.
   */
   enum SubscriptionState {ACTIVE, SUSPENDED, INVALID};
};

#endif  // _NOTIFICATIONIRPCONSTDEFS_IDL_

