<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateTableDupFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="CreateTableDupFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="CreateTableDupFullQualResponse">
    <part name="CreateTableDupFullQualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <message name="CreateTableDupFullQualRequest">
    <part name="CreateTableDupFullQualRequestPart" element="tns:CreateTableDupFullQualRequest"/>
  </message>
  <portType name="CreateTableDupFullQualSql_sqlsePortType">
    <operation name="CreateTableDupFullQual">
      <input name="CreateTableDupFullQualRequest" message="tns:CreateTableDupFullQualRequest"/>
      <output name="CreateTableDupFullQualResponse" message="tns:CreateTableDupFullQualResponse"/>
    </operation>
  </portType>
  <binding name="CreateTableDupFullQualSqlBinding" type="tns:CreateTableDupFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateTableDupFullQual">
      <soap:operation/>
      <input name="CreateTableDupFullQualRequest">
        <soap:body/>
      </input>
      <output name="CreateTableDupFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="CreateTableDupFullQualSql_sqlseService">
    <port name="CreateTableDupFullQualSql_sqlsePort" binding="tns:CreateTableDupFullQualSqlBinding">
      <soap:address location="http://localhost:18181/CreateTableDupFullQualSql/CreateTableDupFullQualSql/CreateTableDupFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="CreateTableDupFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="CreateTableDupFullQualSql_myrole" portType="tns:CreateTableDupFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
