<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InsertWrongTypeFullQualSql" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.sun.jbi/sqlse/sqlseengine" xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://com.sun.jbi/sqlse/sqlseengine" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="InsertWrongTypeFullQualRequest"><xsd:complexType><xsd:sequence/></xsd:complexType></xsd:element><xsd:element name="numRowsEffected" type="xsd:int"/></xsd:schema>
  </types>
  <message name="InsertWrongTypeFullQualRequest">
    <part name="InsertWrongTypeFullQualRequestPart" element="tns:InsertWrongTypeFullQualRequest"/>
  </message>
  <message name="InsertWrongTypeFullQualResponse">
    <part name="InsertWrongTypeFullQualResponsePart" element="tns:numRowsEffected"/>
  </message>
  <portType name="InsertWrongTypeFullQualSql_sqlsePortType">
    <operation name="InsertWrongTypeFullQual">
      <input name="InsertWrongTypeFullQualRequest" message="tns:InsertWrongTypeFullQualRequest"/>
      <output name="InsertWrongTypeFullQualResponse" message="tns:InsertWrongTypeFullQualResponse"/>
    </operation>
  </portType>
  <binding name="InsertWrongTypeFullQualSqlBinding" type="tns:InsertWrongTypeFullQualSql_sqlsePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="InsertWrongTypeFullQual">
      <soap:operation/>
      <input name="InsertWrongTypeFullQualRequest">
        <soap:body/>
      </input>
      <output name="InsertWrongTypeFullQualResponse">
        <soap:body/>
      </output>
    </operation>
  </binding>
  <service name="InsertWrongTypeFullQualSql_sqlseService">
    <port name="InsertWrongTypeFullQualSql_sqlsePort" binding="tns:InsertWrongTypeFullQualSqlBinding">
      <soap:address location="http://localhost:18181/InsertWrongTypeFullQualSql/InsertWrongTypeFullQualSql/InsertWrongTypeFullQualSql_sqlsePort"/>
    </port>
  </service>
    <plink:partnerLinkType name="InsertWrongTypeFullQualSql_sqlsePartnerLinkType" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
        <plink:role name="InsertWrongTypeFullQualSql_myrole" portType="tns:InsertWrongTypeFullQualSql_sqlsePortType"/>
    </plink:partnerLinkType>
</definitions>
